### ISSUE TITLE
 Order of things for announcements, a 15 point plan....

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1000]
I know that this isn't all website, but I wanted to have a list with the order of events.

1.  Add icons to the newsfeed
-  [x]  @kimrutherford https://github.com/pombase/website/issues/761

2.   JBrowse Gene Page images and documentation  
- [x] @mah11  add item to news feed
- [x] @kimrutherford make JBrowse Gene Page images and documentation  live
- [x] @kimrutherford tweet with image (hashtags?)
- [x]  @mah11 Announce to pombelist

3. Unknowns paper
- [x]  @ValWood upload to bioarchive (today hopefully)

once live:

- [x] @kimrutherford tweet with image from figure 4
- [x]  @mah11  add item to newsfeed (image for thumbnail is  already in dropbox directory)

text for editing

Hidden in plain sight: What remains to be discovered in the eukaryotic proteome? Conserved unstudied proteins pose both challenges and opportunities for diverse areas of basic and applied biology.  In recent years the pace of characterisation has slowed. Here, we provide: Metrics to define unknown lists;  Unknown inventories for human and yeast; Classification of _S.  pombe_ unknowns by numerous orthogonal attributes;  Describe possible reasons for neglect. Our unknowns paper is now on bioarchive <<link>>. 

- [x]  @kimrutherford  retire the current 'pinned'  browse the unknowns inventory to the archive
and add  a new pinned item, replacing the  hand-scribbled image with figure 3, and changing the text to link to the bioRxiv 

- [x]  @kimrutherford  tweet/retweet?  that the  paper  is now on bioarchive (with figure 3 image)

- [x]  @ValWood  announce  paper to pombelist based on edits to newsfeed post

4. Announce new visualization tool (QuiLT)

- [x]  @kimrutherford to make "QuilT  live, with documentation links (check
https://github.com/pombase/website/issues/984 )

- [x]  @mah11 provide announcement for newsfeed.

Draft announcement. @mah any suggestions? :

Based on figure 3 in our unknowns paper <link>,  we have added an extension (QuiLT) to our Advanced Query Tool that allows you to create a similar figure for any gene list you create or import.

To access the QuiLT graphical view, use the ‘Visualise’ icon at the top right of the results list. This view is interactive, you can
- Highlight and drill-down into ‘sub-lists’ (filter)
- Reorder your lists to focus on features of most interest
- Download the image

(Image for newsfeed thumbnail is in the new folder)

- [x] @ValWood  Announce to pombelist based on Midoris edits./ Crediting Kim

I will also add this note (or similar)
(Note that we have created a precedence list for a defined subset of GO terms, so that each gene product is annotated to a single GO term, read the documentation to <<link to XXX>> for more)

- [x]  @kimrutherford  Tweet  for new tool

I got this  137 characters with spaces: Any suggestions?
View orthogonal data-types for a list simultaneously, currently GO-slims, viability, conservation. https://www.pombase.org/query ->Results->Visualise

Image for tweet:

![qlt-tweet](https://user-images.githubusercontent.com/7359272/47370446-a0e0be80-d6dd-11e8-9394-a79ab31dae1e.jpg)

**Comment by ValWood** [comment]
- [ ]  formalise where to put the images and how to name them. I'm happy to skip the dropbox step if I can put them somewhere more convenient. I never know the best way for this stuff...

**Comment by mah11** [comment]
Dropbox is fine as long as someone deletes stuff every now and then. But their final destination is the assets directory or one of its subdirectories.

https://github.com/pombase/website/tree/master/frontend/src/assets

**Comment by kimrutherford** [comment]
> I got this 137 characters with spaces: Any suggestions?

The maximum is 280 characters for a tweet now.  Images are free.  LInks are deducted from the count.

I'll have a go at a longer text.

**Comment by ValWood** [comment]
Oh blimer where have I been, I had no idea- I did think they often looked longer!

**Comment by kimrutherford** [comment]
The JBrowse inline browser is live.

~Ensembl browser~

**Comment by mah11** [comment]
I am finding this ticket very difficult to follow -- it contains at least three tickets' worth of topics and material -- so it's entirely possible that I've missed a task somewhere. But I've drafted some text for various things I did find. Both news items are now in github; the unknowns ms one needs bioRxiv URL for link, and both need the front-page flag (and because they're not live, further edits would be fine).

-----

Unknowns ms news:
Hidden in plain sight: What remains to be discovered in the eukaryotic proteome?

In a new publication, PomBase curators consider the challenges and opportunities that conserved, but persistently unstudied, proteins pose for diverse areas of basic and applied biology. To draw attention to these proteins, we develop metrics to define unknown lists, provide unknown inventories for human and yeast, classify S. pombe unknowns by numerous orthogonal attributes, and speculate about reasons for their neglect.
A pre-publication manuscript is available at bioRxiv.

-----

QuiLT announcement:
PomBase now offers a new way to display gene lists graphically based on multiple orthogonal annotation types - the Quick Little Tool (QuiLT) for visualisation. 

Inspired by our recent analysis of conserved unstudied proteins (see figures 3 and S1 in the manuscript at bioRxiv), QuiLT allows you to create a similar figure for any gene list you create or import using the advanced search. To use QuiLT, follow the link to your search results, then click the "Visualise" button. QuiLT visualisation is also available from the PomBase pages that list genes annotated to an ontology term, and on the Priority unstudied genes page.

The QuiLT display is interactive, and you can:

- Highlight subsets of the list, and filter the display
- Toggle annotation types on and off
- Reorder the list to focus on features of most interest
- Download the image

Note: For GO annotations, QuiLT can only use one term per GO branch (molecular function, biological process, cellular component) per gene. We have therefore created a precedence list for a defined subset of terms in each GO branch that determines which term is used for any gene product that is annotated to more than one.

See the QuiLT documentation for more information, and contact the curators if you have comments, questions or suggestions.

Many thanks to our star (and only) programmer, Kim Rutherford, for developing QuiLT (and the rest of the PomBase website).

-----

QuiLT news:
same as announcement, minus the Note paragraph; headline "See your genes in a QuiLT"

-----

QuiLT tweet suggestion (221 chars):
Draw an eye-catching QuiLT from your favorite gene list using PomBase's new visualization tool. Search at https://www.pombase.org/query -> Results -> Visualise to show viability, GO slim terms, and orthologs.

**Comment by ValWood** [comment]
The reason these are all in one ticket is that the order is important. It's really only to get the various announcement lined up in the correct order because I couldn't hold it n my head.

**Comment by mah11** [comment]
For those of us not in your head, it would be vastly less confusing to use separate tickets, and link them or even just include some text describing the order (e.g. "requires # 123" or "do this after # 456").

**Comment by kimrutherford** [comment]
>  tweet/retweet? that the paper is now on bioarchive (with figure 3 image)

Figure 3 is a flowchart. Do you mean figure 4?

**Comment by ValWood** [comment]
Yes we put another figure in (I think) it moved anyway!
Do you have the figure for the twwet?  The news item is in place, I see it on dev...
http://pombase-dev.bioinformatics.nz/news
but needs a line editing.

(remember to HT WT in tweet)

**Comment by kimrutherford** [comment]
I've sent a tweet and a follow up with the figure.

> (remember to HT WT in tweet)

I remembered this time :-)

I've updated the text of the news item and it should be visible in 10-ish minutes.

**Comment by ValWood** [comment]
brill.....
I'll announce on pombelist on Monday, I think... will see, might do it sooner...

**Comment by ValWood** [comment]
Could you retire  (archive)  the current "pinned resource  spotlight" and make a new one with the 
fig 4 image pinned and a link to the list, and to BioRix?

**Comment by kimrutherford** [comment]
> Could you retire (archive) the current "pinned resource spotlight" and make a new one with the
> fig 4 image pinned and a link to the list, and to BioRix?

I thought it didn't make sense to have the older unknowns spotlight in the archive.  So I've just bought it up to date and changed the image.  I've added a link to the pre-print.

**Comment by ValWood** [comment]
Kim you can move "Quilt" to live tomorrow,  and put on the news feed. then I will announce to pombelist.

**Comment by kimrutherford** [comment]
The current new item text says:

```
Inspired by our recent analysis of conserved unstudied proteins (see figures 3 and
S1 in the ...
```

Should that be figure 4?

**Comment by ValWood** [comment]
yes well spotted!

**Comment by kimrutherford** [comment]
> It's live now and the news feed item is there too.

After seeing it on the main site I realised that there was no link to the documentation.  I've fixed that now but let me know if we should move the link.

**Comment by ValWood** [comment]
I announced Quilt to pombelist so tweet it when you get chance.
Val

**Comment by ValWood** [comment]
Then this can close.....

**Comment by ValWood** [comment]
remember to tweet the image (cancer -related genes quilt)

**Comment by ValWood** [comment]
That isn't the cancer related genes quilt, its something mitochondrial....
We don't need to say what it is anyway...

**Comment by kimrutherford** [comment]
> I announced Quilt to pombelist so tweet it when you get chance.

Thanks for the announcement.  I've tweeted about it: https://twitter.com/PomBase/status/1065373066002227202

**Comment by kimrutherford** [comment]
> I've tweeted about it: https://twitter.com/PomBase/status/1065373066002227202

Tweeter seems to be 90% people sharing Thanksgiving recipes today (slight exaggeration there).  Possibly Monday would have been a better launch date.  Oh well.  We can tweet about it each time we make a change in future.

**Comment by ValWood** [comment]
Yes I did think after the fact that is was Thanksgiving...oh  well...
