### ISSUE TITLE
inconsistent numbers stats page

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1002]
According to the Canto curator summary on the stats page, a total of 565 publications have been community curated.

but in the community annotation response rate section
To date 1361 publications have been assigned to community members for curation. 571 are finished and are either in the main PomBase database or are currently being checked by the PomBase curators.

shouldn't the numbers 565 and 571 be the same?

**Comment by kimrutherford** [comment]
I see different numbers.  Are you looking at https://curation.pombase.org/pombe/stats/annotation ?

Is see 616 that are community curated and 623 "are finished and are either in the main PomBase database or are currently being checked by the PomBase curators."

The difference is because the second number includes publications that have been submitted but not approved.

**Comment by Antonialock** [comment]
thanks. The difference in number is because I changed the status of Jacky, and then changed it back
