### ISSUE TITLE
FAQ update / locating rDNA

### ISSUE THREAD

**Issue by ValWood** [pombase/website#105]
Gerry
On PomBase, I found it hard to locate the info on the rDNA.  Could you link "rDNA" to the page with "are-there-any-rdna-repeat-sequences-pombase" and to its predecessor page ("genome regions")?  Similarly for "rRNA". These two terms bring up pages but those don't contain all the info I needed.

**Comment by ValWood** [comment]
I'm looking at the FAQ and I don't fully understand the request here? Can anybody figure what needs linking to where?

**Comment by Antonialock** [comment]
no...the genome region page
http://www.pombase.org/browse-curation 

already links to this FAQ item
http://www.pombase.org/faqs/are-there-any-rdna-repeat-sequences-pombase

And the FAQ item links to relevant gene pages and the browser

.....
maybe we should link to the FAQ item from here?
http://www.pombase.org/downloads/datasets

**Comment by ValWood** [comment]
perhaps he just want to find the gene pages.
This might be a bit hard if you don't know the sys ID because they don't have "traditional" common names
http://www.pombase.org/spombe/result/SPRRNA.43

**Comment by mah11** [comment]
I have added a FAQ on finding rRNA genes; it and the rDNA sequences FAQ now link to each other.

Like you, I'm not sure what else Gerry might want. Reading his message, it's possible that he wants to be able to search for the string "rDNA" or "rRNA" and retrieve sensible results (not sure if that would be in the simple, advanced, or both search(s)). If that is what he means, he's out of luck in the short term, and we'll have to have a chat with Kim to see if anything is both sensible and feasible further down the line.

I don't want to add any FAQ links to download pages in Current PomBase, because that would set a precedent that could make too much busy work for me (once you add one, where do you stop?). We should have better options for sprinkling helpful hints and documentation links throughout Shiny New PomBase.

So I'm going to close this on the grounds that we've done as much as it makes sense to do at present.

**Comment by ValWood** [comment]
(not sure if that would be in the simple, advanced, or both search(s))

both  *almost * work.

You can find all of the rRNAs  using "genes by type" rRNA in advanced query....

All rRNAs contain RRNS in systematic ID, so if you search on *rRNA* you get them all, but because currently no faceting on datatype, you also get things with *rRNA* in the product too....
User just needs to know about wild-card and naming convention ;)


But I agree, enough for now!
