### ISSUE TITLE
dissemination figure

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1083]
I made a "dissemination" figure. Primarily for the grant  (we have 2 pages for figures)

![dissemination](https://user-images.githubusercontent.com/7359272/50547648-f8e3f600-0c35-11e9-93c9-469a89001c4a.jpg)

Can probably be improved a lot, suggestions welcome.

The main purpose it so emphasize the types and variety and numbers of resources we disseminate data to, but importantly how the GO annotations is then used for inference, so it was important to separate these somewhat in the figure.

Aesthetically  it could be improved (especially  the inference part).
But, we could use this version as a "resource spotlight", with a "Why curate...message"
(...curated data is disseminated to and linked from many data resources)

We can also use a more refined version in the "community curation porter"

**Comment by ValWood** [comment]
Importantly did I miss any resources we disseminate to (I just added "MARVELL")

**Comment by ValWood** [comment]
Importantly did I miss any resources we disseminate to (I just added "MARVELL")

**Comment by ValWood** [comment]
Yes 500, million is wrong! That's the total annotations.... it's 597,000

**Comment by ValWood** [comment]
updated
![dissemination_circle](https://user-images.githubusercontent.com/7359272/50563786-e2ae6680-0d17-11e9-8537-7679894876d0.jpg)

**Comment by ValWood** [comment]
Yes. It might also be better to have the big circle on the left and  the dissemination on the right (more logical for modelling the dissemination).

**Comment by kimrutherford** [comment]
I think so too.  It would flow better.

**Comment by mah11** [comment]
I've had a quick look at this at last .. some thoughts 

- What about keeping PomBase in the middle, to give the impression of data lovely data oodles of wonderful data (oops, sorry got carried away) flowing from pombase in all directions?

- I'm afraid the colored circle isn't doing it for me. The big blocks are nowhere near as good as arrows for conveying the idea of something - in this case, data - moving from point A to point B. It's also not clear whether the relative size matters, nor why phenotypes, modifications, and interactions are grouped together. The text "primary dissemination" also looks like it's an additional description for PomBase. (Honesty compels me to acknowledge that the way it reminds me of [this game](https://en.wikipedia.org/wiki/Simon_(game)), even though I didn't play it much, may also contribute.)

- Moving on, if all of the data dissemination routes have arrows, then the numbers and accompanying text (e.g. 3530 curated orthologs) can move to be sort of like labels on the arrows, which will reduce clutter and make it clearer which numbers go with which arrows/data destinations.

- I haven't got any great ideas about how to show the GO annotation transfer thing, and distinguish it from sending PomBase GO annotations themselves out to the world. It may well help to move GO to the bottom of the circle, so that a tier of shared-with-these-recipients pombe annotations will fit between the central PomBase logo and a tier of annotations inferred by transferring pombe annotations to orthologs.

- smaller things I also recommend:
  - use the PomBase logo without the strapline
  - move the FYPO logo, or delete it. where it is now, it looks like it's one of the destinations for disseminated data
  - use broken lines and/or lower color saturation - but same color - for planned/proposed/envisioned (but not yet happening) dissemination.
