### ISSUE TITLE
active form PR:000044777 for pcn1 (SPBC16D10.09)?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#112]
pombase.org shows "active form PR:000044777" as an extension in the GO Biological Process section on the pcn1 (SPBC16D10.09) page.

It's missing from PomBase v2.

**Comment by ValWood** [comment]
2 related tickets, about how to display the PRO ID:
https://github.com/pombase/website/issues/100
https://github.com/pombase/website/issues/67

**Comment by kimrutherford** [comment]
I've added the missing active forms and they are links to PRO.

**Comment by ValWood** [comment]
Hmm,
We need to unpick this a bit.
"active form" might be the relationship type. It has a special meaning and means that the protein binds to the "active form" of another protein (activation may be caused by a different independent event).
So not all of these are "active forms"

On the cdc2 page I see
![problem cdc2](https://cloud.githubusercontent.com/assets/7359272/21801715/bff14548-d71a-11e6-8a9a-ed8b7fe03c1a.jpg)

and at least one of these isn't an "active form"

We need to advise    how these are curated and how to interpret.
Also what we display  has always been a bit unsatisfying for user interpretation. It is unclear sometimes if the "PRO" ID  refers to the bound molecule or the thing bound  because you only see the ID.

We might need to do something more like:

cdc2(unphosphorylated form) binds chk1
cdc2(phosphorylated form 1) binds cdc13
cdc2(phosphorylated form 2) binds cdc13


we also discuss the display in
https://github.com/pombase/website/issues/100
https://github.com/pombase/website/issues/67
https://github.com/pombase/curation/issues/1008

So this should be high on curators list to discuss!

**Comment by mah11** [comment]
> "active form" might be the relationship type

No, "active form" is the display text used with a PR:nnn ID that we put in column 17.

> means that the protein binds to the "active form" of another protein

No, they show which form of Cdc2, i.e. the gene product annotated to "protein binding", does the binding to the other protein. To say that a specific form of Cdc2 binds a specific form, active or otherwise, of (e.g.) Cdc13, we would put a PR ID in column 16, and the broken pombase 1 display would have "binds PR:nnnn1 active form PR:nnnnn2".

> So not all of these are "active forms"

Yes, they are all forms of Cdc2 "active" for binding to the other protein indicated by "binds". 

> we also discuss the display in [tickets]

The example in #67 is of a PR:nnn id used in an extension (GO column 16). I'll transfer your display suggestion there, because that ticket started life as our "how should we display PR" home.

#100 is about what the hyperlinked text should be. Names are usually better than IDs, but some PR names really challenge that.

We should not let https://github.com/pombase/curation/issues/1008 distract us here, because it's mainly about which display text gets used for an extension relation. It's completely coincidental that the example there happens to be a PR:nnn ID (tho a couple of comments there did follow that tangent), and the open website tickets cover everything.

I agree that we should try to come up with a way to make all of this clearer, if even the senior PomBase curator can't get it from the existing display.
