### ISSUE TITLE
upcoming research spotlight, Bird

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1131]
![model](https://user-images.githubusercontent.com/7359272/52285619-9c73a500-295e-11e9-9279-4912e409acb5.jpg)

Zinc transporters belonging to the Cation Diffusion Facilitator (CDF) family have complementary roles in transporting zinc out of the cytosol.

PMID: 29529046
Originally published in Plos Genetics
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1007262

(waiting on GO,FYPO and PECO)

**Comment by ValWood** [comment]
- [ ] Also need to post compose the GO terms a little

**Comment by ValWood** [comment]
This session is through so this research spotlight can go live.
I must learn  how to do this!

**Comment by kimrutherford** [comment]
That went live yesterday.

**Comment by ValWood** [comment]
note to self The  publication page is blank
https://www.pombase.org/reference/29529046
although I thought I approved it before the shut down, it maybe did.'t make the data load.

**Comment by kimrutherford** [comment]
I'll investigate that once oliver1 is back online.

**Comment by kimrutherford** [comment]
> note to self The publication page is blank
> https://www.pombase.org/reference/29529046

I checked now that we have a fresh load and that page is still Sad Pombe.

But it turns out that the publication is in the main site and the link in the Spotlight was wrong.  I was able to check in a fix to the config file in SVN while logged in to oliver1 directly.  I still can't access pombe-embl externally though.
