### ISSUE TITLE
Announcement etc for unknowns paper Feb. 20

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1150]
Gahh, I nearly forgot about this.

- [x] @kimrutherford  tweet

- [x] @mah11 newsfeed
I'll let you suggest text. We can add links to articles and blogs as they appear.

- [x] @mah11 or @kimrutherford  "explore Pombase rotation"
a) 
Reuse  "Explore PomBase: Browse our inventory of conserved proteins with no known biological role" image
b)
Our "Unknowns" manuscript is now published in Open Biology (URL). You can access the fission yeast "unknowns" here (link), click the "visualise" button to explore the data interactively in a new tool (QuiLT) inspired by figure 4.
c) pin this one

**Comment by mah11** [comment]
>  @mah or @kmr "explore PomBase" item

This will require svn to be working. I'm happy to do it as soon as it is.

**Comment by mah11** [comment]
News is in github now.

I also have file edits ready to commit as soon as svn is back for the "explore pombase" bit.

**Comment by ValWood** [comment]
@kmr remember to hashtag WT

@Antonialock you can do a linkedIn post of the news features maybe too?

**Comment by kimrutherford** [comment]
> I also have file edits ready to commit as soon as svn is back for the "explore pombase" bit.

Can you send the changes to me?  I should be able to either check in the change slightly manually while logged into oliver1 or put the edited file in the right place so the website releasing system picks it up.

Releasing is going to be a pain until Babraham fix their firewall.  The releases are built on oliver1 then copied to Babraham but since oliver1's IP address has changed that's not possible - the Babraham firewall is blocking the new IP address.  It also means tonight's release isn't going to happen.

If Babraham are slow updating their firewall tommorow, I can make a release by copying things to my NZ desktop then copying to Babraham.  Not very efficient but it would work.  My desktop IP address is allowed by the Babraham firewall.

> @kmr remember to hashtag WT

Will do!

**Comment by mah11** [comment]
> Can you send the changes to me?

emailed to @kimrutherford off-ticket

I've also added the Open Biol link to the news item.

**Comment by kimrutherford** [comment]
> emailed to @kimrutherford off-ticket

Thanks.  The updated Unknowns Spotlight is now on the main site.

> I've also added the Open Biol link to the news item.

That's updated too.

**Comment by Antonialock** [comment]
linkedin and fb of award and paper

hashtagged WT

**Comment by kimrutherford** [comment]
All done!  (I think)
