### ISSUE TITLE
problems with ftp downloads

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1178]
From the survey

I've never been able to get the data set downloads to work - get promoted with a login screen as a guest or registered user, but can never connect. Maybe some better instructions on how to get that connection to work?

I noticed a couple of others saying downloads didn't work...

We need to track this...

**Comment by mah11** [comment]
I have added a new FAQ and notes on the top-level downloads pages. That's all we can do, because the behavior is entirely due to how some browsers handle the ftp protocol.

If anyone has trouble connecting as "guest", we would need more detail about what they tried - and then it would still likely turn out to be out of our hands to remedy.
