### ISSUE TITLE
Google search - SPBC15D4.14

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1208]
Google search doesn't find:SPBC15D4.14
https://www.pombase.org/gene/SPBC15D4.14

probably not much we can do about it but I thought I would mention it

**Comment by ValWood** [comment]
This is weird isn't it?
Page still isn't found

**Comment by ValWood** [comment]
even with
SPBC15D4.14 pombase

**Comment by kimrutherford** [comment]
It's been a while but I've come back to this because it will help long term to improve our Google search ranking.

I've changed things so that Google now sees a very simple version of the gene pages with only the useful keywords.  The simplified pages look like: https://www.pombase.org/simple/gene/SPBC2F12.13

That version is only shown to the Google and Microsoft web crawlers for now.  Everyone else will still see the usual page:
https://www.pombase.org/gene/SPBC2F12.13

If this works out and the Google crawler errors for the gene pages start to decrease, I'll do the some thing for the term and reference pages.

**Comment by ValWood** [comment]
sounds good!

**Comment by kimrutherford** [comment]
> If this works out and the Google crawler errors for the gene pages start to decrease, I'll do the
> some thing for the term and reference pages.

I did that a while ago and it's all looking good now.  SPBC15D4.14 is indexed and show a reasonable summary in the Google results page.

I'll close this issue and we can open new issues when we spot problems.
