### ISSUE TITLE
put the cursor in the search box

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1234]
Martin and Sam have both asked for this.

I think we had a reason not to do it but I can't remember what it was?

**Comment by mah11** [comment]
I think we did agree to do this on the home page, and if it hasn't been done, the reason is that we forgot.

We haven't done it elsewhere because I absolutely loathe having to click away from search boxes on pages that have content themselves (PMC, I'm lookin' at you). On gene pages, pub pages, etc. I want my keystrokes to navigate the page I'm on, not type in the search box.

**Comment by ValWood** [comment]
I agree. From the home page most likely destination is the search box, but from gene pages you are more likely to want to navigate. In fact if you just did a search the cursor is there already so most people should be happy with this...

**Comment by kimrutherford** [comment]
I dislike the cursor going to an input box automatically because it messes with scrolling.  I usually use the space key to scroll down.  If the cursor is in an input field that doesn't work.  In Firefox even page-up and page-down don't work until you click outside the input field.

> From the home page most likely destination is the search box, but from gene pages you are more
> likely to want to navigate

Limiting the change to the front page would make the scrolling problem less painful.

**Comment by mah11** [comment]
> I dislike the cursor going to an input box automatically because it messes with scrolling.

+1000 (the thumbs-up button only adds +1)

> In fact if you just did a search the cursor is there already

... yes, and it *drives me nuts*

**Comment by kimrutherford** [comment]
> I dislike the cursor going to an input box automatically because it messes with scrolling.

On the other hand when I do want to search it's annoying to have to click.

**Comment by ValWood** [comment]
Shall we just close this. I wanted to at least mention everything, but this will never please everyone...

**Comment by kimrutherford** [comment]
Yep, let's close it.  But if we see any other site that has a clever solution to this we should re-open.
