### ISSUE TITLE
Gene page link to KEGG pathway that highlights the position of the gene product within the pathway.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1239]
from https://github.com/pombase/website/issues/763

Antonia:

Example pathway+gene: LRP1/cti1 (shown in red) within RNA degradation
https://www.genome.jp/kegg-bin/show_pathway?spo03018+SPCC1739.07

Here is a pathway - pombe gene name mapping file:
http://rest.kegg.jp/link/pathway/spo

Some genes have more than one pathway mapped to them, but I think it's max 3 or 4 in those cases.

**Comment by ValWood** [comment]
Links would be: 

Pathways
KEGG 
ID (link above)
pathway name  (this would need to come from another look up table)

**Comment by ValWood** [comment]
pyruvate metabolism
https://www.genome.jp/kegg-bin/show_pathway?spo00620+SPAC186.02c

**Comment by kimrutherford** [comment]
> Some genes have more than one pathway mapped to them, but I think it's max 3 or 4 in those cases.

Would we have 3/4 links to KEGG in that case?

**Comment by ValWood** [comment]
yes, multiple links .

**Comment by ValWood** [comment]
How trick is this?

**Comment by kimrutherford** [comment]
> How tricky is this?

Do we have the KEGG IDs for each gene?

**Comment by ValWood** [comment]
Genes  seem to use pombase IDs .   spo:SPCC1739.07
https://www.genome.jp/dbget-bin/www_bget?spo:SPCC1739.07

 but  not all pombe genes are in KEGG

We would need to use the pathways to extract the genes.

**Comment by kimrutherford** [comment]
In your other example link there is a "spo00620" ID.  Do we need those links?:

https://www.genome.jp/kegg-bin/show_pathway?spo00620+SPAC186.02c

**Comment by ValWood** [comment]
"spo00620" is the pathway ID.
those are the ids in http://rest.kegg.jp/link/pathway/spo mapped to the spo:spac

**Comment by kimrutherford** [comment]
OK, thanks.  I should have followed that link.  :-)

The easiest way to do this is to load those pathway IDs into Chado and attach this to the genes.  I'll work on that.

**Comment by kimrutherford** [comment]
> The easiest way to do this is to load those pathway IDs into Chado and attach them to the genes.


That's done now.  Still need to implement the website side of things, including:
> pathway name (this would need to come from another look up table)

**Comment by ValWood** [comment]
Where is this one up to. It isn't super urgent but it would be nice if it's available...

**Comment by ValWood** [comment]
i.e I can put at low priority, but that seems a shame if it is  quite  close...

**Comment by kimrutherford** [comment]
I think we just need to work out this bit:

> pathway name (this would need to come from another look up table)

We have the path IDs loaded but you mentioned pathway names.  What do they look like?  Do you have any idea where to download them from?  I'm happy to investigate.

**Comment by ValWood** [comment]
I see the list here:
https://www.genome.jp/kegg/pathway.html but I cannot find this  as a text file anywhere on the site.

Note that  for example for spo00620  only the digit part is required
 so
00620 =  pyruvate metabolism

**Comment by mah11** [comment]
Hmm. There's FTP access, but even academic users have to pay for it ($2000/year outside Japan).

There's a REST-style API at https://www.kegg.jp/kegg/rest/keggapi.html if that's any help.

Or maybe you can glom on to the results of a search in their DBGET thing - go to https://www.genome.jp/dbget/ and "Search KEGG PATHWAY for 'map'". I get 537 hits, which looks like the right ballpark. The [results URL](https://www.genome.jp/dbget-bin/www_bfind_sub?mode=bfind&max_hit=1000&dbkey=pathway&keywords=map) looks like it may even be stable.

**Comment by kimrutherford** [comment]
We can get KEGG IDs like "00630+1.11.1.6" from Fungi BioMart.  Those IDs can be linked to pages like this: https://www.genome.jp/kegg-bin/show_pathway?map00630+1.11.1.6

Is that any use?

**Comment by kimrutherford** [comment]
> We can get KEGG IDs like "00630+1.11.1.6" from Fungi BioMart.

There are 1300 or so genes with those IDs in BioMart.

There are also 280 genes that have IDs like "MAP00630" which we can link to pages like this: https://www.genome.jp/dbget-bin/www_bget?path:MAP00630

**Comment by ValWood** [comment]
I think ideally we wanted gene specific links like this:
https://www.genome.jp/kegg-bin/show_pathway?spo03018+SPCC1739.07
https://www.genome.jp/kegg-bin/show_pathway?spo00510+SPAC7D4.06c

because they covered non enzymes too.

I think you loaded the mapping (reading above)

**Comment by ValWood** [comment]
I did not read to the end. I see it is trickier...

**Comment by kimrutherford** [comment]
I forgot that I'd loaded the pathway IDs.  It was the pathway names that were a pain.  I couldn't remember what the hold up was.  I should have read the comments.  :-)

> I see the list here:
> https://www.genome.jp/kegg/pathway.html but I cannot find this as a text file anywhere on the site.

I can probably download that page and extract the pathway IDs and names if necessary.  Do the numbers on that page (like "00010") match up with the pathway IDs we have loaded (like "spo00010")?  There are also IDs like "map00010" in KEGG.  Do you know if those are the same IDs with a different prefix?

> Some genes have more than one pathway mapped to them, but I think it's max 3 or 4 in those cases.

Having thought about this, since the pathways have an ID and a name and there may be more than one per gene, we might need to store these like annotations in Chado.  We'd need to make a fake ontology with KEGG pathways as terms.

Would it be OK to have a "Biological pathways" section on the gene pages?  We'd then get a page per KEGG pathway kind of for free.

If that makes sense I'll try to get back to this soon as it's not a big job.  (Assuming the different IDs make sense, "00010" versus "spo00010" versus "map00010")

**Comment by ValWood** [comment]
> Would it be OK to have a "Biological pathways" section on the gene pages? We'd then get a page per KEGG pathway kind of for free.

yes, that would be cool!

**Comment by kimrutherford** [comment]
> We'd need to make a fake ontology with KEGG pathways as terms.

I've finally got around to that.  It's here: `pombe-embl/mini-ontologies/kegg-pathways.obo`

I'll include it in the next load and then work on getting the KEGG ID loaded as annotations:

> Having thought about this, since the pathways have an ID and a name and there may be more than one per gene, we might need to store these like annotations in Chado.

After that it mostly just configuration.

Are these pages OK to link to?: https://www.genome.jp/kegg-bin/show_pathway?spo00100

**Comment by ValWood** [comment]
I think we want to link to pathway + gene
e.g.
https://www.genome.jp/kegg-bin/show_pathway?spo03018+SPCC1739.07
https://www.genome.jp/kegg-bin/show_pathway?spo00620+SPAC186.02c

**Comment by kimrutherford** [comment]
> I think we want to link to pathway + gene

OK, I'll work on that after I've loaded the annotations.

What reference/publication should we use for the annotations?

**Comment by ValWood** [comment]
PMID: 10592173 seems to be the most generic.

**Comment by kimrutherford** [comment]
I've had a first go at this.  I've made up an ontology (pombe-embl/mini-ontologies/kegg_pathways.obo) and loaded the KEGG pathways as real annotations in Chado (a feature, a term and a reference).

I wasn't able to find a definition/description for all the KEGG pathways so that might need work over time.  But they all have a name.

 - [ ] The fake KEGG term IDs have a "KEGG_PW:" prefix which is needed internally.  But those are a bit ugly and not helpful for users, so I plan to hide them from the display.  I'm hoping to do that before it goes live.

 - [ ] We might want to change the "Term ID" and "Term name" column headings to something more sensible for KEGG annotations

 - [ ] And the "Ontology term: ..." at the top of the term pathway path doesn't make much sense

- [ ] Perhaps a link to KEGG pathway page from the top of our pathway page would help?

Below are screen shots from my machine of a gene page and a pathway term page.  "KEGG" in the Source column are links to the pathway+gene pages.  This column is similar to the Source column for disease associations.

I've committed the changes and the should be visible on Monday morning.  

![pathways-1](https://user-images.githubusercontent.com/90474/123540094-5c145c00-d791-11eb-8210-3db08fb7d4c1.png)

![pathways-2](https://user-images.githubusercontent.com/90474/123540097-60407980-d791-11eb-9e4d-92a3820808b7.png)

**Comment by ValWood** [comment]
This will be awesome!

**Comment by kimrutherford** [comment]
I've fixed these three items for the morning:

> - The fake KEGG term IDs have a "KEGG_PW:" prefix which is needed internally. But those are a bit ugly and not helpful for users, so I plan to hide them from the display. I'm hoping to do that before it goes live.
>
> - We might want to change the "Term ID" and "Term name" column headings to something more sensible for KEGG annotations
>
> - And the "Ontology term: ..." at the top of the term pathway path doesn't make much sense

**Comment by kimrutherford** [comment]
> Perhaps a link to KEGG pathway page from the top of our pathway page would help?

That's done too now.

It's looking much tidier without the prefixes.  Let me know what else to change.

We have a KEGG publication page too that shows all pathway annotations.

![pathways-3](https://user-images.githubusercontent.com/90474/123563576-a89b7e00-d809-11eb-8cc9-5685b7d0dc2c.png)

![pathways-4](https://user-images.githubusercontent.com/90474/123563580-acc79b80-d809-11eb-9bac-a157859ebd22.png)

**Comment by kimrutherford** [comment]
Sorry, I forgot to check-in a file.  I have now so hopefully it will be visible tomorrow morning.

**Comment by kimrutherford** [comment]
It's all live now.  Example pathway page: https://www.pombase.org/term/KEGG_PW:spo01210

**Comment by ValWood** [comment]
Nice work  @kimrutherford , all looks good and will be very useful to us for model building,  we can maybe display our curated  GO-cam models in this section too...

@mah11  could you write announcements for pombelist and news section? 
They only need to be very basic- just to say that we now have a new section for linking to biochemical and signaling pathways- and currently provide KEGG pathways with associated link-outs and summary pages with gene lists, amnd ability to send lists to query builder.
(Aside, it is interesting to  intersect these lists with GO- for example there is no good GO term representing purine metabolism as represented by KEGG)

I did notice that what KEGG uses to represent pombe genes is a little inconsistent.
Some metabolic pathways use arrows, and some use unlabelled arrows, but in both cases you can get to the pombe gene. Non-metabolic pathways tend to use gene names.

e.g.s
https://www.genome.jp/kegg-bin/show_pathway?spo00620+SPAC186.02c
https://www.genome.jp/kegg-bin/show_pathway?spo01210+SPAC24C9.06c
https://www.genome.jp/kegg-bin/show_pathway?spo00510+SPAC7D4.06c

but in all cases fission yeast genes mapped  to KEGG pathways are highlighted in green, and the gene of interest  ( from a gene specific page) is in red.

**Comment by kimrutherford** [comment]
Thanks Midori for the news item and the pombelist post.

Val, is there anything else to do on this issue?

**Comment by ValWood** [comment]
No, I think now we wait for suggestions :)
Nice job.
@Antonialock  we are still implementing your tickets ;)

**Comment by Antonialock** [comment]
😂

**Comment by ValWood** [comment]
I hope you are going to check it out ;)
