### ISSUE TITLE
Improve data download documentation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1240]
DATA DOWNLOAD
- Easier access to genome datasets (better readme files on the ftp sites)
- Filter and download gff3 annotated database using different critearia (eg. genes with introns)
- I always have trouble figuring out what file type to download to get the info I want, so maybe little reminders of what the data looks like next to the links in 
- more detailed downloadable  data sets

**Comment by ValWood** [comment]
This was a recurring theme. So we need 

- [ ] The landing page looks a bit random https://www.pombase.org/datasets 

- [ ] A little bit more information on the file contents/description of each file or link to the README?

- [ ] maybe a link to specific FAQs for downloading sequence data and downloading curation

- [ ] are any of the messages out of date ? 

- [ ]  It frustrates me a little that I can see  some of the files before I download them  but not others

**Comment by ValWood** [comment]
and in column BQ
make protein or DNA download easier, like SGD!
I love pombase, but some of my students struggle with data download and formatting
I've never been able to get the data set downloads to work - get promoted with a login screen as a guest or registered user, but can never connect. Maybe some better instructions on how to get that connection to work?

**Comment by kimrutherford** [comment]
> get promoted with a login screen as a guest or registered user, but can never connect

Where's that coming from?  We don't have any logins.

**Comment by ValWood** [comment]
I think I have seen this sometimes when connecting to the ftp site (or I have heard about it)

**Comment by kimrutherford** [comment]
> I think I have seen this sometimes when connecting to the ftp site (or I have heard about it)

Ah, OK.  There some difficulties with FTP.  Perhaps we should move away from it?

We can already access all the FTP site via HTTP.   For example we can get this file:
`ftp://ftp.pombase.org/pombe/names_and_identifiers/gene_IDs_names_products.tsv`
using HTTP: https://www.pombase.org/datasets/names_and_identifiers/PomBase2UniProt.tsv

It's possible to browse as well: https://www.pombase.org/datasets/

**Comment by ValWood** [comment]
Yes that would be better.

Also I just reilised there are no "README's" in these directories, so I guess the old ones did not get copied over and updated. We should resurrect those and mirror in the docs (or on the  download web page if appropriate)

**Comment by kimrutherford** [comment]
It sounds like Chrome will drop support for FTP at some point so moving to HTTPS will become more urgent 


We can already access all the FTP site via HTTP. For example we can get this file:
ftp://ftp.pombase.org/pombe/names_and_identifiers/gene_IDs_names_products.tsv
using HTTP: https://www.pombase.org/datasets/names_and_identifiers/PomBase2UniProt.tsv

It's possible to browse as well: https://www.pombase.org/datasets/

**Comment by kimrutherford** [comment]
I hit return too early on my comment.  I've edited it now so it makes sense.  Here's the link I meant to include: https://chromestatus.com/feature/6246151319715840

**Comment by kimrutherford** [comment]
> It sounds like Chrome will drop support for FTP at some point. Moving to HTTPS will become more urgent then:
> https://chromestatus.com/feature/6246151319715840

They delayed this change for a while but they are getting on with it soon.

Firefox will be removing FTP support next year too:
https://groups.google.com/g/mozilla.dev.platform/c/FqCZUT9ay_o/m/jt4DLRDjAwAJ?pli=1

> It's possible to browse as well: https://www.pombase.org/datasets/

That URL doesn't work but this does:
https://www.pombase.org/ftp/
That's our whole FTP directory.  It would be good if we can think of a better prefix than "/ftp/" since FTP seems to going the way of the dodo.  We can't use the prefix "downloads" or "datasets" because those are already pages: https://www.pombase.org/downloads https://www.pombase.org/datasets

If we can decide on a root URL prefix I think we can fix a lot of documentation with search and replace of `ftp://ftp.pombase.org/` with `https://www.pombase.org/ftp/` (or whatever prefix we decide on).  There are also pages that will need to be fixed manually: https://www.pombase.org/datasets

We can keep the FTP server up and running indefinitely even if browsers doesn't support FTP any more.  It takes no extra work.

**Comment by mah11** [comment]
I don't have a problem with using "/ftp/" as the prefix, but then I'm also entertaining some unbridled get-off-my-lawn sentiments about browers dropping FTP support :P

If you don't like "/ftp/", is there anything wrong with "/data/"? Or I can keep thinking ...

Anyway, I'm happy to do the URL updates in the static page files.

> We can keep the FTP server up and running indefinitely even if browsers doesn't support FTP any more. It takes no extra work.

I like that plan. There are still codgers out there with command-line ftp clients.

**Comment by kimrutherford** [comment]
> is there anything wrong with "/data/"?

That would be fine I think.

**Comment by ValWood** [comment]
- [x] all the READMe's seem to be there
- [ ] some download links work for me but the ones on this page don't
 https://www.pombase.org/downloads/protein-datasets

**Comment by mah11** [comment]
I'm pretty sure the only thing outstanding here is whether to switch "ftp" to "data" in URLs (`https://www.pombase.org/ftp/` and everything under it). Once we do that, or decide not to, I can go in and change links from static pages to use https.

I guess I lean silghtly towards "data" since it won't be ftp any more, but no strong feelings really. I think we ought to decide soon, though, since it looks like Chrome has really dropped FTP support now :P

**Comment by mah11** [comment]
I've updated almost all of the links from ftp to https (the sole exception is in #1669).

I think it would make sense to close this ticket, and open a new ticket for anything that still needs changing once the linky update is live.
