### ISSUE TITLE
enable download of physical interactors of a list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1299]
final items from 
https://github.com/pombase/website/issues/576

This won't look pretty.

alm1       alm1,mtl1, paa1, paa1, par2
ams2      ams2,atg11,atg8,cut14,

etc

I don't think people will do it often, and probably not in combination with other columns because it's quite a specific type of query download

**Comment by kimrutherford** [comment]
> This won't look pretty.

It won't look that much worse than orthologs:
```
SPAC144.14   klp8   KIF13B,​KIF13A,​KIF16B,​KIF14,​KIF1C,​KIF1A
```
\- although the lines will be longer.

Implementing this is a bit more work than implementing the orthologs column.  Let me know when it becomes more of a priority.

**Comment by kimrutherford** [comment]
I've added physical interactors and a bunch of other options to the gene results tables in the dev website.  The options are available in the download dialog too.  Because of the way the results tables were implemented adding all those options was just as easy as adding one (physical interactors).

Could you have a look and see if any of the other extra columns are useful?  The new columns are mostly the ones from QuiLT but I also added molecular weight because it sounded useful.

It took quite a few code changes to get this working so please watch out for any weirdness or bugs.  Unfortunately I think it's slightly slower now but I think that's fixable.

Because of these changes it's now easy to add any other column you can think of.  For example number of exons would be quick to add.

This is not enabled in the main site yet.

**Comment by ValWood** [comment]
Which are the new ones. I tested a few.

Human orthoolog
physical interactors
protein lenght
all worked

GO is doing something a bit weird. It gives you one GO ID (I'm not sure which one, but it often seemed to be "gene expression (GO:0010467)" which is rarely used in direct annotation(if ever) but is a parent of lots of GO processes.

**Comment by kimrutherford** [comment]
> Which are the new ones?

Everything from Physical interactors onwards.

> It gives you one GO ID

It's the GO ID from QuiLT.  I put everything in for completeness in the dev site but I don't think they're all useful.  The GO IDs aren't going to be helpful for users.

**Comment by ValWood** [comment]
OK  in that case leave out GO. I think if GO downloads are enabled it will need to be a slightly different mechanism (GAF/GPAD). We can be userp-led on that. If they ask, we can do it.

**Comment by kimrutherford** [comment]
> OK in that case leave out GO.

The extra columns will be on the main site in the morning.

**Comment by ValWood** [comment]
Need a news item,

You can now download additional data types for genes from the "Download" option on the  Advanced search results page.
New options include: 
All physical interactors of a gene product
Deletion viability
Protein length
