### ISSUE TITLE
link FAQs for ncRNA FASTA format?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#13]
We are aware that these files are not available and we hope to rectify this soon.  You can get the Fasta via the Advanced query. See the FAQ 
http://www.pombase.org/faqs/how-can-i-retrieve-sequences-non-protein-coding-genes

This FAQ  describes how to get them from Ensembl.
http://www.pombase.org/faqs/s-pombe-transcriptome-available-fasta-format

**Comment by mah11** [comment]
I don't think it would make sense to link these, because they're not really about the same thing. The first is about getting DNA sequences for ncRNA features (and eventually any other feature types we may have or add). The second is about how to get transcript sequences, and isn't specific to ncRNAs. 

Instead I have added a link to it from the FAQ on getting sequences for features of whatever type (to which the nc feature FAQ already links).

**Comment by ValWood** [comment]
ok
