### ISSUE TITLE
make publication pages for sessions with other triage statuses

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1352]
I think
"curatable" and "Browser datasets, to host" get publication pages now, extend this to
"Browser datasets, hosted"

how about 
reviews
WT features
?

**Comment by mah11** [comment]
also see #1251

**Comment by mah11** [comment]
message discussion and suggestions in #627, #795, & #858 ... which also strongly imply that we did have publication pages for methods papers and reviews at the time

**Comment by kimrutherford** [comment]
I've changed the Canto code to export "Browser datasets, hosted", reviews and methods.

> We will need to change the message on these pages so it doesn't say:

I'll have a go at improving the message tomorrow.

**Comment by kimrutherford** [comment]
>I agree, reviews and methods should both get pages. We will need to change the message
> on these pages so it doesn't say:
>
> This publication has no annotations in PomBase because it hasn't been curated yet. (Please
> contact us if you would like to contribute annotations for this paper.)

I fixed a small bug in July.  It should now only have that message for publications triaged as "Curatable" and don't have an approved session.

For publications with these triage statuses:
      - Browser datasets, to host
      - Browser datasets, hosted
      - Method or reagent
      - Review or comment

it should show:
This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types

**Comment by ValWood** [comment]
I think this one can close?
