### ISSUE TITLE
Counts don't match the gene list on the term page

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#136]
The count at the top of the term page here:
  http://pombase2.bioinformatics.nz/term/FYPO%3A0003165

doesn't match the number of genes here:
  http://pombase2.bioinformatics.nz/term_genes/FYPO%3A0003165

It looks like the multi-gene phenotype annotations aren't being handled correctly.  Possibly only one gene is counted.

**Comment by ValWood** [comment]
I'm erring towards keeping single and multigene  phenotypes completely separate. I can't remember the exact outcome of our previous discussions. I think we were going to wait to see how the filters operated.

However, I don't think it makes so much sense to have single and multigene phenotypes in the same "others" list.
In fact the "others list" makes less sense for multigene phenotypes generally, so we did not offer it on the old site......

**Comment by ValWood** [comment]
Although maybe it will be OK.
If there is clearly a filter at the top for single or multi gene it could work.

But that leaves a problem with the default lists.
For example the default list for 

FYPO:0002061	inviable vegetative cell population 1596
while it is only  1455  for single mutants. I think this is what people will want as the default list...
But if there was a filter option also at the top of the list, it could still work (and  be better)?

Thoughts?

**Comment by kimrutherford** [comment]
> However, I don't think it makes so much sense to have single and multigene phenotypes in
> the same "others" list.

For phenotypes, should the "others" link show you a list of genotypes rather than genes?

**Comment by ValWood** [comment]
I think it could be.
However from the "others" genotype list, we would need a very prominent way to get to
single gene phenotypes (gene list) with a particular phenotype.

This is because data-mining  mining is done at the level of the gene and we need to be able to send gene lists to the query builder to combine with other (non phenotype) gene lists.

I still feel a bit uncomfortable about the gene list not being the default, but it should not be a big problem for users if there is an obvious way to get to  genes.

Once we have this implemented we can ask people about their preferences and  if it seems strange based on how they use the data...I might just be stuck in a rut

**Comment by kimrutherford** [comment]
The counts are fixed and I think the other comments are covered by #138.
