### ISSUE TITLE
sequence count for bases/nucleotides upstream of gene

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1382]
when displaying bases upstream of a gene, can we have a counter that starts at -1 (1st pos upstream? )

**Comment by ValWood** [comment]
where (I though we already did this?)

**Comment by Antonialock** [comment]
in the sequence section

here I am displaying 100 nts upstream of a gene, and I have selected number -1, but it shows as nt 100 is selected

<img width="550" alt="Screenshot 2019-07-31 at 15 15 39" src="https://user-images.githubusercontent.com/12727506/62219369-1b91e500-b3a6-11e9-877b-0f9a3ed061a1.png">

**Comment by kimrutherford** [comment]
It's the same problem for introns.

**Comment by ValWood** [comment]
How should this be classified? I'm not sure what th issue is?

**Comment by kimrutherford** [comment]
> I'm not sure what th issue is?

I think Antonia would like the coordinates shown after "Selected residues: " to be relative to the translation start point.  So that if you click on the first base in the coding region (like in Antonia's screenshot) it should always say "Selected residues: 1..1" no matter how many bases before that point are visible.

**Comment by Antonialock** [comment]
the count is currently arbitrary depending on how many bases you are displaying. 
We have the additional problem that TSS sites are not well defined so even -1 is not well defined (I guess the only position we can be fairly certain of is initiator methionine in a protien sequence). 

Maybe we can additionally show the genomic number of the base?

**Comment by ValWood** [comment]
Got it.
 
Show coordinates of selected bases relative to feature counting from A of ATG for 1 in CDS features.  
Yes, this would be much better.

Genomic coordinates would also be appreciated.

**Comment by ValWood** [comment]
>the count is currently arbitrary depending on how many bases you are displaying.
We have the additional problem that TSS sites are not well defined so even -1 is not well defined (I guess the only position we can be fairly certain of is initiator methionine in a protien sequence).

I don't understand this comment though. -1 is well defined because translation start site is well defined (its translation start not transcription start and we number the 5' UTR backwards from the ATG?)

**Comment by Antonialock** [comment]
ah yes, good. 

I was probably thinking of ncRNAs (tRNA starts?)

**Comment by kimrutherford** [comment]
> when displaying bases upstream of a gene, can we have a counter that starts at -1
> (1st pos upstream? )

Should this be instead of or as well as the current coordinate display?

> Genomic coordinates would also be appreciated.

That's trickier as the genomic coordinates change depending on what you're displaying.  For example introns in the upstream sequences can be turned on or off.

**Comment by Antonialock** [comment]
maybe integrated?... because the selected sequence might be part upstream of start and part downstream
e.g.
-3..5

**Comment by ValWood** [comment]
We understand, and we don't have any way to do exactly this, but you can restrict the length of the UTR. Since no one else has asked we are going to close this because there are workarounds.
