### ISSUE TITLE
suggestion: link to advanced search near simple search box

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#1402]
I am always surprised how many people say they dont use the advanced search. Maybe they cant find it?

should we have a link to the advanced search near the simple search?

**Comment by ValWood** [comment]
I think this is a good idea....

I also still don't think this is really a "search" though.  
Labelling it as an "advanced search" is part of the problem.

You *can* use it to retrieve entries, but it's primary purpose is not to find things, and I don't know anyone who would use it to locate a specific entry.
It's primary function is to combine lists (OK, you need to find the list first, but that's indirectly upstream of the   function of the tool)

As a user, as it is currently Iabeled I would never go to it instead of the "simple search" if I found what I wanted, because the way it is curently labeled gives me no clue that I can use it to build complex queries to mine the data.

**Comment by ValWood** [comment]
Adding "advanced search" button  close  to the search box would be good though.
Maybe a mouse over could say 
"retrieve, upload and combine lists" or some indication what you can do.

**Comment by ValWood** [comment]
Should we add another link to the 'advanced search" ?

**Comment by kimrutherford** [comment]
> Should we add another link to the 'advanced search" ?

I think an extra link will make things more cluttered.

**Comment by ValWood** [comment]
OK we can try to make it more prominent next time the front page is rearranged
