### ISSUE TITLE
Should HTP datasets provided by users be acknowledged as "community curated"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1435]
\
e.g.

https://www.pombase.org/reference/PMID:31077324

**Comment by kimrutherford** [comment]
> Should HTP datasets provided by users be acknowledged as "community curated"

I think if they help at all, even just putting a HTP file in the right format, they should be a acknowledged somehow.

**Comment by ValWood** [comment]
It's quite nice to keep the browser-hosted datasets in a separate category. Could we have a 'subcategory' for user-provided ones maybe?
Other ideas?

**Comment by kimrutherford** [comment]
> Other ideas?

It's a bit of a hack, but you could make and approve an empty community curation session for each of the user-provided datasets.

**Comment by ValWood** [comment]
We could do that, it would be fine. I was thinking that to show as curated they needed to be triaged as curatable? but maybe they don't?

**Comment by ValWood** [comment]
OK work around is to ensure that the session is assigned to the user.

Check other HTP data sets have community attribution.

**Comment by kimrutherford** [comment]
These publications have browser trackers are admin curated in Canto (according to Chado):

```
 PMID:18488015
 PMID:21511999
 PMID:25908789
 PMID:32101745
 PMID:18093330
 PMID:14566325
 PMID:17304213
 PMID:25747261
 PMID:24256300
```

These three are not curated in Canto for various reasons:

```
 PMID:11859360      (pombe genome paper) 
 PMID:25361970      (PomBase NAR paper)
 PMID:26883383      (this one probably should go through Canto)
```


The publications for the other 16 tracks are community curated in Canto:

```
 PMID:25240800
 PMID:21981922
 PMID:23101633
 PMID:23163955
 PMID:31077324
 PMID:32152323
 PMID:30566651
 PMID:24152550
 PMID:21151114
 PMID:23900342
 PMID:22531001
 PMID:23395004
 PMID:27662899
 PMID:25665008
 PMID:29914874
 PMID:24709818
```

**Comment by mah11** [comment]
I checked the papers on Kim's "admin" list:

| PMID |  note |
|---------------|---------------|
| PMID:25908789 | Antonia did the LTP curation; see below|
| PMID:32101745 | Val did the LTP curation; see below|
| PMID:18093330 | Antonia did the LTP curation, and paper is fairly old, with no indication that the browser data was an author submission|
| PMID:14566325 | paper is fairly old, and there's no indication that the browser data was an author submission|
| PMID:17304213 | Antonia did the LTP curation, and paper is fairly old, with no indication that the browser data was an author submission|
| PMID:25747261 | reassigned session to Hua Li|
| PMID:24256300 | reassigned session to Paco Antequera|

So that leaves an outstanding question: do you want me to reassign the sessions for the ones that have both author submissions for the browser data and some annotations from us (PMID:25908789 and PMID:32101745)?

The rest are done (session reassigned, or admin classification was fine).

I also put a session through for PMID:26883383.

**Comment by ValWood** [comment]
Maybe this isn't worth worrying about as it affects so few?
and we are just mindful going forward (and also try to get the authors to do their own small-scale stuff)

**Comment by mah11** [comment]
Your call ... I've got as far as is reasonable. Just those two papers to reassign, or not, and this can close.

**Comment by ValWood** [comment]
Closing if no indication...
