### ISSUE TITLE
wow

### ISSUE THREAD

**Issue by ValWood** [pombase/website#147]
;) I hadn't seen this!

![funky](https://cloud.githubusercontent.com/assets/7359272/22602615/e04e8e70-ea3b-11e6-9116-5f38ba1e05fb.jpg)

**Comment by ValWood** [comment]
this is so cool, I wasn't even thinking of asking for stuff like this for a while, as I thought it would take ages:
very useful...

![cool](https://cloud.githubusercontent.com/assets/7359272/22607870/b94b4924-ea51-11e6-9718-77a0e2fafcfd.jpg)

**Comment by ValWood** [comment]
This... is.... just... so....cool.....

http://pombase2.aska.gen.nz/term/GO%3A0004672

**Comment by ValWood** [comment]
In this view the "gene" should be in the default view, and be more "primary"

**Comment by kimrutherford** [comment]
> In this view the "gene" should be in the default view

Do you mean the summary view?  We would need to think about how to show the extensions in a compact way if the genes are included because there can be multiple genes with the same extension.  Would we need to show the genes in the same way on the reference/publication pages too?  eg. http://pombase2.aska.gen.nz/reference/PMID%3A19357077

**Comment by ValWood** [comment]
No its fine as is.
