### ISSUE TITLE
inconsistent expression entry for deletions

### ISSUE THREAD

**Issue by mah11** [pombase/website#154]
On the genotype pages for some deletion alleles the expression has "Null", whereas for other deletions there's nothing under expression. Example: compare 'n contrast http://pombase2.bioinformatics.nz/genotype/PomBase-genotype-2769 , http://pombase2.bioinformatics.nz/genotype/PomBase-genotype-13943 and http://pombase2.bioinformatics.nz/genotype/48ef5d49bc0230cb-genotype-6 (all cdc13delta, so they should also be lumped per #153).

I think we'd like "Null" to appear. I'm sure we want the appearance to be consistent for all deletion allele entries (and the same whether they're single allele or or part of multi-allele genotypes).

**Comment by kimrutherford** [comment]
This is a Chado problem.  The deletions from the contig files were missing the "Null".  I've fixed that now so one of your examples is fixed now.

The 48ef5d49bc0230cb-genotype-6 is still missing the Null.  I'm trying to track that down.

Fixing these errors will make merging identical alleles work better (#577).

**Comment by kimrutherford** [comment]
I've looked at this again and decided to fix it a different way.  I've changed the loader to consistently not store an expression for deletions since we can infer the "Null".  I've changed the display code to consistently show "Null" for deletions.  The changes will come through in Tuesday night's load and be visible on Wednesday.  I'll close this issue then if it all looks OK.

**Comment by ValWood** [comment]
Looks good.
closing.
