### ISSUE TITLE
redirect fission-yeast-go-slim-terms to fission-yeast-bp-go-slim-terms

### ISSUE THREAD

**Issue by mah11** [pombase/website#1542]
I think we talked about this in a recent chat but I'm not sure it made it into a ticket, so ...

Now that we have 3 GO slims, it would be nice to change the BP slim page file name from `fission-yeast-go-slim-terms.md` to `fission-yeast-bp-go-slim-terms.md`. It'll be easy enough to do the renaming and updating existing links in one go, but we've used the https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms in a bunch of publications, and I bet some external sites use it, so it can't become a dead end.

@kimrutherford I'm happy to do the rename & edit parts if you want to hand this back to me when a redirect is working.

**Comment by kimrutherford** [comment]
I've renamed fission-yeast-go-slim-terms.md to fission-yeast-bp-go-slim-terms.md in Git and set up an alias so that links to https://www.pombase.org/browse-curation/fission-yeast-go-slim-terms will still work.

I've added this as a configurable thing in case we ever need to rename other pages:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L21-L23

> @kimrutherford I'm happy to do the rename & edit parts if you want to hand this back to me when a redirect is working.

Thanks.  I haven't changed any of the internal links yet to point to the new path yet.  Could you have a look at that?  It's not urgent as the current links work because of the alias.

**Comment by mah11** [comment]
> I've renamed

thanks :)

> I've added this as a configurable thing

how cool is that!!

> I haven't changed any of the internal links yet to point to the new path yet. Could you have a look at that?

Sure, no problem. I'll do it today - there's some other documentation work to do, and I could use some numpty stuff after yesterday's FYPO tour-de-force.

**Comment by kimrutherford** [comment]
> Sure, no problem

Cheers.  I'll update the link in the menu when I do #1527.

**Comment by mah11** [comment]
Thanks! I've got the other links done now, so I'll close this.
