### ISSUE TITLE
Order for process, component, function in website

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1545]
This bugs me more than it should.  :-)

We (but mostly me) are inconsistent about the order of the GO aspects in different parts of the site.  I'd like to make things consistent.  Which order should we pick?

In the "Genome status" menu and in the "Slim with" menu on the results pages I used the order MF, BP, CC.

But on the front page I used:
```
GO Overviews: Process ● Component ● Function
```

In the docs ([here](https://www.pombase.org/documentation/pombase-go-slim-documentation) and [here](https://www.pombase.org/datasets)) we have: BP, MF, CC

**Comment by mah11** [comment]
The only reason I put process first in the docs is because it's been around so much longer than the other two ... I thought people might have got used to seeing it made prominent. I don't really have a strong preference, though; maybe just a slight inclination not to plunk CC in the middle.

If you & Val prefer anything other than BP, MF, CC, I'll happily edit the docs to match.

**Comment by ValWood** [comment]
OK, let's go MF, BP, CC
because  
a) that's  probably a more logical order
b) follows the order on the gene page
c) let's confuse our users and shake them up a  little bit ;)

**Comment by kimrutherford** [comment]
I've changed the front page and it will be live in 10-ish minutes.

**Comment by kimrutherford** [comment]
Thanks Midori.
