### ISSUE TITLE
page won't load

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1558]
https://www.pombase.org/genotype/mad3~30%25-hphNT1_cassette_in_promoter-other-expression-knockdown

**Comment by ValWood** [comment]
also
https://www.pombase.org/genotype/mad1~500%25-nmt1_promoter-other-expression-overexpression

is it because of background? Im trying to find a background example

**Comment by mah11** [comment]
I bet it's the tilde in the allele description

Try [cdc10-129](https://www.pombase.org/genotype/cdc10-129-T429A-amino_acid_mutation-expression-not_assayed) to see backgrounds (big page, loads fine, backgrounds visible in detailed view).

**Comment by mah11** [comment]
annotations from PMID:24161933, all visible on the [publication page](https://www.pombase.org/reference/PMID:24161933), but some of the genotype pages linked from it don't load.

There's a suspiciously perfect correlation between allele desciptions with tildes and whether the genotype pages load or not -- with tildes, get "There has been a server error while loading this page. Please try reloading or go to the main page."; without tildes, loads fine.

**Comment by kimrutherford** [comment]
Looks like it's the percent signs that triggers the bug.  I'll fix that.

**Comment by kimrutherford** [comment]
I've fixed things, although in a slightly hacky way.  All the links on the publication page now work because the "%" is replaced with "_" everywhere: https://www.pombase.org/reference/PMID:24161933

I couldn't track down where the problem with "%" in allele name is causing the failure.  But because it's an uncommon character and we have a hacky fix I don't think it's worth spending a lot of time on.
