### ISSUE TITLE
Versions page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1573]
https://www.pombase.org/internal-details

can we remove
disease_associated: 03:08:2017 11:53
from this list now we use MONDO?

 - PSI-MOD looks like it was not updated since 2014 but you updated recently
 - Also SO features 2012?

Some of them I don't understand :)

**Comment by mah11** [comment]
> Also SO features 2012?

No, that's SO_feature_*relations*, our internal CV of ... well, one relation (promoter_of) that can hold between a SO feature and a gene. See https://curation.pombase.org/pombe/view/object/cv/SO_feature_relations?model=chado

**Comment by mah11** [comment]
I saved the email thread about this page from a few months ago -- Kim said he might "make it a bit more presentable", so I'll wait for him before I link & document it.

Suggestion: sort case-insensitive, which will push PSI_MOD and SO_feature_relations down so they don't steal as much attention from GO BP & CC.

Also, I think we can omit 

> uberon: fypo/releases/2020-06-30/fypo-simple-pombase.obo 

because we don't use Uberon directly.

**Comment by kimrutherford** [comment]
I made this page thinking it would for internal use.  Apart from the GO and FYPO versions I don't think it's useful to anyone outside PomBase?

> can we remove
> disease_associated: 03:08:2017 11:53
> from this list now we use MONDO?

Yep, those terms aren't used anymore so we can stop loading pombe-embl/mini-ontologies/disease_associated.obo
I've removed it from the load.  That change will be visible on Saturday.

> PSI-MOD looks like it was not updated since 2014 but you updated recently

Yep, I updated in May.  The date in that OBO file is: 30:05:2014 00:48.
Since then the datestamp has been fixed: https://github.com/HUPO-PSI/psi-mod-CV/commit/c9af7a6cb28f3d192b75afcbae7d9e86d631632b
Should I update again?

> Also, I think we can omit
>   uberon: fypo/releases/2020-06-30/fypo-simple-pombase.obo
> because we don't use Uberon directly.

Currently the page is a list of the namespaces of all terms loaded from all OBO files, which is why it's so messy.  Uberon appears in the FYPO OBO file so it appears in Chado.

**Comment by ValWood** [comment]
Maybe you are right. I wondered if people  might ever want to report versions of the ontology use. That is unlikely because they will mainly be using lists (and they can cite the date they used PomBase for Versioning)

**Comment by mah11** [comment]
I"m not that fussed about whether we try to attract more attention to this page - I agree that it's mainly of interest to us. I can slip a subtle link to it into the existing PomBase data version blurb and leave it at that.

**Comment by mah11** [comment]
the subtle link got done somewhere along the line, and there doesn't seem to be a huge need to do more for now, so I'll close this
