### ISSUE TITLE
Molecular function GO section

### ISSUE THREAD

**Issue by ValWood** [pombase/website#159]
Whilst thinking about summarizing,  it struck me that the GO MF section would look much better if we always grouped the "binding"  branch functions together a the bottom.

This would group the real activities more naturally.

So for example cdc2

![can binding terms always go to the bottom](https://cloud.githubusercontent.com/assets/7359272/22853146/45bdd990-f046-11e6-8404-eab2893b924b.jpg)

would have the display order:

cyclin dependent protein kinase activity
cyclin dependent protein serine threonine  kinase activity
protein kinase activity
protein serine/threonine kinase activity
ATP binding
Protein binding

**Comment by kimrutherford** [comment]
Currently it's alphabetical order.  Do you just need all the terms under GO:0005488 (binding) to be at the end with the rest in alphabetical order?

I had wondered about ordering the terms by have specific they are - putting the terms with the shortest path to root at the top of the list.  Is there a better order we can use?

**Comment by ValWood** [comment]
yes please, it would be better because it would make the actual function terms more prominent, and  group the less important binding terms together.

**Comment by ValWood** [comment]
> I had wondered about ordering the terms by have specific they are - putting the terms with the shortest path to root at the top of the list. Is there a better order we can use?

Can we think about that later?
I think its a good idea for function...but looking it will not affect many ....
If we have different functions, often it is because the protein is multifunctional, and the functions are in different branches.

For process alphabetical is definitely better, because they are usually in different branches. At least with alphabetical it is clear how we ordered them.
I'll open a ticket for later because I think  we would need to think about this

**Comment by ValWood** [comment]
I  think here that for now punting the binding terms to the bottom of the list so they are not the first thing you see is fine. More can come later if we decide to...

**Comment by kimrutherford** [comment]
On the last Skype call we decided  to put the binding terms at the bottom after a small gap.

I've made some changes that move things in the that direction but it's not done yet.  I've released a change that groups the binding terms at the bottom.  But currently the binding and non-binding terms each have their own "Show details ..." link.  They are treated as two separate sections in the code.

It's currently implemented in the same way as the population vs cell sub-sections for the phenotype annotations because that was easy.

Next I'll fix things so there is just one "Show details ..." at the top.  I'm releasing before that's done so you can have a look at the MF section to make sure you're happy with grouping binding terms separately.

**Comment by ValWood** [comment]
I like it like this. Its much better than jumping from catalytic activity to binding....and nice to have catalytic activity always first

**Comment by kimrutherford** [comment]
> I like it like this. 

Is it OK having the "Show details ..." on both sections?

**Comment by ValWood** [comment]
I think so, unless we think of any better way...

**Comment by ValWood** [comment]
- [ ]  Have only one "show details" at the top

**Comment by ValWood** [comment]
residual:
https://github.com/pombase/website/issues/440
