### ISSUE TITLE
Advanced search results. Sort alphabetically

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1631]
How easy would this be to implement?
It would be  a nice option as I see lots of named queries in categories. Alphabetical sorting would allow them to be grouped easily.

**Comment by kimrutherford** [comment]
Sorting the queries won't be difficult.  Would you like the list to always be alphabetical, or just as as option?

**Comment by ValWood** [comment]
just as an option.
Many people will want them to remain in the order that they do them.

**Comment by kimrutherford** [comment]
The history table can now be sorted by query name if you click on "Query history" in the header.  Let me know if you'd like any tweaks.  The icon changes when you click.  Currently the sort order switches back to the default when you make a new query.  That's so that the most recent query appears at the top of the table.

![sort-column-1](https://user-images.githubusercontent.com/90474/100082302-f3889800-2eac-11eb-94b1-71c6a857d3c0.png)
![sort-column-2](https://user-images.githubusercontent.com/90474/100082715-7578c100-2ead-11eb-9a9c-72c671a83cca.png)

**Comment by kimrutherford** [comment]
I meant to say, it won't be live for 10 minutes or so.

**Comment by ValWood** [comment]
works for me!

**Comment by kimrutherford** [comment]
> works for me!

OK, thanks.
