### ISSUE TITLE
community curation totals

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1646]
The number of community curation was ~12,000 until recently it's now 23,000

Year	Publications curated	Annotations
All	Curator	Community	Curator	Community 
Totals: | 3930 | 3061 | 869 | 58350 | 23930

I suspect all of the numbers have somehow doubled?
Or maybe our additions are added to the community curation?

**Comment by kimrutherford** [comment]
> Or maybe our additions are added to the community curation?

I dug into this and that's partly true.  The code for generating these numbers needs improving as it relies on the curator name attached to the annotations to decide which are admin and which are community.  There were about 7700 annotations where the curator name was "Val Wood", "midori" or "antonia".  The code only looks for "Valerie Wood", "Midori Harris" and "Antonia Lock" because the names that Canto has for you in the main database: https://curation.pombase.org/pombe/view/list/person?model=track

I think this might happen if you enter a session and don't put those exact names in when it asks for the curator details.  I plan to re-write this code at some point to make it more sensible.  But for now that's a problem to watch out for.

I've fixed the annotations that have "Val Wood", "midori" or "antonia" as the curator name so the counts are now:

. | All | Curator | Community | Curator | Community
-- | -- | -- | -- | -- | --
Totals: | 3934 | 3061 | 873 | 66092 | 16482

**Comment by ValWood** [comment]
Great, that makes sense...
