### ISSUE TITLE
put disease slim in https misc directory

### ISSUE THREAD

**Issue by mah11** [pombase/website#1669]
Hi Kim,

Could you arrange to write the disease slim file (disease_ontology_slim_ids_and_names.tsv) to the https://www.pombase.org/data/releases/latest/misc/ directory? It's the only slim that isn't in there, and it's therefore now the only link that I haven't been able to update from ftp to https.

cheers!

**Comment by kimrutherford** [comment]
Thanks for the documentation updates.  I can't find any emails or issues about disease_ontology_slim_ids_and_names.tsv and it's not a generated file.  The contents don't like very useful so perhaps we could delete it?

**Comment by mah11** [comment]
Um, it's the disease slim, so no, I don't think we're going to delete it. It's the terms and IDs, analogous to the files that get generated for the GO slims.

But I'd forgotten that it's not parsed out of an ontology file like the GO slims; we maintain it in pombe-embl svn (i.e. Val does). So we could copy it into the ftp portion of svn instead of putting it with the generated ones in yada/latest/misc and I think I could do that.

**Comment by mah11** [comment]
done

**Comment by ValWood** [comment]
Hmm, where does this file live. I haven't edited the slim since Antonia created it (at least I don't think I have?)
The one I see in supporting files still has DO identifiers???

**Comment by kimrutherford** [comment]
The disease slim terms are configured in the website config file: https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L4914

The TSV file is probably not up to date.

**Comment by kimrutherford** [comment]
> The TSV file is probably not up to date.

It also has DO IDs instead of MONDO IDs.

> Could you arrange to write the disease slim file (disease_ontology_slim_ids_and_names.tsv) to the https://www.pombase.org/data/releases/latest/misc/ directory?

There is MONDO slim file generated in that directory but with a different name:
  https://www.pombase.org/data/releases/latest/misc/pombe_mondo_slim_ids_and_names.tsv

I've added that file to SVN (`ftp_site/pombe/documents/pombe_mondo_slim_ids_and_names.tsv`) and changed nightly script to update it automatically.  If you move or rename it please let me know so I can change the nightly script.  Or tweak the script here:
  https://github.com/pombase/pombase-legacy/blob/master/etc/load-all.sh#L746

I haven't deleted `disease_ontology_slim_ids_and_names.tsv`.  It can probably be archived.

**Comment by mah11** [comment]
OK, cool - I can update the links to point to the MONDO slim in whichever location ... since the GO slims are in releases/latest/slim/ I can just use that one for the disease slim too.

**Comment by ValWood** [comment]
> I haven't deleted disease_ontology_slim_ids_and_names.tsv. It can probably be archived.

I just read this, but I already deleted it.  I don't think we need to explicitly  'archive' it, but could retrieve if necessary.
