### ISSUE TITLE
HGNC links broken

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1675]
Links to HGNC are failing even when gene name is correct.

see
https://www.pombase.org/gene/SPBP35G2.06c
https://www.genenames.org/data/gene-symbol-report/#!/error/
Symbol report error
The transition errored
Neither correctly formatted 'id' nor a 'symbol' parameter was provided when calling /cgi-bin/gene/symbol-report?id=NUP133.
If this error persists please email hgnc@genenames.org with the error displayed above.

(Maybe HGNC changed something? I will ask)

**Comment by mah11** [comment]
It looks like we're generating urls with this pattern: 
`http://www.genenames.org/cgi-bin/gene_symbol_report?match=[id]`

whereas this is what works (and is in the [GO xrefs yaml file](https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml)):
`https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:[id]`

**Comment by ValWood** [comment]
Very weird becasue they were working yesterday!

**Comment by KrisGray** [comment]
Hi. A few years ago, we rebuilt our website and changed the URLs to the gene symbol reports. I did place temporary redirects from the old URL format to the new URL, which Midori correctly stated above. I have made some changes recently, but I am surprised that the change has broken the redirect. I will look into the redirect next week; however, the links within PomBase should be changed to the correct URLs using the HGNC ID. Using the ID is much safer as it does not change, while the approved symbol could, in theory. Before the lockdowns, we talked about finally removing the redirects and announced that this would happen, but due to COVID and lockdowns etc., we left them in place for a little longer, but we shall remove them soon when things have settled down again.

**Comment by ValWood** [comment]
Thanks Kristian!

**Comment by kimrutherford** [comment]
> It looks like we're generating urls with this pattern:
> http://www.genenames.org/cgi-bin/gene_symbol_report?match=[id]

I copied the URL from this issue: https://github.com/pombase/website/issues/407

> however, the links within PomBase should be changed to the correct URLs using the HGNC ID.

Thanks for your help Kristian. I've changed PomBase to use the correct URL (from the GO xrefs file) so the links to HGNC are working again.
