### ISSUE TITLE
Link outs to RNA central

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1732]
We don't appear to have these, I was sure that we did!

@mah11   can you look into ? Presumably a config file update?

**Comment by kimrutherford** [comment]
I've had a quick look and it seems to be a database issue - the RNAcentral IDs aren't being stored correctly.  I'll debug and fix it in the morning.

**Comment by kimrutherford** [comment]
The problem was that the data file from RNAcentral used to look like this:
```
URS0000D656DF   POMBASE SPNCRNA.1708  4896    sRNA    SPNCRNA.1708
URS0000D656E3   POMBASE SPNCRNA.98    4896    sRNA    SPNCRNA.98
URS0000D656EA   POMBASE SPNCRNA.1710  4896    sRNA    SPNCRNA.1710
URS0000D656EB   POMBASE SPNCRNA.445   4896    snoRNA  SPNCRNA.445
```

but now looks like this:

```
URS0000D656DF   POMBASE SPNCRNA.1708.1  4896    sRNA    SPNCRNA.1708
URS0000D656E3   POMBASE SPNCRNA.98.1    4896    sRNA    SPNCRNA.98
URS0000D656EA   POMBASE SPNCRNA.1710.1  4896    sRNA    SPNCRNA.1710
URS0000D656EB   POMBASE SPNCRNA.445.1   4896    snoRNA  SPNCRNA.445
```

I assumed the column 3 was a gene ID column but it was actually a transcript ID column.  When RNAcentral changed the IDs by adding a ".1" the URS IDs got lost in the database - they were attached to the transcript features rather than the gene features.  It's fixed now by using column 6 instead.

The external links should be on the main site by the morning.

**Comment by ValWood** [comment]
Right! thanks for fixing so quickly.... (I rarely look at RNA pages!). I was looking at this for something to do with japonicus, but I can't remember what now...
