### ISSUE TITLE
Page has "Disease" in menu, but no "disease" section on page.

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1735]
Page has "Disease" in menu, but no "disease" section on page.

https://www.pombase.org/gene/SPBP4H10.13

**Comment by ValWood** [comment]
Also
https://www.pombase.org/gene/SPAC959.07

**Comment by ValWood** [comment]
Actually, the disease section disappeared....

**Comment by kimrutherford** [comment]
That's very strange because the slim looks OK: https://www.pombase.org/browse-curation/disease-slim

I'll dig into the problem.  Should I switch to the previous release in the meantime?

**Comment by ValWood** [comment]
I think we can live with it for a day or 2.... no need to switch back..

**Comment by kimrutherford** [comment]
I've fixed the problem and re-deployed the main site.  It was just a coincidence that the links to the disease sections broke.  All sections from orthologs onwards failed.

This happened because I added the japonicus orthologs to the Chado database.  This caused the web code to fail because the japonicus orthologs were available but not yet configured.  I've fixed the code to cope with this.

**Comment by kimrutherford** [comment]
I forgot to say, you'll need to shift-reload to see the fix.

**Comment by ValWood** [comment]
Thanks for the quick trouble shoot!
