### ISSUE TITLE
Add an extra annotation table column for transcript specific annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1797]
If there is transcript specific annotation, add an extra column ("Transcript ID") to the annotation table.  Don't show the extra column otherwise.

Follow on from:
  - https://github.com/pombase/website/issues/1613#issuecomment-853748060

**Comment by kimrutherford** [comment]
Also need to decide what to display in the column for annotation that isn't transcript specific.  It would be tidy to leave the field blank but maybe we should use "All" to make it very clear?

**Comment by mah11** [comment]
> maybe we should use "All" to make it very clear

I have no objection to this

**Comment by ValWood** [comment]
Fine by me, can be tweaked if necessary.

**Comment by kimrutherford** [comment]
This is done now.  It should be visible on the main site on Tuesday morning.

**Comment by kimrutherford** [comment]
> It should be visible on the main site on Tuesday morning.

I needed to re-release to update Spotlight images so the main site has these changes now.

The are quite a few annotations that are transcript specific ([fib1 has several](https://www.pombase.org/gene/SPBC2D10.10c)) so I'm a bit suspicious that there may be a code problem.  I thought there'd be just a few.  If you notice any that shouldn't transcript specific please let me know.

**Comment by kimrutherford** [comment]
> There are quite a few annotations that are transcript specific

Probably this is the main problem:
   - pombase/pombase-chado#876

**Comment by ValWood** [comment]
I'm not convinced that fib1 should be annotated with alternative transcripts (in the current schema we only annotate the canonical transcript unless there is any known phase or functional difference). There are long versions of most transcripts at low level (transcriptional readthrough). So I might collapse this one down when I get to chromosome 2 (will need to look at the data).

In the meantime could I have  up-to-date list of the genes with annotated alternative transcripts so that I don't miss any? All of the 5'UTRs in the current contig files will be deleted and the new ones I'm working on will be imported to replace them, so I need to make sure I have everything correct in my version.

**Comment by kimrutherford** [comment]
> In the meantime could I have up-to-date list of the genes with annotated alternative transcripts so that I don't miss any?

I haven't forgotten this.  I'm waiting for a complete Chado load with the transcript bug fixes.  Then I'll be able to query them from Chado.

**Comment by ValWood** [comment]
It would be useful to have these in a log file so that I can look them up whenever and don't need to ask.

Should I open another ticket for this since this one  ios closed?

**Comment by kimrutherford** [comment]
Yep, a new issue is a good idea.
