### ISSUE TITLE
PMID:34572495 2 small things

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1841]
1.

I accidentally used my google account so this shows as community curated, could you merge again (sorry)

https://www.pombase.org/reference/PMID:34572495

2. This page does not show the single annotation from this paper (a TAS made in the legacy file),
 although it does show up on the gene page.

https://www.pombase.org/gene/SPCC126.12

(I put the session through Canto expecting that would make the annotation connect directly to the publication)

**Comment by kimrutherford** [comment]
Is it the MF NOT annotation?  The NOT might be causing weird behavior.

**Comment by kimrutherford** [comment]
The NOT annotation doesn't appear on the term page either (https://www.pombase.org/term/GO:0003933).

**Comment by ValWood** [comment]
Yes I wondered if that was the case.
There is only a single NOT annotation from this paper. It is quite important because for years it has been considered to be a "[GTP cyclohydrolase](https://www.pombase.org/term/GO:0003933)"
but it definitely isn't.

but this will take a long time to purge:
http://www.ebi.ac.uk/interpro/entry/InterPro/IPR002678/
it is *everywhere*

**Comment by kimrutherford** [comment]
Some publication pages have NOT annotations: https://www.pombase.org/reference/PMID:8188690

so I wonder if PMID:34572495 is a problem because it has only NOT annotations.

I'll dig into that.

**Comment by kimrutherford** [comment]
> so I wonder if PMID:34572495 is a problem because it has only NOT annotations.
> I'll dig into that.

Turns out that there was a simpler explanation - the PubMed ID had a space after the colon so was treated as a different publication in Chado.  Whoops.

This took me an embarrassing length of time to work out.  :-)

The GAF file has "PMID: 34572495" instead of "PMID:34572495" so the annotation ended up here: https://www.pombase.org/reference/PMID:%2034572495

I've just fixed the loading code to remove any spaces after the colon so the annotation should be on the PMID:34572495 page on Wednesday.

**Comment by kimrutherford** [comment]
> I accidentally used my google account so this shows as community curated, could you merge again (sorry)

Done!

**Comment by kimrutherford** [comment]
> The NOT annotation doesn't appear on the term page either (https://www.pombase.org/term/GO:0003933).

That seems to be on purpose: https://github.com/pombase/website/issues/307#issue-225922584

Since that issue, we've changed how NOT annotations are displayed to make it much more obvious:
![not-annotation-1](https://user-images.githubusercontent.com/90474/155080636-76e37736-c047-49e1-90e0-169ac792c6f6.png)
(That's an example of how https://www.pombase.org/term/GO:0006399 would look if the NOT annotations were added back)

So maybe it would be OK to have NOT annotations on the term pages again?

**Comment by ValWood** [comment]
oops, my fault.  Good to fix those as there were possibly others, since  PubMeds have a space be default for some bizarre reason.

**Comment by ValWood** [comment]
> So maybe it would be OK to have NOT annotations on the term pages again?
yes, why not. I think this will be helpful. As long as they don't get into the query builder, counts etc.

**Comment by kimrutherford** [comment]
> As long as they don't get into the query builder, counts etc.

Good point.  I'll make sure they aren't changed.

**Comment by kimrutherford** [comment]
> I've just fixed the loading code to remove any spaces after the colon so the annotation should be on the PMID:34572495 page on Wednesday.

Looking OK now:

https://www.pombase.org/reference/PMID:34572495

> So maybe it would be OK to have NOT annotations on the term pages again?

That's still in progress.

**Comment by kimrutherford** [comment]
> So maybe it would be OK to have NOT annotations on the term pages again?

That's done for Monday night's load.  I'll check the site on Tuesday morning and close the issue.

**Comment by kimrutherford** [comment]
>> So maybe it would be OK to have NOT annotations on the term pages again?
>
> That's done for Monday night's load. I'll check the site on Tuesday morning and close the issue.

All good now: https://www.pombase.org/term/GO:0003933
