### ISSUE TITLE
Link from gene structure warnings to page describing the changes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1846]
<img width="918" alt="____ticket gene-structure eupdated link" src="https://user-images.githubusercontent.com/7359272/155746510-724f12f2-5477-4d5c-95ad-db7e49452c93.png">

It would be useful if these warnings linked through to this page:
https://www.pombase.org/status/gene-coordinate-changes.

Maybe we can do this by creating and adding a DB-xref.

**Comment by kimrutherford** [comment]
Since all the gene structure updates will link to the same page I think we can do this in the configuration rather than with a db-xref.  Where should the link go on the gene page?  Should "gene structure updated" be a link to that gene coordinate changes page, instead of where it goes at the moment?  Or would an extra link be better?

**Comment by ValWood** [comment]
Maybe the linked list
https://www.pombase.org/term/PBO:0000070
is useful.

So I guess an additional link will be better.

One of my next tasks is make this batch of changes in the contigs, and add the warnings.
I'm not sure if I will begin that this week as I have a few higher priority tasks to do first.

**Comment by ValWood** [comment]
We no longer need to do this because Manus has now documented all the changes in the history section.

However, I think we should position the history section on the page directly below the warning (or move the warnings to above the history). At present the sequence section is in between.

**Comment by kimrutherford** [comment]
I think this can be closed?
