### ISSUE TITLE
"with" field for IBA has disappeared

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1855]
<img width="919" alt="Screenshot 2022-03-15 at 15 11 53" src="https://user-images.githubusercontent.com/7359272/158418901-785f58dc-9ea8-4431-9185-9bc318a5c52f.png">

**Comment by kimrutherford** [comment]
We've lost lots of with/froms because they are separated by pipes:
  https://curation.pombase.org/dumps/builds/pombase-build-2022-03-14/logs/log.2022-03-14-21-06-10.gaf-load-output

Previously we were treating the pipes as commas because I didn't know better.  But I presume we don't want to make separate annotations for each of with/from values in that case?

I've reverted the change for now so it doesn't reject the pipes and tonight's load will be back to normal.

I'm going to revert pombase.org too an older version too, probably Friday's so the IBA withs come back.

**Comment by ValWood** [comment]
OK we can chat about this next week. It got a bit complicated!

**Comment by kimrutherford** [comment]
> OK we can chat about this next week. It got a bit complicated!

Yep!  :-)

For now I've allowed the pipes again so the IBAs have a with field.

**Comment by ValWood** [comment]
Action:
i) ban the pipe "|" separator for the "from" field with evidence code "IC" (should always be comma separator)
ii) If there is a "|" in the "with" field (e.g. for PAINT annotation) do not treat as independent annotations,  retain as a single annotation (this is slightly different from norma, c.f annotation extensions, where the meaning is *Really* critical)

**Comment by kimrutherford** [comment]
I checked the GOA GAF before the load started and there are no IC annotations with a pipe in the from field.  So I think we won't see any warnings once I change the code (unless there other GAF files with a problem).

**Comment by kimrutherford** [comment]
I've changed the code to warn about pipes in IC from fields.
