### ISSUE TITLE
No PMIDs in Literature section of gene pages

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1880]
We don't show the PMIDs on gene pages unless you hover over the "details..." link.  Maybe we should add them in case a user uses control-f to search the page?

**Comment by ValWood** [comment]
I guess , but users would need to know to "show all" annotation on the page do control F. (we don't want to show them by default, because this would drastically affect our display collapsing), we would then often have multiple rows for the same term.

I think we decided to go by author date instead of PMID because our core uses will more likely recognise papers in this way. We could switch to 
"author (PMID)" instead of "author (date)",  but the caveat above still applies. At least  users would then be able to search by PMID in uncollapsed page sections, but it would not make the rows so much longer.

I was thinking if this might help in any way
https://github.com/pombase/website/issues/929
but I don't think it can because there is no way to direct a user to a precise point on the page.

I don't have any other ideas....

**Comment by kimrutherford** [comment]
HI Val.

I was talking about the Literature section.  This is the sort of change I was thinking of:

![lit-pmid-1](https://user-images.githubusercontent.com/90474/168418646-f5cc6b61-5a0a-4c52-8cdb-8da33953c9ba.png)

**Comment by kimrutherford** [comment]
Here's a slightly different style:

![lit-pmid-2](https://user-images.githubusercontent.com/90474/168418844-fbea4fcf-421c-4ff0-be70-87595793daa3.png)

**Comment by ValWood** [comment]
Right, OK yes that would be useful!  Slight preference for the second, I think but not hugely.
Would it be better in the publication details line rather than the title line? I guess it would be a bit more 'hidden" if you are scanning.

**Comment by kimrutherford** [comment]
> Would it be better in the publication details line rather than the title line?

I think that makes sense.

How about this?  I've added a bit of spacing between the authors and citation and between the citation and the PMID.

![lit-pmid-3](https://user-images.githubusercontent.com/90474/168421057-f20c4d61-7f1b-4ee5-a8c8-383f298a1e56.png)

**Comment by ValWood** [comment]
yep!
