### ISSUE TITLE
show homologous diploid on the same page as the  haploid alleles

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1882]
i.e
https://www.pombase.org/genotype/rec12delta_rec12delta

phenotypes should be on the same page as
https://www.pombase.org/genotype/rec12delta

Forr the uses it makes more sense to see these all together (also, we have not been able to curate diploids for so long and so  many that should. be diploid are currently curated as haploid.

(We should crowdsource the fix for that, ask people to let us know which need converting to diploid!)

**Comment by kimrutherford** [comment]
How should the annotations be displayed?  I assume we can't just put them all in the same table.  Will we need two tables and two headers?

Should we just put everything from the diploid page at the bottom of the haploid page?

In your example, the genotype of `rec12Δ` has the name `rec12-169::kanMX6`.  But that's not the name of the `rec12Δ/rec12Δ` genotype, is it?  Or in a lab would they talk about `diploid rec12-169::kanMX6` and `haploid rec12-169::kanMX6` rather than giving different names?

**Comment by ValWood** [comment]
I think we could put them all in the same table. Probably listing haploids first then diploids might be helpful. But I don't think that is totally necessary.

>In your example, the genotype of rec12Δ has the name rec12-169::kanMX6. But that's not the name of the rec12Δ/rec12Δ genotype, is it?

I don't know the history of this genotype, but  rec12-169::kanMX6 is a synonym 
I assume at some point the deletion was made by replacing the gene with kanMX6  and this version was called rec12-169. We want to keep one representation of the deletion alleles , even if created in different ways they should be phenotypically identical if the entire gene was deleted (remember we force the deletions to be called rec12Δ
in the Canto interface).

In the table  rec12-169::kanMX6 appears as a synonym, but it appears as "name" in the header. I think it should be synonym here too? 

> in a lab would they talk about diploid rec12-169::kanMX6 and haploid rec12-169::kanMX6 rather than giving different names?

Yes. They would just talk about these as being the same genotype (which they are) . If 2 wt strains were mated to make a diploid they would be wt haploid and wt diploid but they wouldn't be different genotypes. Does that make sense?

**Comment by ValWood** [comment]
There is a "short name" field that was  sometimes used before we had a synonym field. Perhaps that field is used somewhere for rec12-169::kanMX6
(this field has always confused me. We had quite a lot of discussion about  it historically)

https://github.com/pombase/canto/issues/2071
https://github.com/pombase/canto/issues/1321

**Comment by kimrutherford** [comment]
> I don't know the history of this genotype, but rec12-169::kanMX6 is a synonym

It is recorded as a genotype name and also an allele synonym in this session:
https://curation.pombase.org/pombe/curs/35aab4b08bf43fb8/genotype_manage/ro
(same for a bunch of the other alleles)

> this field has always confused me

What confuses you about it?

**Comment by kimrutherford** [comment]
> I think we could put them all in the same table.

We'll need to think about how to do that.  Currently we don't show the genotype description in the annotation tables on the genotype pages because it would be redundant.  So we wouldn't be able to see which annotations were halpoids and which were diploids if it was all the same table: 
https://www.pombase.org/genotype/dbl4delta_dbl4delta
https://www.pombase.org/genotype/dbl4delta

It's possible to add the genotype descriptions but we'd be back to having a lot of redundancy.

Any ideas?

> If 2 wt strains were mated to make a diploid they would be wt haploid and wt diploid but they wouldn't be different genotypes.

I'm not convinced.  :-)

A homozygous diploid has a different phenotype to a haploid.  Which seems like a case of different phenotypes for different genotypes?

**Comment by ValWood** [comment]
Well a diploid and an haploid will have different phenotypes but that doesn't; make the genome different. It's only the ploidy that is different.

I guess that is the distinction, but I am not a very good geneticist!

@manulera  thoughts. Is there a definition  that will convince kim ( or am I wrong?)

**Comment by ValWood** [comment]
ACtually that isn't the issue. We just want to say that homozygous diploid alleles are single-allele genotypes.
They might be different geno types, but they are still single allele genotypes

We just want to say
haploid cdc2 delta
and diploid cdc2delta/cdc2 delta
are single locus genotypes.

This is true, they are at the same locus on different chromosomes.

**Comment by ValWood** [comment]
>this field has always confused me

What confuses you about it?

We can discuss on a group call. I will add to the list.

**Comment by ValWood** [comment]
This list
https://www.pombase.org/term_genotypes/FYPO:0000151
in
https://github.com/pombase/website/issues/1904

makes me realise that we also want to see single locus heterozygous diploids displayed as 'single locus'  if one copy is WT.

**Comment by manulera** [comment]
Joining and replying to some of the comments:

rec12-169 is a highly unusual allele. Apparently they replaced the coding sequence of rec12 with not only the KanMX cassette, but also with 3XHA tags and 6 histidins. They even design a plasmid to do this allele, but they don't explain what for. In principle, it should be equivalent to a deletion, so it can be made a synonym for phenotype purposes, but it's not what you would expect to find in a deleted locus.

![Screenshot 2022-06-21 at 10 10 15](https://user-images.githubusercontent.com/22526102/174751701-dae6bbce-2640-4f5b-9575-7369360da263.png)

**Comment by manulera** [comment]
> This list
https://www.pombase.org/term_genotypes/FYPO:0000151
in
https://github.com/pombase/website/issues/1904

For this, is it necessary to mention `haploid` in the title? Maybe single locus phenotype is enough.

**Comment by manulera** [comment]
> Well a diploid and an haploid will have different phenotypes but that doesn't; make the genome different. It's only the ploidy that is different.

I think double deleted diploid is a different genotype from deleted haploid, specially in the context of phenotype annotations. There will typically be a reason to do the experiment in the diploid instead of the haploid. I guess most often to study some meiosis process inducing meiosis in diploids, but there might be other use case. 

Currently the Pombase pages are genotype pages, so I would say it makes sense they are like that. If we had allele pages however, then we could have what you are saying. Let's say rec12D. Then you would have several sections corresponding to genotypes that include that allele:

* rec12D alone
* rec12D / diploid
* rec12D multi-locus phenotype
* rec12D / diploid multi-locus phenotype

Not sure if this is something we would want to do, but I think it would capture the link between the haploid and diploid locus that you mention, and that I agree exists.

**Comment by ValWood** [comment]
We do have a plan for allele pages
https://github.com/pombase/website/issues/1294
Almost complete  bar a some upstream blocking tasks?

So most of this ticket is nonsense. Closing. Sorry about that Kim!
