### ISSUE TITLE
gene page GO annotation filtering not working correctly

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1885]
I think this is recent because I'm sure it has been working properly in the past:

If I filter on  protein kinase/mitotic M-phase  this is what I see:

<img width="1137" alt="Screenshot 2022-05-23 at 15 48 24" src="https://user-images.githubusercontent.com/7359272/169846849-6587f1ca-18fe-49c7-be64-14b6b2413975.png">

**Comment by ValWood** [comment]
But due to the hierarchy, these should be in the list also,

<img width="940" alt="Screenshot 2022-05-23 at 15 49 05" src="https://user-images.githubusercontent.com/7359272/169847232-8907086f-5812-443c-933c-f0941a37a8fe.png">

<img width="984" alt="Screenshot 2022-05-23 at 15 48 59" src="https://user-images.githubusercontent.com/7359272/169847339-228b9273-067f-491b-95bc-b8db125a7878.png">

**Comment by kimrutherford** [comment]
> But due to the hierarchy, these should be in the list also,

It's messing up in summary mode again.  I thought I'd fixed that.  I'll disable extension filters again in summary mode until I get a chance to look again.

It might all needed revisiting because the counts in summary mode mostly don't make sense after filtering.   The summary doesn't show any annotations, so we probably shouldn't be showing a count of annotations that are still visible.

> but there are 0 annotations visible not 8

That's the same bug I think.  If you "Show details..." you see all 8.

**Comment by kimrutherford** [comment]
Here's another example.  This is shown in the summary until I filter on "mitotic metaphase":

**directly inhibits** clp1 **involved in** negative regulation of exit from mitosis **during** mitotic metaphase

In this case it's not even a hierarchy problem because it's "mitotic metaphase" in the filter and in the summary line.

(This is from "cyclin-dependent protein serine/threonine kinase activity" on the cdc2 page)

**Comment by kimrutherford** [comment]
I'm having second thoughts about fixing this at all.  :-)

My concern is that we show text like "Showing 4 of 21 annotations" in summary mode when the phase filter is active.  But that doesn't make a lot of sense because the summary doesn't show annotations directly - it's just a summary.  This might need a bit of a rethink or at least a re-wording.

**Comment by ValWood** [comment]
We could just say
 "associations" or
"summarized associations" (clunky)
"gene to term associations"

**Comment by kimrutherford** [comment]
> My concern is that we show text like "Showing 4 of 21 annotations" in summary mode when the phase filter is active

Perhaps it should just say "Showing filtered terms" or "Showing filtered summary" rather than trying to put a number on it?

**Comment by ValWood** [comment]
I guess we could. I worry that people might forget they have applied a filter. Maybe if we do that we should be more explicit about the filter. We can discuss. I quite like the numbers (It neve occurred to me that they might be a bit misleading, but if we could word it better this might be OK)

NOTE at the moment the "phase filter" has disappeared .

**Comment by kimrutherford** [comment]
> NOTE at the moment the "phase filter" has disappeared .

I've disabled it in summary mode because it's not working: https://github.com/pombase/website/issues/1885#issuecomment-1135263257

**Comment by ValWood** [comment]
I forgot!

**Comment by ValWood** [comment]
Will the fix here also fix
https://github.com/pombase/website/issues/930?

**Comment by kimrutherford** [comment]
> Will the fix here also fix #930?

That's a separate (trickier) problem.

**Comment by ValWood** [comment]
I think we should close this. It is working fine in the detailed view,  and now these filters are only visible in the detailed  view. So I think we just say that this query requires detailed view (Maybe need to revise the documentation?)

**Comment by ValWood** [comment]
?
