### ISSUE TITLE
Scraping BioRxiv to increase Pombase citations

### ISSUE THREAD

**Issue by manulera** [pombase/website#1902]
Hi @kimrutherford. When talking with @ValWood Val the other day we said that to increase Pombase citations we could scrape BioRxiv like we do Pubmed for fission yeast publications. If the authors have not cited pombase, we could send them an email asking them if they would like to cite Pombase, we could even send them the sentence to include in their methods and the citation.

I had a look at the BioRxiv API and you can get the abstract title etc. but not the full text, like with the PMC api.

https://api.biorxiv.org/

If you point me to the code that does this for Pombase in PMC, I could give it a try myself.

Best,
Manu

**Comment by ValWood** [comment]
I think this would be excellent but if it isn't quick to do it can be on the back burner for the GDA application because they are only asking for  data up to 2021. If we get accreditation  in the first round it will not be so urgent. If we don't then we  probably do need to improve our citations (and we should do it anyway), but we can make it a priority at that point.

Going forwards it would be very useful to  do this, but I think we should work on a couple of other  bigger issues first (allele standardization and the  genome resubmission).

**Comment by ValWood** [comment]
ePMC says
We are unable to use bioRxiv's own full-text XML as it is cost-prohibitive and
they do not allow it to be re-used for re-rendering the full text elsewhere.

I will just make frequent requests to the community. I can monitor some as they now come through to Canto, and there aren't  so many.
