### ISSUE TITLE
Ability to jump between popualtion and cell phenotypes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1911]
It always bothers me a little that  if you are in the population phenotype section  of the gene page you might not  be aware that there is the ( probably more informative) cell phenotype section lurking underneath.

I just wondered whether it would be useful to have some sorry of "jump to" link at the top of each section to make it 
 a) more obvious  that the cell level phenotypes exist
and 
b) provide a quick way to get to them if there is an excessive number of population phenotypes

**Comment by ValWood** [comment]
sty1 and pap1 are good examples where this would.  be useful

**Comment by kimrutherford** [comment]
Would clickable sub-menu items solve the problem?:

![image](https://user-images.githubusercontent.com/90474/189258148-186db963-17c4-4318-9951-272f45916ab8.png)

If we do that, I think the menu items should only be visible when the phenotype section is visible because the menu is already too long.

Another option is to have "Jump to population phenotypes" and "Jump to cell phenotypes" links somewhere near the top of the phenotype annotation sections.

**Comment by ValWood** [comment]
Yes!

**Comment by kimrutherford** [comment]
I've had a first attempt at this.  We can change the behaviour once you've tried it out.

For now, the "Population phenotype" and "Cell phenotype" sub-menu items are initially hidden.  They appear if you click on "Single locus phenotype" or "Multi-locus phenotype".  They are hidden again if you click on a different nav bar item.

Let me know if that works for you.

**Comment by ValWood** [comment]
I think this is good.
