### ISSUE TITLE
bug in 'canned query' for viable genes

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1949]
includes
SPBC4.07c | rpt2 | 19S proteasome base subcomplex ATPase subunit Rpt2
SPCC576.10c | rpt3 | 19S proteasome base subcomplex ATPase subunit Rpt3
SPBP19A11.03c | mts4 | 19S proteasome regulatory subunit Rpn1/Mts4

which are inviable population.
Can you remind me how the query works?
v

**Comment by kimrutherford** [comment]
HI Val.

> Can you remind me how the query works?

You see what the query does with the `[details]` link in the query list.

But unfortunately, the query was mis-configured.  It's now:

     genes annotated with "viable vegetative cell population" (FYPO:0002060)
     [Null expression - single locus haploid genotypes] "

But it was saying "null" instead of "haploid".

It's defined here in the config file: https://github.com/pombase/pombase-config/blob/24d30c80af557dc0a451838a9cdac6deb5cb2b6e/website/pombase_v2_config.json#L4600-L4611

I've just added the `"ploidiness": "haploid"` to the config, which was missing.  I should have added that when we implemented the [haploid/diploid split](pombase/website#1328) last year.  The query has been wrong since then.  Sorry! 

The "Inviable deletions and disruptions" was giving incorrect results too (1513 instead of 1384 genes).

It's only these two pre-configured queries that were wrong as far as I can tell.  If you make a query for FYPO:0002060 with null expression manually it has been working fine.

**Comment by kimrutherford** [comment]
You'll need to delete the query from the history table and then re-run it to see the new results.

**Comment by ValWood** [comment]
Great, thanks. I might annunce this in case people have used the old query and have it in their history, because it won't auto update.

**Comment by ValWood** [comment]
What date was the haploid /diploid split?

**Comment by kimrutherford** [comment]
> What date was the haploid /diploid split?

It went live about April 26th 2021
