### ISSUE TITLE
Improve messy phenotype annotation sections

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#1964]
I think that the top part of the phenotype section is getting messy:

![image](https://user-images.githubusercontent.com/90474/203697042-119fd614-40ec-43d9-88d4-8c5cfadfaf38.png)

We can probably find another place for the "View all alleles of SPCC18.17c" link.

It's especially chaotic when the details are shown and a filter is active:

![image](https://user-images.githubusercontent.com/90474/203697795-0084a93b-3404-4d67-9926-dab4880d7c39.png)

Do you have any ideas for making it tidier?

The first change that I thought of is putting the two boxes side-by-side, but it looks a bit weird:

![image](https://user-images.githubusercontent.com/90474/203696956-64093b9b-538c-42b1-b077-bf67201d5813.png)

**Comment by ValWood** [comment]
I have an idea! 
I think we should remove the slim links panel from the phenotype pages. They aren't as useful as for GO (which define biological modules, and also are far fewer).  

I think the phenotype slim has slightly different applications and isn't so relevant on the gene pages (it isn't developed in the same way to define module with minimal overlap between each other) . These links are actually a bit annoying here because people may expect them to behave like filters. For GO, the filters and  the slim terms are the same. For phenotype they are different (because the slim and the filters have a slightly different purpose. 
There is also additional confusion because of the population/cell phenotype split. i have been meaning to mention this for a while.

So maybe we can use this panel / a similar panel for links more relevant to phenotypes?

**Comment by kimrutherford** [comment]
> I think we should remove the slim links panel from the phenotype pages.

Great, that will make things tidier.  I'll do that tomorrow.

**Comment by kimrutherford** [comment]
> I'll do that tomorrow.

I forgot that was just a config change.  It's done for the morning.

**Comment by kimrutherford** [comment]
How do you feel about making the viable/inviable box smaller?

So this:

![image](https://user-images.githubusercontent.com/90474/204186578-894ed82d-c4dc-47d7-b84d-3711674818db.png)

instead of:

![image](https://user-images.githubusercontent.com/90474/204187167-500b4120-c870-45e6-98ce-1424b6d51597.png)

**Comment by ValWood** [comment]
Yep, then other stuff can go alongside...

**Comment by kimrutherford** [comment]
> How do you feel about making the viable/inviable box smaller?

OK, that's done now.

**Comment by kimrutherford** [comment]
I think this can close until we come up with some more ideas.
