### ISSUE TITLE
Warning triangle text on ncRNA pages

### ISSUE THREAD

**Issue by ValWood** [pombase/website#1978]
Suggested text for a "warning triangle" associated with the ncRNA "genomic location" line of ncRNA features.

"As in most systems, fission yeast lncRNA most are cryptic, many may be non-functional. RNA-seq data have limitations for precise mapping of transcription start and termination site coordinates, hence features are currently approximate. Most lncRNAs in fission yeast are induced under perturbations or genetic conditions (most notably during late meiosis). Almost all lncRNAs are suppressed by 3 RNA-processing pathways: the nuclear exosome, cytoplasmic exonuclease, and RNAi. For more details on the relevance of  a specific RNA please follow the link to the source(s) (adjacent)."

Quite long

@bahler can you improve this so that we day the same with less text?

**Comment by bahler** [comment]
Revised text:

"Many lncRNAs are cryptic and the functions (if any) are mostly unknown. RNA-seq cannot precisely map transcription start and termination sites, hence features are currently approximate. Most lncRNAs in fission yeast are induced in certain conditions, like non-dividing cells and meiotic differentiation. In proliferating cells, most lncRNAs are suppressed by RNA-processing pathways. For more details on the relevance of a specific RNA please follow the link to the source(s) (adjacent)."

Best,
-Jürg

From: Val Wood ***@***.***>
Sent: 13 December 2022 11:57
To: pombase/website ***@***.***>
Cc: Bahler, Jurg ***@***.***>; Mention ***@***.***>
Subject: [pombase/website] waring triangle text on ncRNA pages (Issue #1978)


⚠ Caution: External sender


Suggested text for a "warning triangle" associated with the ncRNA "genomic location" line of ncRNA features.

"As in most systems, fission yeast lncRNA most are cryptic, many may be non-functional. RNA-seq data have limitations for precise mapping of transcription start and termination site coordinates, hence features are currently approximate. Most lncRNAs in fission yeast are induced under perturbations or genetic conditions (most notably during late meiosis). Almost all lncRNAs are suppressed by 3 RNA-processing pathways: the nuclear exosome, cytoplasmic exonuclease, and RNAi. For more details on the relevance of a specific RNA please follow the link to the source(s) (adjacent)."

Quite long

@bahler<https://github.com/bahler> can you improve this so that we day the same with less text?

**Comment by ValWood** [comment]
Perfect, thanks. Kim can you implement when you are back.
Thanks
Val

**Comment by kimrutherford** [comment]
Hi Val.  Where should the warning icon be placed?  Before the "Source ..."?

![image](https://user-images.githubusercontent.com/90474/211741227-7e3f250c-0b0a-407e-9681-53704749470e.png)

**Comment by kimrutherford** [comment]
The text only mentions lncRNAs so should the warning icon only appear on lncRNA gene pages?

**Comment by ValWood** [comment]
Yes try that please..

**Comment by kimrutherford** [comment]
> on lncRNA and sncRNA (all currently ncRNA are lncRNA)

Sorry, I'm still a confused.  We have features of type sncRNA, lncRNA and ncRNA in Chado and on the website.  Should this warning appear on the ncRNA pages or just the sncRNA and lncRNA pages?

**Comment by ValWood** [comment]
All sncRNA and lncRNA

**Comment by kimrutherford** [comment]
How's this?  I'm mousing-over the icon but I couldn't capture the mouse pointer in the screenshot.

![image](https://user-images.githubusercontent.com/90474/212842065-bc6e4f80-5a2a-4330-9a19-e9e12a6bb202.png)

**Comment by ValWood** [comment]
Looks good. I wonder if we should add to the final sentence. 
"You can also inspect individual datasets in JBrowse."

**Comment by kimrutherford** [comment]
This change is on the main site now.
