### ISSUE TITLE
How to summarize ontology term view page for modifications

### ISSUE THREAD

**Issue by ValWood** [pombase/website#200]
We need to think about this....
when main redundancy removed

**Comment by ValWood** [comment]
So this:
http://pombase2.aska.gen.nz/term/MOD%3A00046

Should we go straight to this page for modification data??
http://pombase2.aska.gen.nz/term_genes/MOD%3A00046

since we don't show extensions
(I can't get "show details to work...)

**Comment by mah11** [comment]
"Show details" works eventually, but it takes ages (and slows the rest of the browser down) because the list is so damn long for any of the phosphorylated residue terms.

So should the gene page link go to the MOD:nnn gene list instead? Normally I'd be leery of having different behavior for terms from different ontologies, but in this case I'm less sure precisely because the phospho-MOD annotation pages are so awkward.

**Comment by ValWood** [comment]
Hmm, and we only we such a small number of terms that the nesting isn't useful.

These links would then behave like the taxon list links....

**Comment by ValWood** [comment]
can discuss on next call just to be sure...

**Comment by ValWood** [comment]
This is just something we will have to live with....
