### ISSUE TITLE
reported structure, not displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2006]
https://www.pombase.org/reference/PMID:12018481

**Comment by ValWood** [comment]
Also
PMID:16138082 Structure
papers trisaged as "structure" should be treated as "curatable".
"Structure " is just a triage class to group these to curate.

**Comment by kimrutherford** [comment]
> https://www.pombase.org/reference/PMID:12018481

The structures will be on the publication pages on the main site on Wednesday morning.  Currently they're only on the dev site.

> PMID:16138082 Structure
> papers trisaged as "structure" should be treated as "curatable".

I've changed the Canto config so that Structure papers are exported to Chado even if they aren't approved.  So all Structure papers from Canto will get a publication page on the main site on Thursday morning.

**Comment by ValWood** [comment]
ok!
