### ISSUE TITLE
versions page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2031]
https://www.pombase.org/internal-details

I might put a link to this page in the application.
However some things seem a bit inconsistent, or out of date.

For example:
PSI-MOD: 11:12:2020 15:38 time stamp is old (I guess this is because we use our mini version?)
SO_feature_relations: 13:07:2012 17:15

gene_ontology: fypo/releases/2023-03-08/fypo-simple-pombase.obo. ?  mixture of GO & FYPO?

iao: 13:08:2012 11:25 (what is this?)

**Comment by ValWood** [comment]
Maybe standards_versions would be a better name for the link?

I might put the link on the 'sue of standards section, it asks for a link)

**Comment by kimrutherford** [comment]
> PSI-MOD: 11:12:2020 15:38 time stamp is old (I guess this is because we use our mini version?)

We use the full PSI-MOD but we only update when we need a new modification.

> SO_feature_relations: 13:07:2012 17:15

That's this file, which hasn't been update since 2012: `pombe-embl/mini-ontologies/SO_feature_relations.obo`

> gene_ontology: fypo/releases/2023-03-08/fypo-simple-pombase.obo. ? mixture of GO & FYPO?

We get the gene_ontology namespace for the GO OBO file and from FYPO OBO file.  In the FYPO file it's from the `occurs_in` relation.  Probably we show it coming from FYPO is because we load the FYPO OBO file first.  I'll see if I can fix that.

Here's the relation from `fypo-simple-pombase.obo` that causes the problem:

```
[Typedef]
id: occurs_in
name: occurs in
namespace: external
namespace: gene_ontology
def: ...
```

> iao: 13:08:2012 11:25 (what is this?)

It's this file: `pombe-embl/mini-ontologies/mini-ontologies/iao.obo`
Midori's log message from 2012-08-13 is:
```
file to get IAO_0000412 loaded
```
I don't know what IAO:0000412 is except that it's used by FYPO.

**Comment by ValWood** [comment]
OK, good to know, I'll close this because nobody will dig this deep ;)
