### ISSUE TITLE
Download sequences in GenBank format 

### ISSUE THREAD

**Issue by manulera** [pombase/website#2033]
This would be a get request to the `/genome_region` entrypoint of the same api that checks the alleles, returns a gb file.

<img width="558" alt="Screenshot 2023-04-05 at 17 19 17" src="https://user-images.githubusercontent.com/22526102/230142473-d72ae11f-7ca3-47fb-bdf9-84b1b153e466.png">

**Comment by kimrutherford** [comment]
I've added a Docker service and added the necessary Apache configuration: 
https://curation.pombase.org/allele_qc/genome_region/?systematic_id=SPBC18H10.20c&upstream=0&downstream=0

**Comment by manulera** [comment]
Niceee!

PS: Isn't it very late there? 🦉

**Comment by kimrutherford** [comment]
> I've added a Docker service

We need to rebuild the container and then update the service nightly in case of changes.  I'll add those steps to the nightly load.

> PS: Isn't it very late there?

Yep, but I had a sleep in so it all evens out.

**Comment by kimrutherford** [comment]
Here's my prototype: https://desktop.kmr.nz/gene/SPCC18B5.11c

It's still a work in progress.

You'll need to go the Sequence section and click "Show nucleotide sequence":

![image](https://user-images.githubusercontent.com/90474/232987320-9bb0d0b8-5a89-4593-997b-ff793bf15b4d.png)

**Comment by kimrutherford** [comment]
> You'll need to go the Sequence section and click "Show nucleotide sequence":

I've just changed that.  If you don't click "Show nucleotide sequence" the button is now visible but you can't change the upstream/downstream bases in the downloaded GenBank.

**Comment by kimrutherford** [comment]
> This difference should be evident when you are downloading the sequence, so I wonder if something like this would work:

Good plan.  I'll work on that tomorrow.

**Comment by manulera** [comment]
Hi @kimrutherford I also fixed a problem (it did not properly handled multi-transcripts). I also added some very basic tests (`python -m unittest test_apy.py` to run)

https://github.com/pombase/allele_qc/commit/704f31f71fabe74c63ba07baf1a258f2328caa39

To run the test I had to add an extra dependency, so you would have to run `poetry install` in your local copy of the repository if you want to run them.

**Comment by kimrutherford** [comment]
I added a "Download as EMBL" button and I've deployed the code to pombase.org.  There are probably things that need fixing but I think it's already useful.

Thanks Manu!

It even works with genes with two transcripts.  Here's [SPAC22A12.08c.1.embl](https://curation.pombase.org/allele_qc/genome_region?systematic_id=SPAC22A12.08c&format=embl&upstream=1000&downstream=1000) from the [SPAC22A12.08c page](https://www.pombase.org/gene/SPAC22A12.08c) in Artemis:

![image](https://user-images.githubusercontent.com/90474/233245550-b9d92981-49a7-40cc-a054-1a5be96373d2.png)

Although one day it would be good to change `/genome_region` to accept a transcript ID rather than a gene ID.  Then we could allow the user to select which transcript they'd like in the GenBank/EMBL file:

![image](https://user-images.githubusercontent.com/90474/233245987-b564fd50-8f88-4d56-a413-2ae05645c79a.png)

**Comment by kimrutherford** [comment]
> This difference should be evident when you are downloading the sequence, so I wonder if something like this would work:

Done!  The change is available on the main site.

![image](https://user-images.githubusercontent.com/90474/233258083-79391cfb-4de9-4ebd-810f-2baedc63a3d7.png)



For JaponicusDB, I've left it as a single FASTA download button.

**Comment by manulera** [comment]
Fantastic. I will announce in the mailing list. I would have loved this one when I was working with pombe myself.

**Comment by manulera** [comment]
Added some docs with https://github.com/pombase/website/commit/493b16d61c4ab6bdd19babe7b2de3b3932c11ab8
