### ISSUE TITLE
links to PRO give an error

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2035]
I spotted
https://proconsortium.org/app/entry/PR:000060258/
link from
https://www.pombase.org/gene/SPAC3G9.09c

<img width="374" alt="Screenshot 2023-04-11 at 14 34 10" src="https://user-images.githubusercontent.com/7359272/231179759-800afc26-06a2-4042-8c07-2d82b5d05641.png">

These links work, so I wonder if this is the URL format we should be using?

https://proconsortium.org/cgi-bin/entry_pro?id=PR:000060258

cc @nataled

**Comment by nataled** [comment]
The correct link should always be a PRO PURL: http://purl.obolibrary.org/obo/PR_000060258

The first link @ValWood indicated, https://proconsortium.org/app/entry/PR:000060258/, will work only when the indicated term is part of the full release and part of the downloadable PRO file (this term is not). The second PRO link indicated will work either way, but that's the old form (kept going for now to ensure backward compatibility for those that haven't transitioned to using the PURL). The PURL works either way.

PR:000005792 works because it is in the latest release.
