### ISSUE TITLE
Part_of  should display as involved_in

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2037]
Part_of should display as involved_in
Here it is a mixture.  https://www.pombase.org/term/GO:0140713

Can you see  why?

**Comment by kimrutherford** [comment]
Here is the configuration:

```json
        {
            "rel_name": "part_of",
            "if_descendant_of": "GO:0003824",
            "display_name": "involved in"
        },
        {
            "rel_name": "part_of",
            "if_descendant_of": "GO:0098772",
            "display_name": "involved in"
        }
```

ATP-dependent histone chaperone activity (GO:0140674) is covered by this configuration (`"if_descendant_of": "GO:0003824"` - "catalytic activity") so `part_of` displays as `involved in`.

H2A-H2B histone complex chaperone activity (GO:0000511) is not covered by the config because it's not a descendant of GO:0003824 or GO:0098772.

Should `part_of` display as `involved in` for all descendants of "histone chaperone activity" (GO:0140713)?

**Comment by ValWood** [comment]
yes please, we can go up to all descendants of
GO:0140104  molecular carrier activity

**Comment by kimrutherford** [comment]
> yes please, we can go up to all descendants of
> GO:0140104 molecular carrier activity

I've committed that fix for Monday night's load.

**Comment by kimrutherford** [comment]
> Here it is a mixture. https://www.pombase.org/term/GO:0140713

It's better now.

**Comment by ValWood** [comment]
I notice here: (taf11)
part of link displays as part_of rather than involved in
https://www.pombase.org/gene/SPAC1002.04c

 GO:0140223   [ JSON](https://www.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0140223/complete)
general transcription initiation factor activity
should be added to the list displayed as "ionvolved_in"

In fact, I don't know  what the exceptions would be to MF -BP links displyed as part of?

**Comment by kimrutherford** [comment]
I've change the config for GO:0140223 part_of.  It will be visible on Friday morning.
