### ISSUE TITLE
Show assigned_by and date for annotations?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2092]
Hi @ValWood

After we had trouble working out why the ASTRA complex annotations were still in JaponicusDB, I wondered if it would help to show the annotation assigned_by and date fields in the evidence popup.

Is that a good idea?

![image](https://github.com/pombase/website/assets/90474/67b5623e-4f0a-497f-8869-f012a77251f1)

**Comment by ValWood** [comment]
1. I think it's a good idea to show the assigned by on the pop up mouse over. We should really show the source and GBC are checking for that. It will definitely make it easer to  imemdiately trace annotations too. I never worried so much becasue we load such a small amount of external EXP data.

2. I don't think we need to load Complex Portal data if we already have the annotation from the same paper with any evidence code. Here we have made a different judgment call. I consider this a direct assay for the complex. So it we can filter all the complex  portal IP if there is an IDA that will remove the duplication. If we do that, we will  load very few (if any) Complex portal annotation because I think we have curated all publications with complexes. This use of IPI without with has been brought up at GO  (I actually didn't think we loaded them).
3. I have another plan to make the source of the japonicus annotations a bit clearer...will open a ticket.

**Comment by kimrutherford** [comment]
> I think it's a good idea to show the assigned by on the pop up mouse over. 

That's done now if you reload.

**Comment by ValWood** [comment]
Great!

**Comment by kimrutherford** [comment]
I think this is done now.
