### ISSUE TITLE
line wrapping

### ISSUE THREAD

**Issue by ValWood** [pombase/website#211]
unnecessary line wrapping on a hyphen here ;)

![line wrapping](https://cloud.githubusercontent.com/assets/7359272/23918980/e876b8e6-08ec-11e7-9c29-2f823faebb44.jpg)

**Comment by kimrutherford** [comment]
Which page was that?

**Comment by ValWood** [comment]
ark1.

**Comment by kimrutherford** [comment]
Thanks.  I'm not sure what the best thing to do here is.  The wrapping is happening because I thought the display looked better if the extensions were vertically aligned.  To do that it's using an HTML table.

But because in this case there is a long extension further down the table (see screenshot), that is making the genotype column get squashed.  One possibility is to just not allow wrapping of the genotype identifiers.  I'll try that but I'm worried that it won't look good for very long genotype identifiers.

![screenshot at 2017-03-15 19-28-39](https://cloud.githubusercontent.com/assets/90474/23936260/dd464512-09b5-11e7-8a51-487dbb04c36b.png)

**Comment by ValWood** [comment]
ok its not a problem then. I thought it was just deciding to wrap on the hyphen.

We can do some cleverer stuff later to shorten some of the genotype displays  with mouse over. It would require us to devise some rules (if this, display this etc)
For this particular one, if known the change would be more informative becasue everypne looking at kinases will know "as" is an anlog sensitive mutant.

For e.g.  as2 is ark1-as2(L166A)
