### ISSUE TITLE
fasta search link on gene pages no longer works

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2140]
...because EBI have changes to some sort of dispatcher system, the sequence is no longer posted.

**Comment by kimrutherford** [comment]
That's annoying!  I had a look and can't see an obvious fix.

**Comment by ValWood** [comment]
The propably removed the ability to submit a sequence via the web now they have this new queing system.
we can just remove it. I'm probab ly the only person who uses Fasta, and   unless there are a lot of new proteins it isn't going to help ortholog detection.

**Comment by kimrutherford** [comment]
> The propably removed the ability to submit a sequence via the web now they have this new queing system.
we can just remove it.

I've remove it.  It will be gone in the morning.

**Comment by kimrutherford** [comment]
Hi Val.  I think you mentioned on the call that you're using the fasta search more at the moment.  Should I tried to get the Fasta search button working again?

**Comment by kimrutherford** [comment]
I've contacted EBI support to ask if there is a supported way to link to the Job Dispatcher system with the sequence and tool preset.

Meanwhile:
 - pombase/website#2291

**Comment by ValWood** [comment]
brilliant

**Comment by kimrutherford** [comment]
I've had a reply from the EBI and been able to put the FASTA button back on the gene pages.  It works for me in Chrome but not in Firefox.  That seems like an EBI bug because I'm having trouble using the Job Dispatcher at all with Firefox.  I'm going to put in a support request about that.

Could you try the button in Safari too when you get a chance?

**Comment by PCarme** [comment]
It works in Safari as well.

Pascal
________________________________
De : Kim Rutherford ***@***.***>
Envoyé : vendredi 6 décembre 2024 10:25
À : pombase/website ***@***.***>
Cc : Subscribed ***@***.***>
Objet : Re: [pombase/website] fasta search link on gene pages no longer works (Issue #2140)


⚠ Caution: External sender


I've had a reply from the EBI and been able to put the FASTA button back on the gene pages. It works for me in Chrome but not in Firefox. That seems like an EBI bug because I'm having trouble using the Job Dispatcher at all with Firefox. I'm going to put in a support request about that.

Could you try the button in Safari too when you get a chance?

**Comment by kimrutherford** [comment]
> It works in Safari as well.

Thanks for checking!

I've noticed that even in Chrome it doesn't always work perfectly.  The FASTA button only works it you have been to the EBI Job Dispatcher website in the past and have clicked "I agree, dismiss this banner" for the "This website requires cookies, ..." message.  If you haven't done that the sequence doesn't get filled in.

I'll report that to the EBI too.

**Comment by kimrutherford** [comment]
> I'll report that to the EBI too.

I've done that now.

**Comment by kimrutherford** [comment]
> I've noticed that even in Chrome it doesn't always work perfectly. The FASTA button only works it you have been to the EBI Job Dispatcher website in the past and have clicked "I agree, dismiss this banner" for the "This website requires cookies, ..." message. If you haven't done that the sequence doesn't get filled in.

It seems to be an unexplainable temporary problem.  The EBI couldn't reproduce the issue and it's now working for me.

So the FASTA button works fine now.

**Comment by kimrutherford** [comment]
Now I know the correct way to link to the Job Dispatcher, it's easy to add links to other tools.

Is there anything else that could be useful?: https://www.ebi.ac.uk/jdispatcher/

**Comment by kimrutherford** [comment]
> Is there anything else that could be useful?

New issue:
  - pombase/website#2302
