### ISSUE TITLE
Show promoters from Canto/Chado

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#2160]
These are now in Chado so we need to decide where and how to show:
  - Promoter swap
  - Exogenous gene promoter

Follows on from:
  - pombase/pombase-chado#1087

See also:
  - pombase/canto#2544

**Comment by kimrutherford** [comment]
It would be quick to display them in the same way as Canto while we think about it:

![image](https://github.com/pombase/website/assets/90474/85f3ed42-58e3-495a-be74-cf27b3f79e65)

**Comment by ValWood** [comment]
I don't think we  need to see them in the allele name/description, but we should see them in the pop-up:

<img width="772" alt="Screenshot 2024-03-19 at 08 50 41" src="https://github.com/pombase/website/assets/7359272/28dd14fc-5792-472f-a49f-b82e24f782db">

The rationale is that this info is usually "supplementary" sometimes it is curated, and sometimes not in any given case (especially for knockdown).

We should treat it the same as "background", so 
any  cdc2+ ox (ie. any promoter), is represented as a single genotype page

Because many overexpression will not have the promoter mentioned if we don't group them, we will have separate pages for OX with "nmt41" and "unspecified"

I wonder if we do something like:

https://www.pombase.org/genotype/cdc2-Y15F-Y15F-amino_acid_mutation-expression-not_assayed_or_wild_type

Gene | Product | Allele name | Synonyms | Description | Type | Expression
-- | -- | -- | -- | -- | -- | --
cdc2 | cyclin-dependent protein kinase Cdk1/Cdc2 | cdc2-Y15F | cdc2-F15cdc2-YF15 | Y15F aa | amino_acid_mutation | Not assayed or wild type

Gene	Product	Allele name	Synonyms	Description	Type	Expression
[cdc2](https://www.pombase.org/gene/SPBC11B10.09)	cyclin-dependent protein kinase Cdk1/Cdc2	cdc2-Y15F	
[cdc2-F15](https://www.pombase.org/reference/PMID:9398669)
[cdc2-YF15](https://www.pombase.org/reference/PMID:9398669)
Y15F aa	amino_acid_mutation	Not assayed or wild type

But in the  Expression column list the promoters,
Then add a promoter column to the table below when it is known?


Thoughts @PCarme @manulera ?

**Comment by kimrutherford** [comment]
> Then add a promoter column to the table below when it is known?

Which table below do you mean here?

**Comment by ValWood** [comment]
Ah sorry I was going to put another screenshot in. I mean the annotation table below the genotype table in;
https://www.pombase.org/genotype/cdc2-Y15F-Y15F-amino_acid_mutation-expression-not_assayed_or_wild_type

(in the full view, not the details view)

**Comment by kimrutherford** [comment]
I don't think that will work well for multi-locus genotypes.  And if it's a separate column, isn't it going to be the same value(s) in every row?

Can we add a "Promoter" column in the table at the top of the genotype page?  It might work better for multi-locus genotypes.

![image](https://github.com/pombase/website/assets/90474/a23a503a-e1ea-4107-8494-2a17b3b5e07d)

**Comment by ValWood** [comment]
good point, we can discuss on Friday

**Comment by kimrutherford** [comment]
The code for displaying the promoters is mostly ready to go, however we decide to do it.  In my prototype I added an extra column, but that's easy to change.

![image](https://github.com/pombase/website/assets/90474/c353bb27-4aa1-45f0-aa87-4b5b2c594a60)

(https://desktop.kmr.nz/genotype/cut1%2B%28wild_type%29-expression-overexpression__mad2delta)

![image](https://github.com/pombase/website/assets/90474/f32ae093-ed61-4270-aec2-9e9db88c6486)

(https://desktop.kmr.nz/genotype/mad2%2B%28wild_type%29-expression-knockdown__slp1%2B%28wild_type%29-expression-overexpression)

**Comment by kimrutherford** [comment]
Replaced by: pombase/website#2161
