### ISSUE TITLE
reciprocal 'target_of" annotation missing

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2167]
This *might* be a configuration issue, but on the sep1 page we have these targets:

<img width="1023" alt="Screenshot 2024-04-18 at 10 18 17" src="https://github.com/pombase/website/assets/7359272/6c910778-be80-403c-8acf-31a47668826d">

but they don't appear on the  'target of' list of the targets?

**Comment by kimrutherford** [comment]
Could you add a link to the page where you took the screen shot?

**Comment by ValWood** [comment]
Apologies it was sep1
https://www.pombase.org/gene/SPBC4C3.12

**Comment by kimrutherford** [comment]
I had a look.  There is no configuration for that term or its MF ancestors.
It only has 3 MF ancestors: 
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000981

On the [term page](https://www.pombase.org/term/GO:0000981) GO:0000981 has a descendent term with configuration: GO:0001228
but that's because GO:0001228 has a different parent with configuration: GO:0001216

We can fix this by adding configuration for has_input for GO:0000981, GO:0003700 or GO:0140110.  Let me know what's best and I'll add it.

**Comment by ValWood** [comment]
If I understood the question
https://www.ebi.ac.uk/QuickGO/GTerm?id=GO:0000981
should be "regulates transcription of"

**Comment by kimrutherford** [comment]
What should we have in the target of table?  "transcription regulated by"?

**Comment by ValWood** [comment]
>What should we have in the target of table? "transcription regulated by"?

yes!

**Comment by kimrutherford** [comment]
OK, I've added that configuration.
