### ISSUE TITLE
why does PMID:22267499 appear on ppa3 gene page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2178]
from https://github.com/pombase/curation/issues/3439

PMID:22267499
Is it in the PubMed Keywords?

I think we discussed at some point , but I can't find a ticket, that  for curated papers we could ignore the PubMed  gene list and only put on the pages which the gene has an annotation. This would  also prevent the linking of papers for the wrong gene via synonyms etc.

**Comment by kimrutherford** [comment]
> Is it in the PubMed Keywords?

I checked.  There are no genes from PubMed keywords for PMID:22267499.

The problem is this case is a an unwanted side effect of trying to keep things simple.  (ie. a bug)

The Literature list on the gene pages shows all the publications referenced by anything on the gene page.  That mostly works well but in this case it's including a publication it shouldn't.

The `ppa2Δ` allele has a synonym `ppa2-delta` from Canto session for PMID:22267499 (291d614ef0c90bc4):
https://www.pombase.org/allele/SPBC16H5.07c:allele-1

`ppa2Δ` is part of a genotype on the ppa3 page.  The publications that ppa2 references (including synonym refs) are pulled in and are shown in the Literature section.

I'll fix that!

The genotype pages have the same problem: 
https://www.pombase.org/genotype/ppa2delta_ppa2delta
PMID:22267499 shouldn't be in the Literature section because `ppa2Δ/ppa2Δ` isn't mentioned in PMID:22267499 and isn't on the publication page.

I'll fix that too.

**Comment by kimrutherford** [comment]
That's all fixed but needs a nightly load.  I'll check pombase.org on Tuesday morning.

There are other examples like PMID:2544292 in the ppa3 page Literature section that shouldn't be there.  It's the same bug: PMID:2544292 is from an allele synonym (`bws1Δ` synonym of `dis2Δ`)

**Comment by kimrutherford** [comment]
> That's all fixed but needs a nightly load. I'll check pombase.org on Tuesday morning.

The load didn't work last night so I'll check tomorrow.

**Comment by kimrutherford** [comment]
Fixed!
