### ISSUE TITLE
cant locate exact string of exact synomym on Advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2180]
Advanced search on phenotype not locating  exact matches.

from
https://github.com/pombase/fypo/issues/4405

I thought I had missed the synonym "branched mitochondria" but it is there?

  Even though its exact matching string of an exact string, it comes up pretty low in the Canto search:
<img width="772" alt="Screenshot 2024-05-20 at 08 02 05" src="https://github.com/pombase/website/assets/7359272/3509a506-e688-4581-95cf-0baf0c8f417e">

but on the website search it doesn't appear at all:

<img width="992" alt="Screenshot 2024-05-20 at 08 02 57" src="https://github.com/pombase/website/assets/7359272/ee90772a-30f0-4e0f-a972-df00a3252326">

**Comment by kimrutherford** [comment]
The words in the synonyms aren't weighted as highly as the words in the term name when searching.  It's a slightly delicate balance deciding but perhaps the term names are given too much weight.  Current matching words in exact and narrow synonyms are worth 0.3 compared to the same words in term names.

In your example you had an exact match for a synonym but at the moment there isn't any special handling for that.  An exact match doesn't give an extra boost.  I'll change things so that exact matches are weighted more highly.

**Comment by kimrutherford** [comment]
That worked, so "net-like mitochondrial morphology" (FYPO:0003807) is the top suggestion for "branched mitochondria".  It's possible that synonyms are now weighted too highly.  Could you keep an eye out for other problems?

For Canto I think there's a different problem.  Canto uses a different and older implementation of Lucene.  I changed the weightings for exact synonyms for Canto too so that "branched mitochondria" synonym is now second in the list.  Lucene is mysterious sometimes but I think "branched septum" still comes first because it's short and "branched" is in the name and is a synonym.

I have a plan one day to switch Canto over to use the pombase.org term autocomplete API so that Canto and the website always give the same results.  Could you let me know if you think the pombase.org term complete is giving good enough results that we could make that switch?

Canto now:

![canto-complete](https://github.com/pombase/website/assets/90474/df95c577-7e65-4d8c-89d8-bf52860de4e5)

**Comment by ValWood** [comment]
We'll keep an eye on it

CC @Pcarme

**Comment by kimrutherford** [comment]
OK, thanks.  I'll close this now but please make new issues if you spot anything weird.

**Comment by kimrutherford** [comment]
This is a problem again after these changes:
 - pombase/website#2285

**Comment by kimrutherford** [comment]
Fixed!  Let me know if you see any other problems.
