### ISSUE TITLE
add preprints to publication list

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2186]
preprints
https://www.medrxiv.org/content/10.1101/2022.04.13.22273750v3
https://arxiv.org/abs/2312.10904

**Comment by kimrutherford** [comment]
Do these have PMIDs?

**Comment by ValWood** [comment]
No but we already have a preprint section at the bottom of the list.
Maybe preprints should be integrated by date but clearly tagged as pre prints?
And perhaps we don't need to include  preprints once we have a PMID. What do you think?

**Comment by kimrutherford** [comment]
Ah, right.  I wasn't sure which publication list you meant.

So no problem.  I do that soon.

> Maybe preprints should be integrated by date but clearly tagged as pre prints?

Would it make sense to move the pre-print section to the top of the page since they are generally the most recent?

> And perhaps we don't need to include preprints once we have a PMID. What do you think?

Yep, I think about pre-prints as being a temporary thing.  Should I remove the 3 current pre-prints?

**Comment by ValWood** [comment]
Yes good plan. At the top of the page it shows what we are recently involved in. I agree they should be temporary. Although people think there should only be pre-prints!

**Comment by kimrutherford** [comment]
OK.  I'll:
  - move the pre-prints to the top
  - add the two new pre-prints
  - remove the current three

**Comment by kimrutherford** [comment]
Done
