### ISSUE TITLE
SGD names and descriptions updating?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2188]
Are we picking uop new SGD names and descriptions?

check out https://www.pombase.org/gene/SPBC8D2.16c

Saccharomyces cerevisiae | YGR283C | Putative methyltransferase more ... |  
Saccharomyces cerevisiae | YMR310C | Putative methyltransferase more ...

buit at SGD
https://www.yeastgenome.org/locus/S000003515
UPA1 & 2

**Comment by kimrutherford** [comment]
The SGD genes aren't updated automatically because I wasn't convinced that the script to query SGD InterMine would be reliable enough.  I've updated the data file now (for Monday morning) and added a note to the PomBase calendar to update it regularly in future.

https://github.com/pombase/pombase-chado/wiki/Updating-the-SGD-genes-file

**Comment by ValWood** [comment]
Is  updated so closing
