### ISSUE TITLE
Ability to sort slim results on gene column

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2246]
I wondered if this would be easy to do:

It would be nice to be able to rank these by number

<img width="630" alt="Screenshot 2024-09-28 at 12 56 01" src="https://github.com/user-attachments/assets/088f44db-a8d3-46d9-9a63-5726e9d9910a">

**Comment by kimrutherford** [comment]
> I wondered if this would be easy to do:

It's probably 2-3 hours work.

**Comment by ValWood** [comment]
OK, it would be good to do sometime....

**Comment by kimrutherford** [comment]
Which order should the rows be when you sort by gene count?  Largest count at top or bottom?

**Comment by kimrutherford** [comment]
> Which order should the rows be when you sort by gene count? Largest count at top or bottom?

I've implemented this with the smallest at the top for now - very easy to change.   Most other places where we sort by a column of numbers we use that order, like the literature section of gene pages and on the results pages for things like protein length.

There are two different types of slim pages.  There is the slim overview:
  - https://www.pombase.org/browse-curation/fission-yeast-bp-go-slim-terms

and the pages of slimmed gene results sets:
  - https://www.pombase.org/slim:mf_goslim_pombe/from/id/c57703f2-6762-40d7-bfa9-a67d150ec59f

The first case was very simple to implement, but the second case was slightly more involved.  If you see an bugs it will likely be in the second case.  Let me know if there are problems.

This will be on pombase.org in the morning.

The nightly update is running a little late because I broke things implementing [modification filtering](https://github.com/pombase/pombase-chado/issues/1223#issuecomment-2448707481) and had to restart.  It should be done by 8am UK.

Also available on my desktop: https://desktop.kmr.nz/browse-curation/fission-yeast-bp-go-slim-terms

**Comment by kimrutherford** [comment]
> This will be on pombase.org in the morning.

Now live:
https://dev.pombase.org/browse-curation/fission-yeast-bp-go-slim-terms

**Comment by ValWood** [comment]
> by gene count? Largest count at top 

please!

**Comment by ValWood** [comment]
Looks good! for both types of pages

**Comment by kimrutherford** [comment]
>> by gene count? Largest count at top 
>
> please!

Is it OK that that's inconsistent?

**Comment by ValWood** [comment]
inconsistent with what? The ones we are most interested in are the annotated bins. Otherwise I need to scroll to the bottom and read it backwards?

**Comment by kimrutherford** [comment]
> inconsistent with what? The ones we are most interested in are the annotated bins. Otherwise I need to scroll to the bottom and read it backwards?

See: https://github.com/pombase/website/issues/2246#issuecomment-2451249432

> I've implemented this with the smallest at the top for now - very easy to change. Most other places where we sort by a column of numbers we use that order, like the literature section of gene pages and on the results pages for things like protein length.

So I'm wondering if it's OK to be inconsistent?

**Comment by PCarme** [comment]
I think this "inconsistency" is OK since the ordering by gene count will serve different purposes:
- For the Literature section, you want the lowest gene counts at the top to see the papers that are specific to the gene you are looking at first, and all the high throughput assays "hidden" at the bottom of the list.
- For the slims, I think the idea is to see the terms that are the most annotated, so the "most interesting" first.

**Comment by ValWood** [comment]
Thanks for the explanation. I agree, they have different purposes so the inconsistency is OK

**Comment by kimrutherford** [comment]
OK, thanks.

I've re-released with the largest gene count at the top.
