### ISSUE TITLE
number discrepancy reporting phenotype totals

### ISSUE THREAD

**Issue by ValWood** [pombase/website#225]
This seems odd...

http://pombase2.aska.gen.nz/term_genotypes/FYPO%3A0000059 total  single allele genes 2150

but a query on
"abnormal mitotic cell cycle" on the live site gives 903?

It is not impossible that the live site is incorrect though,  I always thought the number was lower than I expected for all alleles, but then >2000 seems very high....

maybe you are still counting annotations, not genes, or it includes multigene too?

**Comment by mah11** [comment]
The 2150 is genotypes, as the URL indicates. 

The gene list page, http://pombase2.bioinformatics.nz/term_single_allele_genotype_genes/FYPO%3A0000059, has 892.

There is a problem here, but it's much smaller and simpler: both the gene count and the genotype count are labeled "single allele genotypes ...". Obviously the gene count should have "genes from single-allele genotypes ..."

(and "single-allele" should be hyphenated because the whole thing modifies "genotypes")

**Comment by kimrutherford** [comment]
> There is a problem here, but it's much smaller and simpler:

Thanks, I've improved the text.  Could you have a look and close the issue if it's OK?

**Comment by mah11** [comment]
Yep, that looks entirely sensible. Thanks :)
