### ISSUE TITLE
immature peptide region

### ISSUE THREAD

**Issue by ValWood** [pombase/website#2251]
complete this ticket.  reminder  (SO browsing issue)

<img width="1157" alt="ticket-SO browsing" src="https://github.com/user-attachments/assets/ad2e4aff-90e5-4f1b-9a44-89634db45a02">

**Comment by ValWood** [comment]
For SO browsing, ignore part_of (only display is_a)

**Comment by kimrutherford** [comment]
There was a bug is the way the transitive closure was stored in Chado.  The code was expecting `BFO:0000050` as the relation term ID, but was getting `part_of`.  The only other ontology that had this problem was PSI-MOD but that has very few part_of relations and none connecting modification terms used by us.

> For SO browsing, ignore part_of (only display is_a)

That fix probably isn't needed now but let me know what you think once the website is fixed on Thursday morning.

After fixing that the annotation appear on the immature peptide region page:

![image](https://github.com/user-attachments/assets/bdb7c890-a6a4-475c-a6b5-fb3ab7827b5a)

I'll check this on Thursday and close the issue.
