### ISSUE TITLE
static page content

### ISSUE THREAD

**Issue by ValWood** [pombase/website#239]
How do we want to maintain static content?
Config files for page text?

Can we discuss on next call.
I'll make tickets for anything where there is automated content.

**Comment by mah11** [comment]
changed summary because most non-gene pages are not static (e.g. publication pages, ontology term pages)

**Comment by ValWood** [comment]
text only pages

- documentation
- FAQ
- community curation blurb
- resource metrics page
-contents
-citing PomBase
-mailing list
-news feed
- events (dump this as news feed is sufficient)
-jobs (dump this as news feed mailing list is sufficient)
- internet resources

**Comment by ValWood** [comment]
Clone resources.
I had forgotten about this page.
There is no point having the sanger archives link. They lost them all years ago, and I doubt anybody need these.

The information about clone naming could go to an archive, or the FAQ?

The cosmid assembly data, people do still use, so there should be something int he FAQ about that.

Otherwise this menu item can go.

**Comment by ValWood** [comment]
Tools

Blast 
link can go.  We don't have the resources or the will to maintain a blast server. Plently of other things to use.

Motif search
Kim your old friend is following you around... We should be able to just copy this over?

Genome Browser.
In the first instance we will link to EG

**Comment by ValWood** [comment]
Find menu

This links to

Our searches
The GO slim
FYPO

This menu has always seemed a bit odd to me.

Maybe we should have a menu for "Resources"
GO slim
FYPO
Priority unstudied genes
Gene characterization status

**Comment by mah11** [comment]
> Maybe we should have a menu for "Resources"
> GO slim ...

The title is going to have to be a darn sight more specific than "Resources". Everything on, or linked from, the pombase web site is a "resource".

**Comment by ValWood** [comment]
1. Convert static pages to markdown in git hub directory
2. Configure links

**Comment by kimrutherford** [comment]
I've being doing some investigation into showing and editing static content in a simple way.  I just tried the easy implementation but found that it has a problem that I can't get around.

In the meantime I've created a directory to contain Markdown documentation:
  https://github.com/pombase/website/tree/master/frontend/src/docs

My plan is to have a sub-directory of docs for each of the documentation paths (so "about/", "help/", "community/" etc.)  I've created a "community" directory as an example.  So far I've just turned the http://www.pombase.org/community/fission-yeast-community-curation-project page into Markdown.  It looks like this in editable form:
  https://raw.githubusercontent.com/pombase/website/master/frontend/src/docs/community/fission-yeast-community-curation-project.md

GitHub renders Markdown into nice HTML by default:
  https://github.com/pombase/website/blob/master/frontend/src/docs/community/fission-yeast-community-curation-project.md

The "community" directory also contains a "menu.md" file containing the Markdown that should appear in the menu at the left.  And there's an "index.md" which contains the content you should see when you go to http://www.pombase.org/community/

Despite some problems, I've made the dodgy implementation of this live so we can get an idea of how it could work.  There's now a "Community docs" link on the right of the main page.

The reason I need to come up with a new implementation is that clicking the navigation links reloads the site.  For example the "Community curation" link in the menu on the left on this page: http://pombase2.bioinformatics.nz/community/fission-yeast-community-curation-project

I'll work on that.

**Comment by ValWood** [comment]
You are a wizard.

**Comment by kimrutherford** [comment]
I've improved things so that the docs pages now load instantly.

There are a few sample pages linked to from the "Docs" section of the main page:
  http://pombase2.bioinformatics.nz/

As described above, the docs are here:
  https://github.com/pombase/website/tree/master/frontend/src/docs

If you make changes, I'll need to re-release the site (for now, I hope to make that more automatic that at some point).  Let me know if you make changes.  It generally takes less than a minute to re-release.

The pages can be edited online via GitHub or locally.  GitHub renders the Markdown files as HTML so you can view them live(-ish).  Unfortunately it does a bad job on tables that don't have headers.  eg.
  https://github.com/pombase/website/blob/master/frontend/src/docs/about/index.md

If you have a table with a header it needs to be formatted like this:

    |some header | other header|
    |------------|-------------|
    |value 1     | value 2     |
    |some data   | other data  |

which renders as:

|some header | other header|
|-------|------|
|value 1      | value 2   |
|some data | other data|

The amount of whitespace doesn't matter and the numbers dashes doesn't either.  So that second like could be: "|-|-|"

You need as many sets of dashes as you have columns.  eg. "|-|-|-|" for a three column table.

If you don't have a header you still need the "|-|-|" for it to display properly on the web site.  I won't display properly on GitHub without a header though.

For the PomBase v2 pages the markdown files are being processed with Pandoc which has a very comprehensive implementation of Markdown:
  http://pandoc.org/MANUAL.html#pandocs-markdown

One helpful Markdown feature that we may need is the ability to stick arbitrary HTML in the file.  This might help with moving some of the more complicated pages across 

eg.

    # some header
    - some list item
    - other item

    <bold>
       BOLD text
    </bold>
    <img src="http://pombase2.bioinformatics.nz/assets/pombase-logo.png"/>

    # Some other header

renders as:

# some header
- some list item
- other item

**BOLD text**
<img src="http://pombase2.bioinformatics.nz/assets/pombase-logo.png"/>

# Some other text


---------------------------------------------

Pandoc has lots of options and features so I'm sure it will cope with most of our documentation needs.

One last note.  If you need to link to another page in PomBase v2, use path without the `http://pombase2.bioinformatics.nz/` bit.  eg. `[Mailing lists](community/mailing-lists)`

There are two examples in the menu.md for the community section:
  https://raw.githubusercontent.com/pombase/website/master/frontend/src/docs/community/menu.md

You can link to any page, including gene pages.  eg. `[cdc2 page](gene/SPCC1739.11c)`

------------------------------------------

Let's have a chat about what to do next on the next Skype call.

**Comment by kimrutherford** [comment]
I've summarised all that on the [wiki](../wiki/Documentation-with-Markdown).

**Comment by ValWood** [comment]
can probably close this and open tickets for remaining to do (some already exist)
