### ISSUE TITLE
evidence filtering

### ISSUE THREAD

**Issue by ValWood** [pombase/website#249]
question from kim

For evidence filtering, should the drop-down just have all possible evidence types (with those with no annotations greyed out)? Or should it just have the ones that are actually in the table?

Or would you like some higher level categories like the ones here?:
http://geneontology.org/page/guide-go-evidence-codes

Experimental Evidence
Computational Analysis Evidence
Author Statement Evidence
(etc.)

**Comment by ValWood** [comment]
Use the Canto subset

**Comment by kimrutherford** [comment]
Current Canto phenotype evidence codes:

 - Cell growth assay             
 - Chromatin immunoprecipitation experiment
 - Chromatography evidence
 - Co-immunoprecipitation experiment
 - Competitive growth assay evidence
 - Electrophoretic mobility shift assay data
 - Enzyme assay data
 - Epitope-tagged protein immunolocalization experiment data
 - Flow cytometry data
 - Gel electrophoresis evidence
 - Immunolocalization experiment data
 - Microscopy
 - Other
 - Particle size and count assay
 - Plasmid maintenance assay evidence
 - Quantitative PCR
 - Reporter gene assay
 - Substance quantification evidence
 - Transcript expression level evidence
 - Western blot assay

**Comment by ValWood** [comment]
We need a config file to map the more specific evidence codes from the PHAFs to the Canto set for the filtering.

**Comment by mah11** [comment]
Kim - have a look at the file I'm attaching. It's not quite complete because there are a couple of places where curators might have to decide on another entry for filtering (or if we should just map something fairly specific to "other"). But it might help sort out what should go in a config file.

[evidence_20170404.txt](https://github.com/pombase/website/files/906133/evidence_20170404.txt)

**Comment by kimrutherford** [comment]
Thanks.  I'll put that in config file and then we can tweak it.

**Comment by kimrutherford** [comment]
I've added an evidence filter.  It doesn't have all the evidence types in the menu yet but it seems to work. 

I've started documenting the filter configuration here:
  https://github.com/pombase/website/wiki/Config-file#filters

**Comment by ValWood** [comment]
I don't see the evidence filter after shift reload?

**Comment by mah11** [comment]
a) phenotype only;
b) did you click "show details"? no point filtering evidence in the summary view, which doesn't show evidence anyway.

it's working pretty well for me, except that the cell phenotype table doesn't seem to grey out unused evidence types (e.g. cdc2 single allele cell phenotypes list includes gel electrophoresis not in grey)

**Comment by mah11** [comment]
decision: don't lump co-immunoprecipitation into Western blot assay (or anything else); change configuration from my earlier suggestion

**Comment by mah11** [comment]
another config update: change "Other" (1144 uses in file) ECO mapping to ECO:0000314

**Comment by kimrutherford** [comment]
I've added all the other phenotype evidence codes (I think).

I've also fixed the filters so that if you select an evidence filter and a term filter at the same time it does something sensible.  Currently it gives you the intersection of the filters - annotations that match the term AND the evidence.

One currently bug is that if you filter by evidence, then go to the summary view it still shows the filtered list even though you can't see the evidence in the summary.  Let me know what you think should happen in that case.

**Comment by kimrutherford** [comment]
> it's working pretty well for me, except that the cell phenotype table doesn't seem to grey out unused evidence types

I changed the code a bit while fixing the case when you select two filters at once.  I now can't reproduce this bug.  I think I may have fixed it by accident.  Could you try it again to see if you still has issues for you?

**Comment by mah11** [comment]
It is indeed greying out unused codes as expected now. Hooray for accidental fixes.

There's just one thing I think could be improved: the evidence descriptions aren't all in alphabetical order, which threw me off. (The few that were in the dropdown before you added the rest are still grouped at the top instead of ordered with the rest.)

Options for returning to summary view are (a) remove the evidence filter, or (b) show only terms that match the active filter, but add a warning that filtering is on and happening and hiding some annotations. Not sure I've generated a strong preference so far ...

**Comment by kimrutherford** [comment]
> the evidence descriptions aren't all in alphabetical order

I've made them alphabetical.  Should we do the same for the term filter?

> add a warning that filtering is on

That might be good idea anyway to make it clear when some annotation is filtered.

**Comment by mah11** [comment]
> Should we [list items alphabetically] for the term filter?

that would make sense to me

**Comment by kimrutherford** [comment]
> > Should we [list items alphabetically] for the term filter?
>
>that would make sense to me

OK, I've done that.

**Comment by ValWood** [comment]
The evidence code filter is only present at the moemnt for cell level phenotypes (not for molecular or  population). You might be aware of that...

**Comment by ValWood** [comment]
ignore that... (summary view)

**Comment by ValWood** [comment]
Anything else to do here?

**Comment by kimrutherford** [comment]
I think the only thing was to show a warning when filtering is active.  I've made a separate issue for that: #271
