### ISSUE TITLE
publication page shows ortholog section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#256]
Oddly this publication page shows an ortholog section containing the pombe gene

http://pombase2.bioinformatics.nz/reference/PMID%3A25533340

haven't seen it on any other publication pages so far

**Comment by mah11** [comment]
That it appears at all is not a bug - that paper is the dbxref for those orthology annotations (most don't have dbxrefs at all, let alone PMIDs, but that's one of the exceptions).

It does look bug-ish that it shows two identical entries. I assume that's because the paper is cited for both human and S. cerevisiae orthologs of xlf1, but that's not at all obvious so we should decide what we do want to display.

Artemis for xlf1:

    FT                   /controlled_curation="term=human NHEJ1 ortholog;
    FT                   db_xref=PMID:25533340; date=20060627"
    
    FT                   /controlled_curation="term=orthologous to S. cerevisiae
    FT                   YLR265C; db_xref=PMID:25533340; date=19700101"

**Comment by mah11** [comment]
another actual bug: the pombe gene name hyperlink is borked

**Comment by Antonialock** [comment]
ah, I didn't realize. Then the dbxref doesn't show on the gene page....should it?

**Comment by mah11** [comment]
oh, yeah, it probably should ... I bet we never thought of it because so few orthologs have dbxrefs

**Comment by ValWood** [comment]
Yeah somewhere it is stuck in a curation tracker ticket  when I eventually  revise/finalise the ortholog table formats.  Because I hadn't yet done this step I hadn't bothered to open a jira ticket to display the xrefs, because the dbxrefs were not previously exported in the tables Mark used.

So, good to display correctly now since this can precede the table revisions...

**Comment by kimrutherford** [comment]
> Then the dbxref doesn't show on the gene page....should it?

It should but since most orthologs don't have a reference, maybe it would look odd to have a reference column that's mostly empty?

> another actual bug: the pombe gene name hyperlink is borked

Looks like it's showing the pombe part of the ortholog but not the gene in the other species and then getting confused while it does it.

We need to do something similar to what we do for interactions.  We need an extra column on the reference page that shows the pombe gene in the ortholog.  We don't need that on the gene pages because we know which gene it is.

**Comment by kimrutherford** [comment]
> another actual bug: the pombe gene name hyperlink is borked

Fixed.

> Then the dbxref doesn't show on the gene page

Fixed.

> It should but since most orthologs don't have a reference, maybe it would look odd to have a reference column that's mostly empty?

Actually quite a lot have a reference because of Compara.

**Comment by mah11** [comment]
another thing we could do is write a PB_REF for the ones that don't have a publication to cite
not urgent, and we'll open a curation ticket when we get round to it.

**Comment by ValWood** [comment]
> Actually quite a lot have a reference because of Compara.

Yeah that's a bit of a fudge. I didn't use Compara to make the call, but  rather than add all of the IDs manually we use Compara to grab the 1:1 IDs on the basis that these are pretty difficult to get wrong (....that said I have corrected a few).
