### ISSUE TITLE
Filter on conditions?

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#261]
#56 talks about condition querying.

Do we need to filter on conditions?

See also: #93 and #187

**Comment by ValWood** [comment]
Maybe not on the gene pages.
We'll have a think...Maybe  we only need to be able to do this in the query builder.

We need to think about how we do this, because we don't always curate conditions, only when they are important to the result. This means that filtering and searching may not always have the expected outcome, so we need to be able to make this clear...

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/56  pendign discussion
