### ISSUE TITLE
GO F-P link data

### ISSUE THREAD

**Issue by ValWood** [pombase/website#263]
GOC annotations from Function -process links...
Where do we get this data from? 

I have completely forgotten where this is documented.....

**Comment by ValWood** [comment]
@kimrutherford @mah11

**Comment by ValWood** [comment]
This is an old issue but it might be the location
https://github.com/pombase/pombase-chado/issues/126

**Comment by ValWood** [comment]
Thats a very old link...

I looked on the GO website documentation/FAQ and did a google search for
"gaf-inference" which was  in the old path but I still can't locate it.....

**Comment by kimrutherford** [comment]
Is this what you mean?:
  http://build.berkeleybop.org/view/GAF/job/gaf-check-pombase/lastSuccessfulBuild/artifact/gene_association.pombase.inf.gaf

**Comment by ValWood** [comment]
that' the one

**Comment by ValWood** [comment]
Chris recommends this location

https://github.com/pombase/website/issues/263#issuecomment-295110040

https://build.berkeleybop.org/job/go-gaf-release-snapshot/lastSuccessfulBuild/artifact/pipeline/target/groups/pombase/

**Comment by kimrutherford** [comment]
> Chris recommends this location

I can't see a .inf file there.  Which file do we need?

**Comment by ValWood** [comment]
seems to be
	pombase-gafcheck-prediction.gaf

I'm not sure what some of them are...

**Comment by kimrutherford** [comment]
That file is a bit odd.  It's identical to the other file (gene_association.pombase.inf.gaf) except that:
Column 9 ("Aspect") is always "C" or "F" and never "P".  The GAF spec says it should be the aspect of the ID in column 5.

Column 9 seems redundant since you can work out the Aspect from the ID.  But it makes me slightly suspicious that it's wrong here.

As an example, the term in the first annotation in both that file and the old gene_association.pombase.inf.gaf file is: GO:0006357 - regulation of transcription from RNA polymerase II promoter
The old file has "P" in column 9 and the new file has "C".

Is it worth reporting to Chris?

For us it's not a problem because we ignore the aspect column so I'll change the load script to use the new one instead.

**Comment by kimrutherford** [comment]
> I'll change the load script to use the new one instead

Done.

**Comment by ValWood** [comment]
Hi Chris, see Kim's comment above...looks like a problem?

@cmungall

**Comment by ValWood** [comment]
Yes that does seem odd.
v
