### ISSUE TITLE
publication pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#27]
We want PomBase to offer a web page for each pombe paper, kind of analogous to a gene page. 

Show the  basic information – 
- [x] title 
- [x] authors
- [x] citation details, abstract, etc. – as a typical PubMed page, 
- [x]  PubMED ID
- [ ]  Other IDs

Links to 
- [x] PubMed
- [ ] CitExplore
- [x] UKPMC etc. 

Some pombase-specific goodies 
- [x]  links to annotations made from the paper. 

We'll flesh out those details more when this becomes a high priority.

- [x] link to them (instead of any external site) in the 'source' column
- [x]  links and add links to the entries in the gene page Literature section.

- [x] Requires https://github.com/pombase/pombase-chado/issues/558  
- [x]  Requires https://github.com/pombase/pombase-chado/issues/559

**Comment by ValWood** [comment]
"Store the triage status of the publication in Chado so that the information can get through to Ensembl. This will allow us to put a note on a gene page that says which reviews the gene was mentioned in."

https://github.com/pombase/website/issues/27

we'll wrap handling reviews as part of this

**Comment by ValWood** [comment]
Other suggestions

- [ ]  Discuss, something about curation status (minimally whether curated, cummunity curated, or not)

**Comment by ValWood** [comment]
- [ ] Add link to PomBase publication pages from NCBI using LinkOut
 like this https://github.com/geneontology/amigo/issues/392

**Comment by ValWood** [comment]
As most of this ticket is done, I'm going to close it and open a new ticket for nn-urgent  future tasks.
Please check that I did not miss anything...

**Comment by ValWood** [comment]
new ticket
https://github.com/pombase/website/issues/160

**Comment by ValWood** [comment]
Outstanding from this ticket

@mah11  pleas open tickets if required

I'm not sure what citexplore is?
https://www.ebi.ac.uk/citexplore
Is this different from ePubMeD? What does it do? 

DO we need to show other IDs (DoI might be useful, especially if we plan to move to pre review 
curation long term)?


This part:
"Store the triage status of the publication in Chado so that the information can get through to Ensembl. This will allow us to put a note on a gene page that says which reviews the gene was mentioned in."

becomes obsolete  as a task. We will open tickets in future about how/what we want to display/classify by topic/attach to genes/ etc
pombe papers which we don't curate data from.

**Comment by mah11** [comment]
CitExplore is a literature search thingy at EBI. For us it's not essential, since our users tend towards PubMed anyway. I think it was only mentioned here because the summary was copied wholesale from Jira, where it was included as a political sop.

I agree, DOI would be good.
