### ISSUE TITLE
should multi-allele genotypes be alphabetical?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#270]
single allele are alphabelical but multi aren't
http://pombase2.aska.gen.nz/term/FYPO%3A0000085

**Comment by mah11** [comment]
That page only has one phenotype term showing.

**Comment by ValWood** [comment]
I'm refering to the alleles.

Look at the multi gene  phenotypes section

the seem to begin alphabetical, and then they go

   tdp1Δ slx8-29(unknown) top1+ ,   ufd1-1(P76S) tdp1Δ top1+ ,   hta1-S129A(S129A) hta2-S128A(S128A) ctp1Δ rad3Δ

I'm not sure if there is an order

**Comment by mah11** [comment]
corrected summary

**Comment by kimrutherford** [comment]
> the seem to begin alphabetical, and then they go

It's a hold over from Ancient Times (last week).

Until a few days ago we had all the genotypes in one big list and ordered by number of alleles then ordered alphabetically within those groups.  We have that so that the single allele genotypes came first in the detailed view and the order in the summary is the same as the order in the detailed view.

So "ufd1-1(P76S) tdp1Δ top1+" with three alleles comes before "hta1-S129A(S129A) hta2-S128A(S128A) ctp1Δ rad3Δ" with four alleles.

Now that we have a separate section for single allele genotypes perhaps we should just use alphabetical order for the multi-allele genotypes?

**Comment by ValWood** [comment]
makes sense

**Comment by kimrutherford** [comment]
> Now that we have a separate section for single allele genotypes perhaps we should just use
> alphabetical order for the multi-allele genotypes?

Done.  (You might need a shift-reload)
