### ISSUE TITLE
More help for "Slim terms"

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#278]
Currently the list of slim terms in the process section just says "Slim terms".  Think we need to help link there or change the "Slim terms" text to something more obvious for the users.

**Comment by kimrutherford** [comment]
I should look before typing.  It was "Slim Terms" in v2 and I've just changed it to match v1: "GO slim terms".  I still think it needs improving to make it more descriptive.

**Comment by kimrutherford** [comment]
I've added a help link that goes to this page: http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms

**Comment by ValWood** [comment]
> I still think it needs improving to make it more descriptive.

Maybe a mouse over with a  concise description of what a slim is. "broad overview of annotation distribution"

Perhaps "GO slim terms" should link to the slim page and 
an information link to 
http://www.pombase.org/documentation/pombase-go-slim-documentation

**Comment by kimrutherford** [comment]
Could we perhaps call it something like "Process overview"?  I don't think the word "slim" is helpful.

**Comment by ValWood** [comment]
Maybe
Biological process summary (GO slim)
@mah11 ?

**Comment by mah11** [comment]
I agree that "GO slim" by itself is too jargon-y to be much use. But I don't really have a strong preference between including it as in Val's suggestion or leaving it out.

I have maybe a slight preference for "overview" over "summary", because both PomBase and GO documentation use "overview" to explain what slims are used for.

So that yields either "Biological process overview" or "Biological process overview (GO slim)" ... take your pick. In any case, keeping the help link is good.

**Comment by ValWood** [comment]
yes I agree overview is better, I meant to come back and say that!

**Comment by kimrutherford** [comment]
OK, I've changed it to "Biological process overview (GO slim)".  I think that's an improvement.

**Comment by ValWood** [comment]
AS an aside, our slim  should have
GO:0032543 - mitochondrial translation
(I added this recently because mitochondrial translation is no longer a child of  mitochondrion organization). This caused  many mitochondrial translation components to no longer slim

http://www.pombase.org/browse-curation/fission-yeast-go-slim-terms-not-covered

where is the slim coming from...maybe the change did not get committed, I'll track the old ticket...

**Comment by ValWood** [comment]
https://github.com/geneontology/go-ontology/issues/13031

**Comment by mah11** [comment]
GO:0032543 is in the pombe slim in various GO files, including the ones accompanying the latest Chado build.

Even further along the tangent: The go-plus.obo file seems to get updated at GO less frequently, and perhaps less regularly, than the go-plus.owl version. I have no idea why, although GO's own documentation doesn't even acknowledge that the obo version exists.

**Comment by ValWood** [comment]
Do we need to tell anyone?

 @cjmungall

**Comment by kimrutherford** [comment]
> GO:0032543 - mitochondrial translation

I've added that to the config file in SVN: pombe-embl/website/pombase_v2_config.json
and re-released the site.  eg. http://pombase2.bioinformatics.nz/gene/SPAC23C11.09

**Comment by ValWood** [comment]
So, where should these links go.

The  
 "Biological process overview (GO slim)" should link to the full slim
and
help to the documentation 
http://www.pombase.org/documentation/pombase-go-slim-documentation
replacement?

**Comment by cmungall** [comment]
go-plus:

The decision to list only the OWL for go-plus here was conscious:

http://geneontology.org/page/download-ontology

obo format is not a good fit for some of the more advanced features of go-plus.

However, I have no desire to break things. If this is a dependency in your pipeline we can reinstate. Can't do it right now, can you file a ticket in go-ontology and assign me?

Looking towards the next 10 years, it would be great to get yours and @kimrutherford's opinion in particular on:

https://douroucouli.wordpress.com/2016/10/04/a-developer-friendly-json-exchange-format-for-ontologies/
https://github.com/geneontology/obographs

(I thought I'd sent this previously but can't find record in my email)

While we will necessarily support obo in the long term due to very large number of dependent pieces of software, we'd like to guide people towards the json as much as possible. After a few years it's become apparent the OWL is just hard for people to work with and forces abstractions that are not natural for standard bioinformatics tasks. The json is intended to include everything that can be included in the OWL, but in a developer-friendly way.

The JSON is not yet stable, we want to get feedback from as many developers/bioinformaticians/curators as possible before a 1.x

**Comment by ValWood** [comment]
I don't think its a problem for us....but I'm not sure.

@mah11 @kimrutherford ?

**Comment by ValWood** [comment]
I'll close this and  add the outstanding to the GO slim ticket.
@mah11  could you open a ticket for Chris if required.

**Comment by mah11** [comment]
> @mah11 could you open a ticket for Chris if required.

This is not my call to make. It's Kim who knows what he'll need. From his latest comment it sounds like either the OWL or the JSON would do.

**Comment by ValWood** [comment]
OK I didn't understand the issue...
