### ISSUE TITLE
pop ups for alleles at the edge of table

### ISSUE THREAD

**Issue by ValWood** [pombase/website#291]
look like this

![pop ups](https://cloud.githubusercontent.com/assets/7359272/25555686/ee950cfc-2ce4-11e7-9dde-e6793b6fb1fb.jpg)

would be better if they were not contrained by side of page (like mouse over)

Also here the mouse over pop up arrives and covers the box, and has some funny chars...

**Comment by ValWood** [comment]
- [x]  Hidden Should be fixed when the library is fixed
- [ ]  kim will fix other pop-up

**Comment by kimrutherford** [comment]
> kim will fix other pop-up

It now only shows one.

**Comment by kimrutherford** [comment]
I've changed the genotype details pop-up to be underneath the genotype description instead of to the right.  It still falls off the side of the page a bit but it's somewhat better.

I'm going to take the pombe-2017 milestone off this issue but leave it open until the ngx-bootstrap library has a fix.  Here's the issue: https://github.com/valor-software/ngx-bootstrap/issues/1111

**Comment by ValWood** [comment]
I think this is fixed?

**Comment by kimrutherford** [comment]
> I think this is fixed?

More or less.  I changed it to pop up below the genotype description instead of to the right so it's much less likely to happen now.
