### ISSUE TITLE
sequence feature pages

### ISSUE THREAD

**Issue by mah11** [pombase/website#37]
Sequence features, such as centromeric bits in #36, should have pages analogous to gene pages. SO term searches can then list IDs and link to pages in results.

To start with, just mimic the (few) parts of a gene page that have corresponding info for features – ID, coordinates, map image, literature, external refs if any, etc. Once there are some test pages available we can see if any further refinements are needed.

**Comment by ValWood** [comment]
We can wait a little while longer for these....

**Comment by kimrutherford** [comment]
> SO term searches can then list IDs and link to pages in results.

That's going to require a bit of work as the query system is currently very gene oriented.

Adding sequence feature pages is reasonably straight forward.

Here are the counts of feature types in Chado.  Most of the list is handled already on the gene pages.  Which types would be good to test sequence feature pages?

2 or 3 suggestions would be very helpful.  Thanks.


| feature type                            | count   |
| --------------------------------------- | ------- |
| allele                                  | 14945   |
| chromosome                              |     6   |
| dg_repeat                               |    11   |
| dh_repeat                               |    16   |
| exon                                    | 12114   |
| five_prime_UTR                          |  4874   |
| gap                                     |     4   |
| gene                                    | 56161   |
| gene_group                              |     5   |
| genotype                                | 23045   |
| intron                                  |   994   |
| long_terminal_repeat                    |   239   |
| low_complexity_region                   |    60   |
| LTR_retrotransposon                     |    14   |
| mating_type_region                      |     1   |
| mRNA                                    |  5140   |
| ncRNA                                   |  1527   |
| nuclear_mt_pseudogene                   |    17   |
| origin_of_replication                   |     7   |
| polyA_signal_sequence                   |     1   |
| polyA_site                              |    17   |
| polypeptide                             |  5140   |
| promoter                                |    73   |
| pseudogene                              |    31   |
| pseudogenic_exon                        |    73   |
| pseudogenic_transcript                  |    31   |
| region                                  |    28   |
| regional_centromere                     |     3   |
| regional_centromere_central_core        |     4   |
| regional_centromere_inner_repeat_region |     6   |
| repeat_region                           |    44   |
| rRNA                                    |    49   |
| snoRNA                                  |    57   |
| snRNA                                   |     6   |
| three_prime_UTR                         |  4803   |
| transcript                              |  6697   |
| TR_box                                  |     2   |
| tRNA                                    |   196   |

**Comment by ValWood** [comment]
We already have tickets open for allele pages (but these are slightly different  feature types  to the sequence features we are requesting pages for here)
allele | 14945

I don't think we need pages for 
chromosome | 6
low_complexity_region | 60
gap | 4


We will never manually annotate origins so we don't need pages for these:
origin_of_replication | 7 (these are the early 'well studied' origins, annotated so they appear in the browser with labels)

Obviously we have gene pages already
gene | 56161
and is_a gene(s):
ncRNA | 1527
rRNA | 49
snoRNA | 57
snRNA | 6
pseudogene | 31
LTR_retrotransposon | 14

and we have
genotype | 23045

and we don't need separate pages for 'transcripts' or their 'parts' because these are covered on the gene pages:
exon | 12114
five_prime_UTR | 4874
intron | 994
mRNA | 5140
tRNA | 196
three_prime_UTR | 4803
transcript | 6697
polyA_signal_sequence | 1
polyA_site | 17
polypeptide | 5140
promoter | 73
pseudogenic_exon | 73
pseudogenic_transcript | 31
TR_box | 2 
This leaves:

the various 'regions' 
region | 28 (this is a grouping term)

regional_centromere | 3
The centromeric parts:
dg_repeat | 11
dh_repeat | 16
regional_centromere_central_core | 4 (I"m a bit baffled why we have 4, need to look into that!)
regional_centromere_inner_repeat_region | 6

mating_type_region | 1

I'm not even sure that pages for these regions will be so useful.  What would they show? There is not really anything to annotate on the  individual repeats,  It might be better if our drop-down menus allowed people to get to these regions of the genome in the browser quickly
https://www.pombase.org/jbrowse/?loc=I%3A3753692..3789426&tracks=PomBase%20forward%20strand%20features%2CPomBase%20reverse%20strand%20features&highlight=

gene_group | 5 (I don't know what this refers to)

These are probably OK just as features in the browser
long_terminal_repeat | 239
nuclear_mt_pseudogene | 17
repeat_region | 44

**Comment by kimrutherford** [comment]
> gene_group | 5 (I don't know what this refers to)

There are five misc_features on chromosome 3 with /SO="SO:0005855":

FT   misc_feature    2450422..2452883
FT                   /note="18S, 5.8S, and 28S ribosomal RNA"
FT                   /SO="SO:0005855"

**Comment by kimrutherford** [comment]
If there are interesting non-gene features but it's not worth making a page per feature, we could always add a table of features to the documentation with columns: feature_type, chromosome, start, end.

The table could be automatically generated from a list of feature types in the configuration file.

**Comment by ValWood** [comment]
That might work well.

**Comment by kimrutherford** [comment]
> regional_centromere_central_core | 4 (I"m a bit baffled why we have 4, need to look into that!)

Chromosomes 1 and 3 have one each.  Chromosome 2 has 2:

```
FT   repeat_region   1620807..1624737
FT                   /systematic_id="SPRPTCENB.11"
FT                   /colour=4
FT                   /note="centromere central core"
FT                   /SO="SO:0001796"
FT                   /primary_name="cnt2.1"
FT   repeat_region   1624515..1627609
FT                   /systematic_id="SPRPTCENB.12"
FT                   /colour=4
FT                   /note="centromere central core"
FT                   /SO="SO:0001796"
FT                   /primary_name="cnt2.2"
```

**Comment by kimrutherford** [comment]
I'll add a basic sequence feature page to the documentation containing an automatically updating table.  I won't link to the page from the rest of the documentation until it's ready to go.

**Comment by ValWood** [comment]
> Chromosomes 1 and 3 have one each. Chromosome 2 has 2:

Now merged into a single core. This is probably a hangover from continuation!

**Comment by kimrutherford** [comment]
> I'll add a basic sequence feature page to the documentation containing an automatically updating table. I won't link to the page from the rest of the documentation until it's ready to go.

Done!  But very basic:  https://www.pombase.org/documentation/misc-sequence-features

More features can be added by adding SO term names to the "so_types_to_show" option in the config file:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L27

And the Markdown file for the page is here:
https://github.com/pombase/website/blob/master/src/docs/documentation/misc-sequence-features.md

There are no links to the page yet.  Let me know if there is anything to add or remove from the table.

**Comment by mah11** [comment]
Could we configure some prettier display strings somewhere, e.g. substitute for the SO term names

- regional_centromere -> centromere
- regional_centromere_central_core -> centromere central core

and just use '1', '2', and '3' for the chromosome?

**Comment by mah11** [comment]
It's off to a good start, though - thanks!

**Comment by kimrutherford** [comment]
> Could we configure some prettier display strings somewhere, e.g. substitute for the SO term names

Good plan.  I'll do that next week.

> and just use '1', '2', and '3' for the chromosome?

Would "I", "II", "III", etc. be OK?  That what we have in JBrowse and in the "Genomic location" on the gene pages.

**Comment by mah11** [comment]
> Would "I", "II", "III", etc. be OK?

Sure! The important thing (to me) is not to repeat "chromosome" in the table cells when it's already right there in the header.

**Comment by kimrutherford** [comment]
> Would "I", "II", "III", etc. be OK? 

That's done now.

> Could we configure some prettier display strings somewhere, e.g. substitute for the SO term names

I've added a new config setting (`term_display_names`) to specify the displayed term names:
https://github.com/pombase/pombase-config/blob/master/website/pombase_v2_config.json#L5786
https://github.com/pombase/website/wiki/Config-file#term_display_names

**Comment by kimrutherford** [comment]
I should have mentioned this earlier:
some of the feature IDs in the table aren't great: `CU329670_regional_centromere_3753687..3789421`

These are automatically generated by the loader because there is no /systematic_id for the feature.

**Comment by ValWood** [comment]
- [ ] CU329670_regional_centromere_3753687..3789421
This is the "CU329670" should we give a shorter PomBase ID?

- [ ] The centromere repeat features aren't strand-specific so this should be n/a

**Comment by ValWood** [comment]
OK I now see your follow up comment about the IDs!

**Comment by mah11** [comment]
> I've added a new config setting (term_display_names) to specify the displayed term names:

cool; thanks :)

**Comment by kimrutherford** [comment]
> The centromere repeat features aren't strand-specific so this should be n/a

Currently all features are stored as either forward or reverse strand in Chado.  I don't know how to specify that a feature is unstranded in EMBL format.  Googling didn't help.  We might have to make something up, perhaps a qualifier.

**Comment by kimrutherford** [comment]
> The centromere repeat features aren't strand-specific so this should be n/a

As a temporary fix, I'll remove the strand column.

**Comment by ValWood** [comment]
We have a use case for feature  pages for japonicusDB.

PomBAse transposons always correspond to  ORFs, so are annotated as CDS.
In japonicus the transposons are often quite degraded, and even the ones which aren't  are 
annotated as the full length Transposon, including  the LTR (I think).
Anyway I could not easily see Orfs, but I will look again once they are in the contigs as misc features.

I think we could have pages for these so that people find them when they search with the IDs, although there would not be much to say about them....

**Comment by kimrutherford** [comment]
> I think we could have pages for these so that people find them when they search with the IDs, although there would not be much to say about them....

Would it be enough to be able to search by ID, but get sent to a page like this when you press enter?:
https://www.pombase.org/documentation/misc-sequence-features

That saves a bit of work for me and avoids having features pages that don't contain very much.

**Comment by ValWood** [comment]
This works for me. It is a nice stepping stone until there is sufficient motivation & justification to add the pages which would have knock-on effects for querying etc.
It would at least allow people to see what non-gene features were annotated, and allow them to get to the location in the browser for any non-gene feature.

I think this page would be better if the JBrowse link was the first column after the name and feature types because I didn't realise it was there (you need to scroll right to see it).

**Comment by kimrutherford** [comment]
> This works for me. It is a nice stepping stone until there is sufficient motivation & justification to add the pages which would have knock-on effects for querying etc.

That makes sense.  I'll do that soon.  I should be pretty quick to implement.

> I think this page would be better if the JBrowse link was the first column after the name and feature types because I didn't realise it was there (you need to scroll right to see it).

I've made that change, which should be visible in 20-30 minutes.

**Comment by ValWood** [comment]
Does anyone remember the history of why we have the coordinates in the regional centromere IDs?

**Comment by kimrutherford** [comment]
> Does anyone remember the history of why we have the coordinates in the regional centromere IDs?

I don't remember.  It doesn't seem very useful.  Something shorter makes sense.

**Comment by kimrutherford** [comment]
> I think we could have pages for these so that people find them when they search with the IDs,

Now I've thought about it more, how will they know the IDs so they can search for them?  They're pretty obscure.

**Comment by ValWood** [comment]
Just spotted a comment above:

'I should have mentioned this earlier:
some of the feature IDs in the table aren't great: CU329670_regional_centromere_3753687..3789421"

CU329670 can be the ID, and  they can have labels CEN1, CEN2, CEN3 which are the 'traditional' abbreviations as 'primary/human readable names'


> I think we could have pages for these so that people find them when they search with the IDs, although there would not be much to say about them....

this was in the context of the full length transposons which should have a label that the users recognise, but I don't think there is any urgency for these pages since the will not be any annotation. They are basically coordinates and a label.

**Comment by ValWood** [comment]
I prefer just the sequence feature page,  I think...it is really only required to 'get to this place in the genome' so a page where you can see all  non gene features as a list will be great...

**Comment by kimrutherford** [comment]
> 'I should have mentioned this earlier:
> some of the feature IDs in the table aren't great: CU329670_regional_centromere_3753687..3789421"

There are lots of features in Chado with similar IDs.  These are automatically generated for features that don't have a `/systematic_id`.  The start..end is added to make them unique.  The SO feature name (like `regional_centromere`) is there because of `/SO=...` qualifiers.

Here are some examples:

```
 CU329670_promoter_2992573..2992582
 CU329670_promoter_2992592..2992599
 CU329670_polyA_site_2999546..2999546
 CU329670_polyA_site_2999663..2999663
 CU329670_low_complexity_region_3030456..3033580
```

> CU329670 can be the ID

I think that would be confusing because that's the ENA ID for the chromosome.

**Comment by ValWood** [comment]
So should I just give them IDs

SPCEN1
SPCEN2
SPCEN3
?

**Comment by kimrutherford** [comment]
> So should I just give them IDs
> SPCEN1
> SPCEN2
> SPCEN3

That seems sensible to me.

**Comment by ValWood** [comment]
I had forgotten about this. Do we link to this page yet? I could not find it

**Comment by kimrutherford** [comment]
> I had forgotten about this. Do we link to this page yet? I could not find it

There's no link to it yet.

**Comment by ValWood** [comment]
https://www.pombase.org/documentation/misc-sequence-features
needs a link from the documentation, and we need a list of outstanding tasks here.

**Comment by kimrutherford** [comment]
> needs a link from the documentation,

I've added a "Non-gene sequence features" section here, with a link to the new page:
 - https://www.pombase.org/documentation

(If you have any ideas for a better title please let me know, or [edit directly](https://github.com/pombase/website/blob/master/src/docs/documentation/index.md))

The new sequences features page has a bit of an overlap with:
 - https://www.pombase.org/status/centromeres

It's not urgent, but should we combine them somehow?

**Comment by ValWood** [comment]
I think it is good to keep the centromere cartoon.
We could relabel this page 'Schematic of the centromere" and link to it from the new page.

We don't need any of this text:
~At present, each centromere is annotated as a single sequence feature in PomBase, which can be viewed in and downloaded from the genome browser.
Chromosome coordinates (links to JBrowse):
CEN 1: [I:3753687-3789421](https://www.pombase.org/jbrowse/?loc=I%3A3753680..3789414&tracks=DNA%2CForward%20strand%20features%2CReverse%20strand%20features&highlight=)
CEN 2: [II:1602264-1644747](https://www.pombase.org/jbrowse/?loc=II%3A1602261..1644744&tracks=DNA%2CForward%20strand%20features%2CReverse%20strand%20features&highlight=)
CEN 3: [III:1070904-1137003](https://www.pombase.org/jbrowse/?loc=III%3A1070899..1136998&tracks=DNA%2CForward%20strand%20features%2CReverse%20strand%20features&highlight=)
Note that specific repeats within centromeres cannot yet be viewed or searched as features on PomBase pages, but they are included in the forward and reverse strand feature tracks in the genome browser, which are enabled by default.~

**Comment by kimrutherford** [comment]
> we need a list of outstanding tasks here.

I don't think there's anything else to do and this issue is getting a bit long. So I'll close it.

I've made the changes to the centromeres pages that you suggested.
