### ISSUE TITLE
Protein domains and features data, part 2

### ISSUE THREAD

**Issue by ValWood** [pombase/website#383]
Outstanding from
https://github.com/pombase/website/issues/96#issuecomment-306468594

- [x]  Molecular weight	should be reported in kDA with units 2DP 	34358.2-> 34.36 kDa

- [x] should we add no of residues explicitly here (its already at top of page)

 - [ ]   Codon Adaptation Index	is different on old and new site, which is correct? 
cf cdc2 0.43 - >  0.57
 
- [x] arrange families /domains by count lowest to highest number of hits. This is more logical is it moves from sub-family to family to superfamily information.
No count at the end

**Comment by kimrutherford** [comment]
> - Molecular weight should be reported in kDA with units 2DP 34358.2-> 34.36 kDa
> - should we add no of residues explicitly here (its already at top of page)
> - arrange families /domains by count lowest to highest number of hits

All done.

> No count at the end

I don't understand that.

**Comment by kimrutherford** [comment]
> Codon Adaptation Index is different on old and new site, which is correct?

Possibly neither.  :-(

I meant to check the value for CAI after putting that table in but I forgot.  I just tried calculating it here on an example gene and got a different answer to p1 and p2: http://genomes.urv.es/CAIcal/

For any1/SPBC18H10.20c on P1: 0.41, P2: 0.57 and that web site: 0.70.

For P2 the CAI is value is calculated using this Perl module: http://search.cpan.org/~shardiwal/Bio-Tools-CodonOptTable-1.05/lib/Bio/Tools/CodonOptTable.pm

Now I think about it, that module doesn't use a codon usage table to calculate the value so it's definitely wrong.

I tried calculating the CAI with EMBOSS and that gives an answer close to the website: 0.693
I think it's probably best if I change to code to use EMBOSS instead of the Perl module.

I've added a codon usage file for EMBOSS:
https://github.com/pombase/pombase-chado/blob/master/etc/S_pombe.cut

**Comment by ValWood** [comment]
> No count at the end

I think this meant that "domains" with no count should go at the bottom of the table, but if that only applies to mobidb it is replaced by
https://github.com/pombase/website/issues/385

Re CAI,  we can postpone this and leave it off the page until someone asks,   I only know of one person who has ever used it and its probably only useful in context of the other proteins so not particularly useful on the gene pages.....

**Comment by kimrutherford** [comment]
Great.  I'll close this.
