### ISSUE TITLE
Handle introns in UTRs correctly in sequence export

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#401]
Currently the sequence section of the gene pages doesn't include the introns that are within UTRs in the output even if you tick the "Include introns" box.

**Comment by ValWood** [comment]
@mah11 said this was done. can close?

**Comment by mah11** [comment]
I did not comment on this issue.

**Comment by ValWood** [comment]
Hmm, I thought i posted a follow up comment here last night. Clearly got lost.
Initially I thought  when i first commented this was to do with
https://github.com/pombase/website/issues/397#issuecomment-313048692

but I now think this is a separate issue. I see this is about introns in UTRs. 
We should probably discuss. There are problems here because introns in UTRs are often unknown/unannotated. Not sure what the best behavior is nut not had time to think about it yet....

**Comment by mah11** [comment]
I thought this ticket was just saying that, where we _do_ have introns annotated, the sequence retrieval doodad isn't handling them correctly.

**Comment by mah11** [comment]
I haven't tested it myself, but I would expect UTR introns to be handled as introns because, well, they are.

**Comment by kimrutherford** [comment]
Tell the user explicitly if the sequence includes introns in the UTRs.  We should say something like "(Includes 2 introns in 5'UTR)" if a UTR and intron options are selected and there are UTR introns.

**Comment by kimrutherford** [comment]
See also: #461.

**Comment by kimrutherford** [comment]
I've made it explicit that we include UTR introns when the user selects the UTR and intron checkboxes.
The message is only shown when there actually are introns in a UTR.

I think this issue is done now.
