### ISSUE TITLE
search on "unmapped gene list"

### ISSUE THREAD

**Issue by ValWood** [pombase/website#406]
It would be nice if, in the future, if you searched for a name  in this
list, the drop down would show:
scr1 (S PBC1D7.02c)
scr1 (physically unmapped)

That seems like it would be useful in case people get lead into thinking
that scr1 (SPBC1D7.02c) is *the* supressor of cyclohexamide resistance.
We don't want to create gene pages for these  because they would be
largely empty and it would make genome  "tallies" confusing.

**Comment by kimrutherford** [comment]
I don't understand this one.  Is scr1 unmapped?  Isn't it on chr2?

**Comment by ValWood** [comment]
yes  but that isn't the same scr1 as the unmapped one. This wouldn't be possible though   unless we stored "unmapped" genes as a different class of gene name?

(I can't  find the unmapped gene list by the way? @mah11  where does it live?)

**Comment by kimrutherford** [comment]
> yes but that isn't the same scr1 as the unmapped one.

There are two genes with the same name?  I didn't know that was a thing.  (Although I've just queried and found mat3-Mc and mat3-Mm - I forgot about those)

**Comment by ValWood** [comment]
There aren't supposed to be, but there may be unmapped markers that have been named as physically mapped genes....can explain later.


mat3-Mc and mat3-Mm are the same thing that's complicated too... @Antonialock  can explain :)

**Comment by Antonialock** [comment]
Val you are looking for this list: https://curation.pombase.org/pombase-trac/wiki/PhysicallyUnmappedGenesProteins

mat3-mc and mat3-mi are two duplicated genes. They are duplicated because the sequenced strain doesn't have a complete silent mating type locus (the sequenced strain contains mat3-mc and mat3-mi, but mat3-Pc and mat3-Pi are deleted). We therefore have the silent mating type locus in a separate file. This separate file unhelpfully contains all 4 genes, so the Mc and Mi genes are duplicated.

**Comment by ValWood** [comment]
I . put this as"future" as it likely won't happen
