### ISSUE TITLE
canned queries for query tool

### ISSUE THREAD

**Issue by ValWood** [pombase/website#416]
Kim and I discussed briefly last week, and I just found this list on the wiki, we can refine and add to it. It should include any list in the FAQ

 - [ ] ANY 'disease' gene
- [ ]  All sequence specific transcription factors
- [ ]  All deletion allele viable/inviable
- [ ] All protein coding genes (ex dubious and transposon)

**Comment by kimrutherford** [comment]
> ANY 'disease' gene

Is that any gene with an annotation to a term from the disease_associated CV?

>  All sequence specific transcription factors

Could you explain that one?

> All protein coding genes (ex dubious and transposon)

Is that the same as querying for a product type of "protein"?

**Comment by mah11** [comment]
>> ANY 'disease' gene
> 
> Is that any gene with an annotation to a term from the disease_associated CV?

Yes. We used a query for genes annotated to PBO:5000000 in the old FAQ (with link to advanced search).

>> All sequence specific transcription factors
> 
> Could you explain that one?

It's a little complicated. The old FAQ describes and links to two suggested queries (see http://www.pombase.org/faqs/how-can-i-find-transcription-factors-and-their-targets-pombase). I think the one that gets transcription factors is (GO:0000976 OR GO:0003700), but we also suggest (GO:0000978 AND (characterisation status = published)) in case people want to see if there are targets published that we haven't got curated. 

>> All protein coding genes (ex dubious and transposon)
> 
> Is that the same as querying for a product type of "protein"?

To get the "ex [i.e. don't include] dubious and transposon", it has to be ((product type = protein) AND NOT (characterisation status = dubious) AND NOT (characterisation status = transposon)). Because reasons.

**Comment by kimrutherford** [comment]
Thanks.

There is a section in the config file called "predefined_queries" that can be used to configure any query that can be made in the query builder.  My plan is to configure these canned queries there.  What's missing is an easy way to export a query from the query builder.  I've added an issue for that: #492

**Comment by ValWood** [comment]
We should  probably be a little bit more specific about what these terms find in the docs (since it is so confusing!)

We should say that in GO transcription factor are described by two molecular function terms, 
 a DNA binding activity and a  "transcriptional regulator  activity"


transcription factor activity, sequence-specific DNA binding (GO:0003700)
should find all DNA binding transcription factors.
This will include mitochondrial, Pol I, II and III DNA binding TF-s


To restrict to pol II use
transcription factor activity, RNA polymerase II core promoter proximal region sequence-specific binding (GO:0000982)
(the transcription factor term)
Or 

RNA polymerase II core promoter proximal region sequence-specific DNA binding (GO:0000978)
the DNA binding term

(annotations *should* be equivalent, I check this periodically, they appear to have deviated by 2)
--

**Comment by kimrutherford** [comment]
This is implemented now for these two canned queries:

> ANY 'disease' gene
> All protein coding genes (ex dubious and transposon)

but won't be in the preview until later.

>  All deletion allele viable/inviable

This one needs a bit of work on the server side.  The web code needs to generate those subsets so that the query builder can use them.  It won't take long so I'll do that next.

> All sequence specific transcription factors

I'm still confused by that one.  To make it easier (for me at least) I've added a way to get the JSON representation of a query so I can paste that JSON into the config file.  Once the preview is updated later you'll be able to double click on the query description in the query history table to get a pop-up dialog containing the JSON.  Once it's re-released, I'll ask you to do the query and let me know the JSON.

**Comment by kimrutherford** [comment]
> This is implemented now for these two canned queries:
>> ANY 'disease' gene
>> All protein coding genes (ex dubious and transposon)
> but won't be in the preview until later.

There is now a "Canned queries" tab in the query builder.  Is that the label we want?

**Comment by kimrutherford** [comment]
>> All deletion allele viable/inviable
> This one needs a bit of work on the server side. The web code needs to generate those subsets
> so that the query builder can use them. It won't take long so I'll do that next.

I only just noticed that this issue is "after public release" so I'm going to work on other things first.

**Comment by kimrutherford** [comment]
> Once the preview is updated later you'll be able to double click on the query description in the query
> history table to get a pop-up dialog containing the JSON.

That's working now so if you come up with any other queries to add to the "canned queries" just double click on the query description (the "Query" column in the history) and send me the JSON it shows you.

**Comment by ValWood** [comment]
> All sequence specific transcription factors

yes curators should figure out the best way to do this query (there are 2 branches which should be concurrently annotated).

Also, it might help users to have 2 queries

> All sequence specific transcription factors
> All RNA pol II sequence specific transcription factors

**Comment by kimrutherford** [comment]
> All sequence specific transcription factors
> All RNA pol II sequence specific transcription factors

They're easy to add if you can send me the query JSON.

**Comment by ValWood** [comment]
@mah11  done?

**Comment by ValWood** [comment]
can open a new ticket for anything else?
