### ISSUE TITLE
biogrid links

### ISSUE THREAD

**Issue by ValWood** [pombase/website#420]
I notice this 

https://thebiogrid.org/276415/summary/schizosaccharomyces-pombe/SPBC1861.02.html

goes to cdc2 page?
maybe this is  because this GP has no biogrid annotations?

**Comment by kimrutherford** [comment]
If you put SPBC1861.02 in the biogrid search box you get ABP2 (in capitals).  A biogrid bug?

**Comment by mah11** [comment]
I had a play plugging various pombe systematic IDs into the BioGRID URL without changing the format, and found that they don't find anything. Instead, the last gene page that it did find gets displayed (i.e. it's nothing specific to cdc2, and has nothing to do with how many annotations any gene has).

Putting systematic IDs in the search box works for me too. BioGRID appears to use standard gene names in URLs for named genes. For unnamed genes it converts the systematic ID to all lower case and removes internal dots (e.g. SPBC1685.04 becomes spbc168504.html).

This is odd behavior on the part of the BioGRID site, whether intended or otherwise. A "not found" message would be a lot more helpful.

**Comment by ValWood** [comment]
action, report to biogird

**Comment by ValWood** [comment]
reported
