### ISSUE TITLE
make autocomplete only show used ontology terms

### ISSUE THREAD

**Issue by ValWood** [pombase/website#432]
Re:the completion searches all terms from the given ontology including those that have no annotation.

Applies mainly  to GO and MOD

Much better to see only terms used...

**Comment by kimrutherford** [comment]
> Much better to see only terms used...

Note to myself: remember to also include terms where a descendant has annotation.

**Comment by ValWood** [comment]
can punt if necessary

**Comment by kimrutherford** [comment]
> can punt if necessary

Fixing this and getting the "PBO disease associated" search (see #430) working is more or less the same problem.  So punting this means punting the disease associated query.

**Comment by ValWood** [comment]
That's ok for release. We can help people offline if they need it. Its not a very common query (except for writing grants). Not very useful for combination with other queries...well it could be but I doubt anyone will know how...

**Comment by ValWood** [comment]
Actually there will be a work around anyway.....

If somebody wanted to do, for example, a query with all "neurological disorders"
we can point them to the page,
http://preview.pombase.org/term_genes/PBO%3A0000363
from here they can grab the list and pop it in QB

**Comment by kimrutherford** [comment]
> we can point them to the page,
> http://preview.pombase.org/term_genes/PBO%3A0000363
> from here they can grab the list and pop it in QB

That's easier now you can put the PBO ID into the search box and you can click "Use these genes in query..." on the term gene list page.

**Comment by ValWood** [comment]
neat!

**Comment by ValWood** [comment]
Is this tricky? If so we can remove the milestone... it isn't ctitical

**Comment by kimrutherford** [comment]
I've looked into this yesterday.

It's quite tricky.  Partly because it not easy to coordinate updates of the auto-complete/search data and keep them in sync with the rest of the site.  And it's partly because I'd like to use Solr to do the searching but it's a bit of a steep learning curve.  Solr isn't the simplest solution but none of the alternatives are easy either.  I'm keen on Solr because it's very fast, there are lots of tutorials and other documentation available and it will cope with any searching or auto-completing we'll need in future.  An example we might want to think about is searching publication authors, titles and abstracts.

Solr is more or less Lucene with a web service interface: http://lucene.apache.org/solr/

**Comment by ValWood** [comment]
OK, Post release....

**Comment by kimrutherford** [comment]
> OK, Post release....

So we were going to put this off but I started investigating Solr and Lucene to see how tricky it was.

After a day or two of fighting with them I now have my head around them enough to implement the autocomplete for the query builder. I've configured Solr and loaded the terms with annotations. I still need to wire up the query builder to Solr and do some tuning. I think that will take a day or so.

**Comment by kimrutherford** [comment]
After a bit more work there is now a prototype with Solr/Lucene completion:
  http://pombase-dev.bioinformatics.nz/

and this version should only autocomplete on terms that have annotation.  It should also be faster but that's a bit hard for me to check from NZ as most things are slow here.

It still needs some tuning of results to make sure the most relevant terms appear at the top.  Currently the result order will be different to what you get from Canto.  I'll work on that.

I'd appreciate if you could give it a try.

**Comment by ValWood** [comment]
I'm using it now and it seems fine. I'd need to use it more extensively to see if there are any problems with term relevance but I didn't notice any. Also,  I did not notice any unused terms, and the speed seems fine too.

**Comment by ValWood** [comment]
searching on an ID doesn't work though....

GO:0000978 should give
RNA polymerase II core promoter proximal region sequence-specific DNA binding (GO:0000978)

but suggests
nuclear-transcribed mRNA catabolic process, no-go decay (GO:0070966)
and 
GINS complex (GO:0000811)

**Comment by kimrutherford** [comment]
> searching on an ID doesn't work though....

That's fixed in the dev version:
  http://pombase-dev.bioinformatics.nz/query

**Comment by kimrutherford** [comment]
> That's now fixed in the dev version:

The preview will be offline for a while tonight for a one-off upgrade.

**Comment by kimrutherford** [comment]
> The preview will be offline for a while tonight for a one-off upgrade.

All fixed and the preview now does auto-completion using Solr.  There's no need to use pombase-dev.bioinformatics.nz anymore.

Everything is now set up on the Babraham server so that the preview will restart if the server reboots at any point.  It's also now very easy to move to a new server if there was a problem at Babraham and it's all set so the we can swap www.pombase.org to use the new website when we're ready.

**Comment by ValWood** [comment]
great !

**Comment by kimrutherford** [comment]
This wasn't working yesterday, but it is now: the autocomplete can cope with minor typos.  So if you type:
  transcxiption factro protnien bindink   

it suggests:
  transcription factor activity, protein binding

**Comment by ValWood** [comment]
fantastic, it might even understand my typo's perhaps!

**Comment by Antonialock** [comment]
:D

**Comment by kimrutherford** [comment]
I'll close this but please open new issues for completion weirdness.
