### ISSUE TITLE
Missing Ensembl images for SPAC110.06

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#448]
It's not in PomBase v1 either.  Is it new?

**Comment by ValWood** [comment]
well not that new....

/controlled_curation="term=warning, new gene; db_xref=PMID:24929437; date=20140704"
/controlled_curation="term=warning, replaced existing SPAC110.05 which was in the wrong frame; db_xref=PMID:24929437; date=20160317"

strange....but not surprising that Ensembl genomes is over a year out of date. I won't attempt to do anything about that since I haven't had a reply to any of my previous e-mails.

I wonder if they plan to continue get data directly from us, or from EMBL ) which is seriously out of date. I need to update, but it is a wold of pain....
