### ISSUE TITLE
missing annotations

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#471]
quite a large number of annotations are missing from this publication: 
http://pombase2.bioinformatics.nz/reference/PMID:10348908
https://curation.pombase.org/pombe/curs/8e27bf8723065210

e.g cellular component: nucleus & a large number of phenotypes

last time it was approved was back in 2015.

**Comment by Antonialock** [comment]
(FYI i just added 2 extensions to the nucleus term)

**Comment by kimrutherford** [comment]
Hi.  I think you were looking at the wrong preview page.  This looks OK:
  http://pombase2.bioinformatics.nz/reference/PMID:11129048

**Comment by Antonialock** [comment]
ah that looks better but it is stil missing this anntation:

  | prr1Δ | FYPO:0000280 | sterile

(that's what promted me to look at this paper...I was going to add that annotation, I thought I had missed it, but then I saw that it was present in the session).

**Comment by kimrutherford** [comment]
> prr1Δ | FYPO:0000280 | sterile

I've look into that.  Could it be that sterile isn't a cell phenotype and isn't a population phenotype so is not shown?

**Comment by Antonialock** [comment]
hmm, yeah...ste11 isn't showing sterile either

**Comment by Antonialock** [comment]
odd though...old site also sorts population/cell and it is showing there
http://www.pombase.org/spombe/result/SPAC8C9.14#fission_yeast_phenotype-single_allele-cell_phenotype

**Comment by kimrutherford** [comment]
I checked Chado and the missing annotation is there.  I checked the parents of "sterile" and it isn't a descendant of the "population phenotype" term (FYPO:0000003) and it's not a descendant of the cell phenotype terms (FYPO:0000002 and FYPO:0000652).  So I think that explains it.

> odd though...old site also sorts population/cell and it is showing there

I checked the code for the old site.  On the old pages anything the isn't a descendant of the population phenotype term (FYPO:0000003) is put in the "cell phenotype" section of the page.

**Comment by mah11** [comment]
Kim's right, sterile and other mating phenotypes are neither cell nor population phenotypes in FYPO. I kind of think that's biologically reasonable - it takes two to tango (or mate), so it's not strictly a cell-level process. Technically two can count as a small "population" but I suspect that's not very intuitive; certainly I tend to think of the population phenotypes as the ones you assay by looking at a big population in a culture.

There are other terms that aren't classified as either cell or population - the molecular function phenotypes, developmental process phenotypes (mainly because of the ascus, which isn't a single cell), and a handful of oddballs that defy categorization.

I don't remember explicitly requesting that mating phenotypes go under cell phenotype for the legacy pombase display, but that appears to be what it does.

I wouldn't object to putting anything that's not a population phenotype under cell phenotype for the pombase page displays if it's easy for Kim to do. That would be better than kludging up the ontology itself.

**Comment by mah11** [comment]
<mutter mutter> wrong sodding button </mutter>

**Comment by Antonialock** [comment]
that would work for me..

**Comment by Antonialock** [comment]
this rings a bell, I guess we must have had the same discussion eons ago :-)

**Comment by kimrutherford** [comment]
> this rings a bell, I guess we must have had the same discussion eons ago :-)

Yep! #259

**Comment by kimrutherford** [comment]
> I wouldn't object to putting anything that's not a population phenotype under cell phenotype for
> the pombase page displays if it's easy for Kim to do.

Currently the code expects to be configured with a list of high level terms for each category.  So the quickest fix for "sterile" is to at another term to the config. like: FYPO:0000301 mating phenotype

If it helps I can do a query to find terms that still wouldn't appear in either category.

**Comment by mah11** [comment]
I found around sixty or so terms that don't fall under MF, cell or population phenotype, but I didn't check how many of those are under mating or developmental process.

**Comment by kimrutherford** [comment]
> I found around sixty or so terms that don't fall under MF, cell or population phenotype,

I get 62 so that consistent.

Only 29 of those have annotation:

 abnormal ascus development
 abnormal conjugation
 abnormal telomeric repeat sequence
 altered cytochrome absorption spectrum
 conjugation without glucose starvation
 conjugation without nitrogen starvation
 decreased concentration of M-factor in growth medium
 decreased concentration of P-factor in growth medium
 decreased pH of growth medium
 decreased queuosine level in tRNA
 h- specific sterility
 h+ specific sterility
 increased Argonaute-associated RNA length
 increased concentration of M-factor in growth medium
 increased concentration of P-factor in growth medium
 increased concentration of polysaccharide in growth medium
 increased poly(A) tail length
 normal ascus morphology
 normal conjugation
 normal conjugation frequency
 normal frequency of conjugation with h+ cells
 normal galactose:mannose ratio in glycoprotein glycan
 normal minichromosome loss
 normal monoacylglycerol phosphate chain length
 normal poly(A) tail length
 normal telomeric repeat sequence
 normal topoisomerase-DNA adduct level
 queuosine absent from tRNA
 sterile

If I filter out FYPO:0000301 mating phenotype too there are only 20:

 abnormal ascus development
 abnormal telomeric repeat sequence
 altered cytochrome absorption spectrum
 decreased concentration of M-factor in growth medium
 decreased concentration of P-factor in growth medium
 decreased pH of growth medium
 decreased queuosine level in tRNA
 increased Argonaute-associated RNA length
 increased concentration of M-factor in growth medium
 increased concentration of P-factor in growth medium
 increased concentration of polysaccharide in growth medium
 increased poly(A) tail length
 normal ascus morphology
 normal galactose:mannose ratio in glycoprotein glycan
 normal minichromosome loss
 normal monoacylglycerol phosphate chain length
 normal poly(A) tail length
 normal telomeric repeat sequence
 normal topoisomerase-DNA adduct level
 queuosine absent from tRNA

**Comment by mah11** [comment]
I don't think it would be outrageous to lump those in with cell phenotypes for display.

**Comment by kimrutherford** [comment]
> I don't think it would be outrageous to lump those in with cell phenotypes for display.

I'll do that.

I tried looking for a short list of high level IDs I can add to the configuration to cover those.  Unfortunately there aren't many.

There are quite a few direct children of normal phenotype (FYPO:0000257).  Like:

    normal galactose:mannose ratio in glycoprotein glycan - FYPO:0004942
    normal ascus morphology - FYPO:0005157

I'll add those IDs to the config.

There are a couple of direct children of "normal vegetative phenotype" - FYPO:0001312
Is it OK to put all descendants of FYPO:0001312 in with the cell phenotypes?  There aren't many at the moment.  An example is:

    normal monoacylglycerol phosphate chain length - FYPO:0005582

These two have only abnormal phenotype as a direct parent so there isn't a higher level grouping term that covers them:

    decreased queuosine level in tRNA - FYPO:0003427
    abnormal poly(A) tail length - FYPO:0002929

"abnormal ascus development" is a descendant of "abnormal biological process" - FYPO:0005447 and of "biological process phenotype" - FYPO:0000300.  Is there any problem with including either of those terms in the config for the cell phenotype section?

Apart from "normal vegetative phenotype" the only other high level term we can add is:

    altered effect on growth medium - FYPO:0001155

which has a few child terms in the list.

**Comment by kimrutherford** [comment]
The annotation to sterile is there now, but appears twice :-/

I'll fix that tomorrow or Monday.

**Comment by mah11** [comment]
erm, on some of the FYPO term pages it looks like everything is duplicated

examples:
population - http://preview.pombase.org/term/FYPO:0002344
cell - http://preview.pombase.org/term/FYPO:0003486

**Comment by kimrutherford** [comment]
> The annotation to sterile is there now, but appears twice :-/

The duplication is fixed now.
