### ISSUE TITLE
add prompt to protein domain query in advanced search

### ISSUE THREAD

**Issue by ValWood** [pombase/website#472]
People might try to type "protein kinase family" or WD repeat (although it would not be a bad thing if they could).

For now, can we have some prompt showing maybe a Pfam and an InterPro ID to make it clear that is what is accepted in the box...

**Comment by ValWood** [comment]
In fact, I can't get this to work with
PF02373
Pfam:PF02373
but I know we have some

**Comment by kimrutherford** [comment]
> In fact, I can't get this to work with PF02373

I checked and that domain isn't in the data that the query builder uses.  I think it's because that domain has an InterPro ID (IPR003347) so it's not saving the pfam ID.

I'll fix it to allow the non-InterPro IDs too.

Note to self - here's an example gene:
  http://pombase2.bioinformatics.nz/gene/SPCC622.16c

**Comment by kimrutherford** [comment]
> In fact, I can't get this to work with
> PF02373
> Pfam:PF02373

That's fixed now.

I haven't added the prompt yet.

**Comment by kimrutherford** [comment]
I've added "eg. PF02373 or IPR001138" as a prompt.  How's that?

**Comment by ValWood** [comment]
perfect.
