### ISSUE TITLE
population phenotypes showing in cell phenotype section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#483]
The population phenotypes are also showing in the cell phenotype section
<img width="635" alt="screen shot 2017-08-11 at 12 01 13" src="https://user-images.githubusercontent.com/12727506/29210748-e6362b50-7e8c-11e7-9461-1bf7f4210ab7.png">

**Comment by kimrutherford** [comment]
It looks like the problem is that I recently added FYPO:0000300 (biological process phenotype) to the list of terms to include in the "Cell phenotype" section.  But those "sensitive to ..." terms are descendants of FYPO:0000300 and are also descendants of 0000003 (cell population phenotype).

We added FYPO:0000300 because there were some terms that weren't in either list on the gene pages:
  https://github.com/pombase/website/issues/471#issuecomment-320228727

I'll take FYPO:0000300 out of the config.  The only term that will go missing from the gene page when I do that is FYPO:0000680 ("abnormal ascus development").  Maybe an ontology change can fix that?

After that change the populate phenotype section will include all descendants of:
  FYPO:0000003 and FYPO:0001155

The cell phenotype section will include descendants of:

    FYPO:0000002, FYPO:0000652, FYPO:0000300, FYPO:0000301, FYPO:0001312,
    FYPO:0002928, FYPO:0002931, FYPO:0003093, FYPO:0003324, FYPO:0003427,
    FYPO:0003480, FYPO:0004914, FYPO:0004915, FYPO:0004942, FYPO:0005157

Sorry about the long list.  It was needed to cover everything.

**Comment by kimrutherford** [comment]
It's looking much better now.  You'll need to shift-reload to see the change.

**Comment by mah11** [comment]
> The only term that will go missing from the gene page when I do that is FYPO:0000680 ("abnormal ascus development"). Maybe an ontology change can fix that?

Sorry, FYPO:0000680 wouldn't fit biologically under any of the other high-level terms configured to show up in the cell phenotype section. Better to add it itself.

Also, is there a regular(ish) check for terms that are used in annotations but wouldn't show up on pages? I noticed that FYPO:0002930 isn't in the configuration list - it doesn't have annotations at the moment but we may use it somewhere along the line, and when we do we would want it displayed.

**Comment by kimrutherford** [comment]
> Sorry, FYPO:0000680 wouldn't fit biologically under any of the other high-level terms configured
> to show up in the cell phenotype section. Better to add it itself.

OK, I've added that and I'll rerun things soon.

> Also, is there a regular(ish) check for terms that are used in annotations but wouldn't show up on pages?

It's a manual check at the moment.  If you think it's worthwhile checking on every load, could you add an issue about it?

> I noticed that FYPO:0002930 isn't in the configuration list

FYPO:0002929 is slightly more general.  Would it be better to add that to the config?

**Comment by mah11** [comment]
>>  Also, is there a regular(ish) check for terms that are used in annotations but wouldn't show up on pages?
>>
> It's a manual check at the moment. If you think it's worthwhile checking on every load, could you add an issue about it?

Every load feel like overkill, but I'll open a ticket anyway. Chado tracker (for logs)?

>>   I noticed that FYPO:0002930 isn't in the configuration list
> 
> FYPO:0002929 is slightly more general. Would it be better to add that to the config?

ooh, yes, well spotted

**Comment by kimrutherford** [comment]
> Chado tracker (for logs)?

Yes please.

> ooh, yes, well spotted

OK, I'll add FYPO:0002929 and re-run.

**Comment by mah11** [comment]
https://github.com/pombase/pombase-chado/issues/641 now open for business

**Comment by kimrutherford** [comment]
> I'll add FYPO:0002929 and re-run.

I've done that.  The one annotation to "abnormal ascus development" will pop back in the preview next time I re-release.
