### ISSUE TITLE
Gagneur   PMID:26883383 dataset corrections

### ISSUE THREAD

**Issue by mah11** [pombase/website#50]
Minor corrections to "Gagneur" transcriptome data set:
- add PMID:26883383
- correct citation to "Eser et al. (2016)"

(everything else from Jira PB-2405 looks done)

**Comment by ValWood** [comment]
Is this renaming the files?
I can't  figure which dataset this is?

I know it's trancriptome but it isn't in the current browser.

**Comment by ValWood** [comment]
@Antonialock

**Comment by ValWood** [comment]
this can be closed and  or transferred to  file naming ticket once we know what the action is...

**Comment by Antonialock** [comment]
There is no dataset matching this in the file that was given to Kim.

This JIRA ticket talks about it:
https://www.ebi.ac.uk/panda/jira/browse/PB-2405?jql=project%20%3D%20PB%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22Gagneur%22%20ORDER%20BY%20priority%20DESC%2C%20updated%20DESC

and these RT tickets:
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=132678
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=132679
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=132697
https://helpdesk.ebi.ac.uk/Ticket/Display.html?id=132945

**Comment by Antonialock** [comment]
Jira ticket (in case you have problems accessing)


RT - https://rt.sanger.ac.uk/Ticket/Display.html?id=489146

Track Description - Data type: transcripts
Track Description - Method: Strand-specific RNASeq
Track Description - Sample: Exponential growth, rich glucose media, wild type
PubMed ID: 25634765
Data Format: text
Genome Assembly:
File Name: Eser_biorxiv025585_tableS1.txt
Accession:
Data Description:
!! The ID entered in PubmedID is from another paper just to get submission
going on. We only have a bioRxiv ID for now (025585)!!

Transcript boundary annotation accompanying the manuscript Eser, Wachutka et
al., "Determinants of RNA metabolism in the Schizosaccharomyces pombe
genome", http://dx.doi.org/10.1101/025585

Column annotations:

ID: transcript unit identifier. Due to upfront quality filtering, the
reported ID numbers do not cover all integers from 1 to 7056.

TU.class: one of "multicistronic": overlap multiple ORFs, "nc-TU": non-coding
Transcipt Unit, "novel nc-TU": novel non-coding Transcipt Unit, "ORF-TU":
Open Reading Frame-containing transcription unit.

chromosome, start, end, strand: genomic coordinates

map.ids: Pombase gene identifiers overlapping with the TU

n.map.ids: number of the map.ids.

n.introns, introns: number of introns, introns

UTR5.length, UTR3.length: UTR length

Pombase.mapping:
half.life: mature RNA half-life in minutes
splicing.time: half-splicing time in minutes
synthesis.time: synthesis time in minutes





COMMENTS:

there were 37 comments for this, some that seem key:

"

I suspect from the info in the submission above, that this raw data has been processed to provide high quality gene features rather than a plot. In this case it would be better to ask for a gff or gtf file to preserve the processing they have done to provide exact features. This will be useful to me for refining the UTRs (if it is good, we might use it directly but we need to see it aligned against all of the DEEP CAGE data)

Unfortunately our submission form allows "text" files. Maybe we should remove that option and ask people to contact the helpdesk for advice if they don't have any of the formats listed?"

"What is happening is that there is a GFF file with the mRNA, exons and introns. As a result in the genome browser the transcript box gets drawn and the exon/introns are getting drawn below, as a result it is looking like there are 2 or 3 tracks.

I had responded to this ticket:

https://rt.sanger.ac.uk/Ticket/Display.html?id=487101

But it should have gone here:

https://rt.sanger.ac.uk/SelfService/Update.html?id=514852

This is the current view of the attached GFF that I originally got from Leonard:

http://test.genomebrowser.pombase.org/Schizosaccharomyces_pombe/Share/a72dd60bfed72843cf642cfedb9e1a8932

If this is ok, then we can go ahead."

" I think this should go under "transcriptome" we can reserve the gene transcript tab for the eventual "curated" features

A Data type: transcripts
B Method: processed RNA-seq
C Track details: vegetative growth
D Strand reverse strand
E Citation pending

Is all the data included? This is supposed to cover all features, and some new ncRNA features.
"

"So to finalize this data we shouldn't show the introns. These are just inferred, and they clutter up the view so that you don't see some of the exons. I am uploading an example.....(called don't show introns.jpg)"

**Comment by ValWood** [comment]
that jira ticket has ~40 comments .....shudder

**Comment by ValWood** [comment]
@Antonialock  I removed "next" from this, but  when you next aren't busy (after the workshop?) this can be a high priority dataset to include in the browser... it might not be as complicated as it looks...

**Comment by Antonialock** [comment]
err, yeeah so...first step? Kim did you get any data that looks like it could be this?
@kimrutherford

**Comment by kimrutherford** [comment]
> Kim did you get any data that looks like it could be this?

I can't see it.  I looked for "Eser_biorxiv025585_tableS1.txt" and also for files with "Eser", "Gagneur", "PMID:26883383" or "26883383" in the file name.  Is there anything else I should try looking for?

**Comment by mah11** [comment]
I looked in the EG ftp upload directory where we had people submit data files. There is a "Gagneur" directory there. It is empty.

But then I looked in the scary place that is my email archive - and found that Julien sent the file as an attachment to a helpdesk email that I have stashed. Pack-rat tendencies fully vindicated, I attach it here.
[Eser_biorxiv025585_tableS1.txt](https://github.com/pombase/website/files/1915705/Eser_biorxiv025585_tableS1.txt)

**Comment by kimrutherford** [comment]
I'm not sure what to do with the file.  Can we chat about this sometime?

**Comment by Antonialock** [comment]
@ValWood

**Comment by mah11** [comment]
I've also now just found the bed file Mark loaded in the old browser. GitHub seems not to allow uploads with .bed extensions, so I've renamed it to add ".txt" just to get around that.

[Eser_biorxiv025585_tableS1.transcripts.bed.txt](https://github.com/pombase/website/files/2209516/Eser_biorxiv025585_tableS1.transcripts.bed.txt)

**Comment by ValWood** [comment]
So  what was the action item here?
@Antonialock  to contact Gagneur lab?
Or  do we have what we require now?

**Comment by kimrutherford** [comment]
> Or do we have what we require now?

I think we need a GFF file.

**Comment by ValWood** [comment]
We can discuss this ticket tomorrow too. 
I'm a little confused what is going on but this one  seems as good a place to start as baby and it's quite an important dataset.

**Comment by ValWood** [comment]
can we use the  BED  file here?

**Comment by kimrutherford** [comment]
> can we use the BED file here?

Yep.  I don't know why I said we'd need a GFF file.

The chromosome IDs in the file need tweaking, but that's a quick job.

**Comment by ValWood** [comment]
OK if you can get the files in place I can have a stab at the metadata using the spreadsheet.

**Comment by kimrutherford** [comment]
The BED file is now processed and ready to go.

**Comment by kimrutherford** [comment]
The last column in the spreadsheet ("source_url") should be:
https://www.pombase.org/external_datasets/Gagneur_PMID_26883383/Eser_biorxiv025585_tableS1.bed

**Comment by kimrutherford** [comment]
> The BED file is now processed and ready to go.

Turns out that it wasn't actually a BED file and I hadn't processed it properly anyway.  It was a TSV file but there were too many columns are they were in the wrong order.  Fixed now.

Here's the updated URL:
https://www.pombase.org/external_datasets/Gagneur_PMID_26883383/Eser_biorxiv025585_tableS1.sorted.bed.gz

**Comment by ValWood** [comment]
I added this line to the metadata config file:

Transcripts,yes,yes,"Transcript boundary annotation using min-length max-gap algorithm on binarized RNA seq - Eser et al. (2016)",,972h-,WT,,YES,,vegetative growth,,"RNA-seq",Eser,2016,PMID:26883383,,,,BED,https://www.pombase.org/external_datasets/Gagneur_PMID_26883383/Eser_biorxiv025585_tableS1.sorted.bed.gz

So this should be OK to go provided I didn't make a typo?

**Comment by ValWood** [comment]
Reading through this ticket I was a bit confused by the  section:

"TU.class: one of "multicistronic": overlap multiple ORFs, "nc-TU": non-coding
Transcipt Unit, "novel nc-TU": novel non-coding Transcipt Unit, "ORF-TU":
Open Reading Frame-containing transcription unit.

chromosome, start, end, strand: genomic coordinates

map.ids: Pombase gene identifiers overlapping with the TU

n.map.ids: number of the map.ids.

n.introns, introns: number of introns, introns

UTR5.length, UTR3.length: UTR length"

So I think somewhere along the line it must have been decided just to host TU's .
I guess with this we will only set starts and ends, and we won't be able to distinguish the ones they think are ORF or non ORF, but it is probably sufficient ,  especially since the paper does not mention any proposed changes to intron boundaries. 
I'm pretty sure this publication really only about the  non-coding component of the annotations  (UTRs and ncRNAs) and so the TUs will be sufficient

**Comment by kimrutherford** [comment]
> So this should be OK to go provided I didn't make a typo?

I added an extra comma before "BED".

**Comment by ValWood** [comment]
This transcript data looks very nice.
Can be announced with the next batch.

**Comment by ValWood** [comment]
In the future it might be nice to split this into a forward track and a reverse track, will make them easier to  evaluate.
 For now I will close this announcement required  is noted inhttps://github.com/pombase/website/issues/1441
