### ISSUE TITLE
advanced search documentation

### ISSUE THREAD

**Issue by mah11** [pombase/website#507]
Add page back, with new content, including screenshots.

Requires all the search tickets flagged for v2 release to be done. Then @mah11 will need input from the other curators @ValWood @Antonialock for the explanatory text.

**Comment by ValWood** [comment]
I don't think it needs much it's so simple?
Suggest:

The search is organised as a list of possible query types.
Select a query from the available types (described below).

description of Query types:

e.g Gene Ontology 
The Gene Ontology (GO) retrieves gene products annotated to a GO term and to any of its child terms, following the is_a, part_of, regulates, positively_regulates,and negatively_regulates relationships in the ontology. You may also find it helpful to search or browse in QuickGO or AmiGO to find GO terms of interest. If one search does not seem to retrieve as many results as you expect, try again using a less specific term. 
   •	GO ID
	•	GO Term Name

etc

Executed queries will appear in the query history until deleted.
You can combine queries  according to the Boolean operators OR(Union), AND(Intersect), Subtract(?) by selecting 2 or more queries from the history.

Access “Query results” from the “Count/results? https://github.com/pombase/website/issues/502” column. This column will show query value, “Results…” if the query value has changed since you previously executed (will do later https://github.com/pombase/website/issues/499)

Downloading Query results.
Query results can be configured downloaded from the query results page (screenshot)


----
@Antonialock ? any suggestions

@mah11  do you think it needs more?

**Comment by mah11** [comment]
Most of "which query gets what" can be recycled from old documentation. We don't have anything on how the new query setup interface works, especially for combining.

It's explaining how to do the query combinations using the history that needs to be expanded. I suspect I am not the only person to whom it is not intuitive at present (reverse Polish, argh!!), so it needs very explicit instructions.

**Comment by ValWood** [comment]
I don't understand, its the same as before? You just select the queries that you want to combine? (as above)

You don't really know what you wan to combine until you see the results anyway.
so then you add  another query in the usual way to  refining  the query,
and combine the output.

Anyone else understand what I am missing?
@Antonialock 
@kimrutherford

**Comment by kimrutherford** [comment]
Let's discuss on Thursday.

**Comment by Antonialock** [comment]
Just need to say that queries can be combined by ticking queries in the query history, and then selecting a boolean operator (OR(Union), AND(Intersect), Subtract). This will create a new query result.

**Comment by mah11** [comment]
There has been text to that effect all along. Since it was apparently too easy to miss, I have updated the screenshots (including new ones).

**Comment by ValWood** [comment]
I read the docs and it seems to describe the use so I'll close this. The docs will need tweaking when the  Not querying is fixed but that's all. We'll only need to make changes if we make changes in future more along the lines of the PubMed  search interface. We can consider this when we make additional changes like allowing users to name queries and the like...
