### ISSUE TITLE
retrieve UTRs without coding sequence

### ISSUE THREAD

**Issue by mah11** [pombase/website#542]
We've had a user ask about retrieving just the UTR sequences for a gene. They've said the colour highlighting (#541) was useful for this but maybe we should also offer the option of de-selecting the coding sequence if one UTR option is selected, so they just retrieve UTR sequence in the first place.

Is that (a) technically straightforward and (b) useful enough to do?

**Comment by kimrutherford** [comment]
> technically straightforward

Yep.  That's what is did initially so it would be an easy change.

**Comment by ValWood** [comment]
I think the colouring is  more generally useful so I'll make the colouring the HP ticket and this one 
can happen whenever...

**Comment by ValWood** [comment]
This is low priority with the colouring, but can be done whenever  if quick

**Comment by kimrutherford** [comment]
> This is low priority with the colouring, but can be done whenever if quick

It's quick if you don't mind an extra checkbox in the sequence section:

     [X] include exons

(Toggled on by default)

**Comment by kimrutherford** [comment]
I've made that change locally but I've just noticed that it works poorly with RNA genes (you can't add up or down-stream bases).  I'll check in the change once I fix that.

By the way, for protein coding genes should I change the label on the checkbox to?:

    [X] include coding exons

That seems more accurate since there are UTR exons?

I've also noticed that you can't get the sequence of a pseudogene at all and you can't in the main site either:
  https://www.pombase.org/gene/SPCC576.16c

It says:

    This gene has no transcripts available
 
No one has complained yet but I'd like to fix it.

**Comment by ValWood** [comment]
>No one has complained yet but I'd like to fix it.

I wouldn't worry about this yet. Some of the "predictions" for pseudo are a bit fanciful so the transcript may not exist, or be meaningless.
It might be better to provide nothing...
At least until https://github.com/pombase/curation/issues/21

**Comment by kimrutherford** [comment]
I've fixed the problem that was holding things up: you couldn't get the up and down stream sequence of RNA genes.  So the "Include exon" checkbox will be back tomorrow and so you'll be able to select just the UTR sequences again.

**Comment by kimrutherford** [comment]
> So the "Include exon" checkbox will be back tomorrow

It's actually there now.  I updated the site we new code and last night's data.
