### ISSUE TITLE
newsfeed tweak

### ISSUE THREAD

**Issue by ValWood** [pombase/website#551]
we would like to be able to have either :
i) a  flag 
or
ii) a way to separate old and new nes items
so that we can control precisely which ones appear on the front page. Sometimes we might only want to show one item, other times we might want a few.

**Comment by ValWood** [comment]
I think you did this Kim?

**Comment by kimrutherford** [comment]
> I think you did this Kim?

I haven't done that yet.  For now it is hard coded to show just the two most recent items.

**Comment by kimrutherford** [comment]
I went for option 1) because it's a bit like how we handle categories for the FAQ.

So you can now add a flag in a news item file to make it appear on the front page.  The flag looks like:

    

It can be anywhere in the file but I thought just after the title makes sense.  It's in a comment so it won't appear on screen.

So the "New PomBase" news item now looks like:

    ### New, improved PomBase goes live
    

    The new PomBase web site, which has been under development during 2017, has been released.
    The new site features:
    ...

And all the older news items don't have new flag.
