### ISSUE TITLE
make protein BLAST easier to find

### ISSUE THREAD

**Issue by mah11** [pombase/website#577]
It's already documented that you get protein BLAST on gene pages by ticking the "Show translation" box, and I can add a FAQ. But should we also add a tiny bit of text to the sequence section, so people don't have to hunt down documentation? (That might also make a FAQ superfluous.)

e.g. 'Select "Show translation" for protein BLAST'

prompted by helpdesk ticket 220198

**Comment by kimrutherford** [comment]
Sometimes a seemingly simple interface is too simple :-)

As well as a short help text, I think we can make the "Show translation" button stand out more.  For example we could set it apart more by putting more whitespace around it, particularly underneith so there is a bigger gap above "CDS sequence and: "

I think it might also stand out more if the sequence box on the right was level with "CDS sequence and: "

We could change the button text to something longer, like "Show protein sequence and tools"

Even more radically we could just have two sequence sections on the page: "Protein sequence and tools" and "Nucleotide sequence and tools".  Then it's unmissable (but less tidy).

**Comment by kimrutherford** [comment]
> Even more radically we could just have two sequence sections on the page: "Protein sequence and
> tools" and "Nucleotide sequence and tools". Then it's unmissable (but less tidy).

Having thought about it, I think this is a right solution.  It would be quite a short section because the protein sequence is short compared to the nucleotide sequence.  So it wouldn't make the page too much longer.

We could put "Protein sequence" as the section below "Protein features" on the page which would make it very easy to find.

**Comment by mah11** [comment]
I haven't got a problem with that.

**Comment by ValWood** [comment]
would the sequence be separated on the page? If so wouldn't that be  a bit odd?

(my personal preference would be to keep as is  but have protein sequence as default.....I can be persuaded otherwise I'm sure...we can discuss tomorrow.....)

**Comment by mah11** [comment]
We have decided to return to the original purpose of this ticket and hereby request:

Display all four BLAST buttons (NCBI BLASTN, Ensembl DNA; NCBI BLASTP; Ensembl protein) in the existing Sequence section, all the time, whether it's set to display DNA or protein sequence.

Leave anything and everything else about the sequence and protein feature sections for another time and another ticket.

**Comment by kimrutherford** [comment]
Do we need separate "Download protein sequence" and "Download DNA sequence" buttons too?

**Comment by kimrutherford** [comment]
> Display all four BLAST buttons

I've made that change.  A few things had to change behind the scenes so could someone test this on http://pombase-dev.bioinformatics.nz/ in the morning?


I'm still in favour of this change:

> We could put "Protein sequence" as the section below "Protein features" on the page which would
> make it very easy to find.

**Comment by ValWood** [comment]
OK, I think Antonia would prefer that too....I was against it because I thought it odd to have in 2 places, BUT I would prefer the protein as default which M. did not approve of....
So we ended up in a deadlock.

If everyone thinks it would be OK, we could move protein to protein features....but I do think that people might struggle even more to find it, at least initially.  The reason I think it might be  OK to move is that it seems the natural home for the protein sequence down the line when we have a  "protein viewer".

Express you preferences and reservations here....

**Comment by ValWood** [comment]
> Do we need separate "Download protein sequence" and "Download DNA sequence" buttons too?

I don't think so, but I'm not sure....

**Comment by kimrutherford** [comment]
> could someone test this on http://pombase-dev.bioinformatics.nz/ in the morning?

I forgot that and I've re-released.  Let me know if you see any problems.

**Comment by kimrutherford** [comment]
> If everyone thinks it would be OK, we could move protein to protein features....but I do think that
> people might struggle even more to find it,

I think it would be better as a separate "Protein sequence" section, maybe just under the protein features section.

**Comment by ValWood** [comment]
> I forgot that and I've re-released. Let me know if you see any problems.

Looks great....

**Comment by Antonialock** [comment]
I'm rolling a bit of blue sky thinking into this reply.

I would prefer a bit of re-organization in general. I think our left hand side menu is difficult to read, it is already very long. Therefore I don't think we should add another separate protein sequence section.

I think we should have fewer main sections, but subdivide them into short sections. For example, protein domains, protein sequence, protein modifications, could all be part of a general "protein" section (you can use the quick links to navigate to the top of the main section, or to sub-sections). 

I think this could work better because with the protein sequence by the modifications/domain you could have a selection to overlay that information over the protein sequence (like we allow highlighting introns etc)

In the separate nucleotide sequence section we could include information from the old "transcript" section (UTRs, maybe some features that we have talked about before, like ability to highlight restriction sites)

![screen shot 2017-11-10 at 13 57 38](https://user-images.githubusercontent.com/12727506/32661798-2f5a220c-c620-11e7-8fcc-3f8e467ffba6.png)

**Comment by Antonialock** [comment]
(just typed this up quickly to convey the idea, I didn't think a lot about the actual section names...e.g "Nucleotide sequence" could change to "Nucleotide", "protein features" to "protein" etc)

**Comment by ValWood** [comment]
hmm, that would make the menu go from 18 items to 26...some might be hidden....

**Comment by Antonialock** [comment]
yeah, but the compartmentalisation should make it easier to scan

**Comment by kimrutherford** [comment]
> but subdivide them into short sections

I like that idea!  Let's have a chat about it on Skype.

**Comment by ValWood** [comment]
@Antonialock  can you open a new ticket for the menu proposal.
