### ISSUE TITLE
blank page when clicking google result

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#603]
I found this URL in a google search but the page is blank:
https://www.pombase.org/about/pombe-mailing-list

Do we need to delete the page?
The menu item for the pombe mailing list goes straight to http://listserver.ebi.ac.uk/mailman/listinfo/pombelist now which is fine?

Can we check for blank pages floating around?

**Comment by kimrutherford** [comment]
Currently if a documentation page is missing it just shows the menu and a blank page.  That was an accident.  I'll fix that so it shows Sad Pombe instead.

Since there is no link to the page in the new pombase.org, Google will soon forget about that missing page.

Any link that looks like it's part of the documentation does the same thing as the link you found, eg.: https://www.pombase.org/about/any-old-missing-page

**Comment by ValWood** [comment]
closing?
