### ISSUE TITLE
delta

### ISSUE THREAD

**Issue by ValWood** [pombase/website#612]
mcm5delta::his3+ (deletion)

should get converted to 
mcm5Δ::his3+ ()

everywhere

**Comment by kimrutherford** [comment]
I've fixed that.  I'll close this issue when the change is in the main site.

**Comment by kimrutherford** [comment]
Is it OK for "delta-Poz1 binding site" to be changed to "Δ-Poz1 binding site"?

(SPBC1778.02 / rap1)

**Comment by ValWood** [comment]
I think either are ambiguous/cryptic, I wonder if the authors call it that?

we should probably fix to
poz1 binding site Δ    ?

**Comment by ValWood** [comment]
I fixed "delta-Poz1 binding site"

**Comment by mah11** [comment]
For the specific allele in question, the actual paper uses "∆Poz1-site" and "∆Pz"; they also have "∆Bqt1/2-site" and "∆Bq" for 341-370 deletion. I think the shorter versions would work fine as allele names (i.e. rap1-∆Pz and rap1-∆Bq).

(I would spell out "poz1 binding site _deletion_" rather than "... delta" or "... ∆", if I wanted an allele name to be that wordy in the first place. But I don't.)

More generally, I'm inclined to err on the side of converting "delta" to "∆" willy-nilly, and then addressing the few that will look a bit odd.

**Comment by ValWood** [comment]
changed names to match paper  ∆Pz  & ∆Bq
(I put  the other name in the short name field , even though it is longer. Why do we call this field "short name", I never really use it - why don't we  collect any  other name here?)

**Comment by ValWood** [comment]
> More generally, I'm inclined to err on the side of converting "delta" to "∆" willy-nilly, and then addressing the few that will look a bit odd.

agree

**Comment by mah11** [comment]
> I put the other name in the short name field

I fixed your fix ;) (you put Bqt1 in both instead of Poz1 in one).

> Why do we call this field "short name" ..?

We don't; the field is just labeled "name". It's for a _genotype_ name, which won't be connected with any individual allele in the database, even if the genotype only has one allele. Anything a user enters is likely to be shorter than the description for a multi-allele genotype, though.

**Comment by ValWood** [comment]
1. Oh christ!

2. It says "short name" in the box though?

**Comment by ValWood** [comment]
So I think we can close this?
