### ISSUE TITLE
Better message for publications with no annotations

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#627]
All annotation pages have the text "Annotations from this publication:" after the details, even if there are no annotations.  eg. https://www.pombase.org/reference/PMID:27677791

Change to something better like: "This publication has no annotations in PomBase because ..."

Reasons for no annotations:

 - not curatable
 - no annotations in the paper
 - not curated yet

anything else?

Note to self: we need to pass the "canto_triage_status" from Chado to the web code so the web code knows if the paper is Curatable.

**Comment by mah11** [comment]
If it has to "know" the triage status anyway, maybe the pub page should use a couple of them to indicate some of the reasons for no annotations. Specifically, I suggest 

- methods paper
- review

because each covers a fairly big chunk of the total uncuratable pubs (762 and 1126 respectively), and users might be interested in knowing if a particular paper is in one of those categories.

**Comment by ValWood** [comment]
I started to type the same somewhere in another window a while ago....but got side-tracked...

I think we should avoid "not curatable"

For papers which are identified as "curatable" but not yet curated we should   have a message 
that the paper has not yet been curated....

**Comment by mah11** [comment]
Yeah, different words will sound nicer than "not curatable". But I'm inclined to lump most of the subtypes of "uncuratable publications" rather than list every triage category.

Message ideas:

This publication has no annotations in PomBase because ...

- it is a review.
- it is a methods paper.
- curators have found no annotatable gene-specific data in it.
- it hasn't been curated yet. (Please [contact us](mailto:helpdesk@pombase.org) if you want to contribute annotations for this paper.)

**Comment by kimrutherford** [comment]
> Note to self: we need to pass the "canto_triage_status" from Chado to the web code so the web
> code knows if the paper is Curatable.

I've done that now so any changes to the messages on the publication papers should be straight forward.

**Comment by mah11** [comment]
Notes from call:

- ignore untriaged pubs; they don't even get a page
- _any_ annotation (Canto, tab-delimited files, contig files, etc.) takes precedence over the "no annotations" options
- "it hasn't been curated yet" = anything triaged curatable, but without approved session
- "... found no annotatable ..." = (uncuratable BUT NOT (review OR methods)) AND (approved session with no annotations)

**Comment by ValWood** [comment]
super ;)

**Comment by kimrutherford** [comment]
> ignore untriaged pubs; they don't even get a page

Currently untriaged publication do get pages on the main site.  I'll fix that.

**Comment by kimrutherford** [comment]
> Currently untriaged publication do get pages on the main site. I'll fix that.

I've fixed that for tomorrow night's load.

While testing, I found a publication in Chado that doesn't appear to have been through Canto:
https://www.pombase.org/reference/PMID:17287513
It also doesn't seem to be a pombe paper.  Very odd.  I'll investigate how it ended up in Chado.

**Comment by ValWood** [comment]
presumably a typo
chromosome1.contig:FT                   valproic acid; db_xref=PMID:17287513; date=20100917"
chromosome1.contig:FT                   valproic acid; db_xref=PMID:17287513; date=20100917"
chromosome2.contig:FT                   valproic acid; db_xref=PMID:17287513; date=20100917"

**Comment by kimrutherford** [comment]
> presumably a typo
> chromosome1.contig:FT valproic acid; db_xref=PMID:17287513; date=20100917"

PMID:17287531 is in Chado too and also has some annotation for apm1.

**Comment by ValWood** [comment]
Valproic acid affects membrane trafficking and cell-wall integrity in fission yeast.
Miyatake M, Kuno T, Kita A, Katsura K, Takegawa K, Uno S, Nabata T, Sugiura R.
Genetics. 2007 Apr;175(4):1695-705. Epub 2007 Feb 7.
PMID: 17287531 

will fix

**Comment by kimrutherford** [comment]
The publication pages now show sensible messages when there is no annotation.
