### ISSUE TITLE
Reinstate link to Blast

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#631]
user request:
"in the previous version of Pombase, there was a Blast button in the "tools" section that allowed us
to search the pombe genome/proteome with any query."

I think Jonasthan asked for this too previously..?

**Comment by ValWood** [comment]
it's the only  thing people really miss in the PI survey....
It   is just the ability to blast directly against the pombe genome/proteome that they miss the convenience of.
I think we will need to add it back, but since they can do it  elsewhere, just by selecting the organism, it won't be at the top of the list.

**Comment by ValWood** [comment]
for now add  link to
https://fungi.ensembl.org/Schizosaccharomyces_pombe/Tools/Blast?db=core
from "search" tab
to make people happy.....
We'll give them (EBI) that one!

**Comment by kimrutherford** [comment]
What should we use for the label?  "S. pombe BLAST at Ensembl"?

**Comment by ValWood** [comment]
"BLAST at Ensembl" is okay, they find out it's pombe

**Comment by kimrutherford** [comment]
> "BLAST at Ensembl" is okay, they find out it's pombe

That's there now.
