### ISSUE TITLE
unexpected phenotype displayed

### ISSUE THREAD

**Issue by ValWood** [pombase/website#644]
cwf12 is in the list for
"abnormal ascus morphology "
but I can't see a phenotype related to this term.

This might be to do with incorrect display related to has_part 
But I can't even see a term here that would cause this via has_part ?

We should discuss Tues, but  @mah11  if you know the issue holler...

**Comment by Antonialock** [comment]
It is because annotations from PMID:28410370 aren't showing? I don't get why

**Comment by ValWood** [comment]
I don't see cwf1 iin that session, is it in a PHAF?
curs/5724d1814ea9f342/ro

**Comment by Antonialock** [comment]
yes

**Comment by Antonialock** [comment]
I think the phenotype is missing
is_a: FYPO:0003037 ! abnormal cell phenotype

**Comment by Antonialock** [comment]
Maybe it is a cell population phenotype seeing you have 4 spore cells within one ascus...
i.e.
is_a: FYPO:0000003 ! cell population phenotype

**Comment by Antonialock** [comment]
weirdly abnormal ascus morphology isn't showing in bioportal...

<img width="302" alt="screen shot 2017-12-15 at 09 49 35" src="https://user-images.githubusercontent.com/12727506/34036512-5836059c-e17d-11e7-95ba-75e33ac02787.png">

**Comment by mah11** [comment]
> weirdly abnormal ascus morphology isn't showing in bioportal...

That appears to be unrelated to our problem; it's because BioPortal has a way-out-of-date version of FYPO. I think that's my fault - I forgot to update the source link at OBO Foundry when we switched to GitHub. I have now sent a pull request, so let's see if the change percolates through to BioPortal. If it doesn't I'll pester them separately.

**Comment by mah11** [comment]
> I think the phenotype is missing
> is_a: FYPO:0003037 ! abnormal cell phenotype
> 
> Maybe it is a cell population phenotype seeing you have 4 spore cells within one ascus...

No, an ascus is neither a cell nor a cell population. It's a very small anatomical structure consisting of 4 cells (the spores) and the stuff (ascoplasm and wall) around them. A phenotype that affects a whole ascus is therefore neither a cell phenotype nor a population phenotype. The terms are directly, and only, is_a: FYPO:0001985 ! abnormal phenotype because pombe doesn't have enough other multicellular anatomical structures to make it worth adding another grouping term.

That doesn't look like the problem anyway, because annotations are showing up as expected for some other terms that only have is_a FYPO:0001985, e.g. FYPO:0000150 ! abnormal colony morphology or FYPO:0000680 ! abnormal ascus development.

It's also not a problem with the whole PMID:28410370 PHAF, because other annotations from that paper are showing up, e.g. FYPO:0006010.

I am stumped.

**Comment by ValWood** [comment]
It's probably because we are only displaying population phenotypes and cell phenotypes and it falls outside both of these so it doesn't make it onto the gene pages (although you can query for it....)

**Comment by mah11** [comment]
It can't be as simple as that - we display all the molecular function phenotypes, and they're neither cell nor population. It must be a configuration thing.

**Comment by mah11** [comment]
Found it! and added FYPO:0005156 so it'll behave the same way as MF phenotypes, i.e. get lumped in with cell phenotypes, next time the site gets updated.

**Comment by Antonialock** [comment]
super!

**Comment by mah11** [comment]
tangent, but: I've emailed BioPortal ...
