### ISSUE TITLE
Don't make  dev-live ontol GO ontology issue fixed:

### ISSUE THREAD

**Issue by ValWood** [pombase/website#648]
We have a few drops in numbers for the slim,  and a number of genes are not mapping to slim terms.
I'm not sure if this is a GO  issue, or a problem at our end will dig around...

**Comment by ValWood** [comment]
1. Increase in number of gene not mapping to the slim
http://pombase-dev.bioinformatics.nz/gene_subset/non_go_slim_with_bp_annotation

2. examples  
bqt1 has
http://pombase-dev.bioinformatics.nz/term/GO:0032121
Should map to "meiotic nuclear division" which is one of our slim terms

dad1 has
mitotic sister chromatid biorientation
should map to
GO:0000070    mitotic sister chromatid segregation

3. Numbers have also dropped for
ascospore formation and some other terms

Even relatively stable numbers have changed, DNA replication has dropped from 119 to 112, and that hardly ever changes...

**Comment by ValWood** [comment]
these are the ones which no longer slim to DNA replication
cdc17 | SPAC20G8.01 | ATP-dependent DNA replication ligase Cdc17
cdc24 | SPAC8F11.07c | DNA replication protein Cdc24
cds1 | SPCC18B5.11c | replication checkpoint kinase Cds1
fml2 | SPAC20H4.04 | ATP-dependent 3' to 5' DNA helicase (predicted)
mcl1 | SPAPB1E7.02c | DNA polymerase alpha accessory factor Mcl1
mgs1 | SPAC26H5.02c | DNA replication ATPase Mgs1 (predicted)
rif1 | SPAC6F6.17 | telomere length regulator protein Rif1

but they are annotated to a term which is part of DNA replication:

http://pombase-dev.bioinformatics.nz/term/GO:1903461

but then they do not appear in this list:
http://pombase-dev.bioinformatics.nz/term_genes/GO:0006260

Oliver zero knock on issue?

**Comment by ValWood** [comment]
There is definitely a drop in numbers:

At GO
42012 (38116 non-IEA) | 09/15/2017
-- | --

In gaf
 40545

**Comment by ValWood** [comment]
my theory that it was the oliver zero failure 
is incorrect.... fro 3rd Jan.... will look back further...

cat pombase-build-2018-01-03.gaf  |wc
   40533

**Comment by ValWood** [comment]
The number drop occurred sometime between the 11th and the 25th.... any idea what could be the cause anyone?
I'm not even sure it its one issue or two...as the annotations missing from the slim appear to be on the gene pages?????

$ cat pombase-build-2017-12-11.gaf  |wc
   42145  704601 6528151
$ cat pombase-build-2017-12-25\ \(1\).gaf  |wc
   40479  677749 6240011

**Comment by kimrutherford** [comment]
The drop in annotations happened between the 14th and 15th:

    pombase-build-2017-12-14 42131
    pombase-build-2017-12-15 40474

The majority of the missing annotations are for just these 5 genes:

SPAC19B12.10    sst2
SPBC1703.12     ubp9
SPBC18H10.08c   ubp4
SPBC713.02c     ubp15
SPCC188.08c     ubp5 

The missing annotation for those five genes all have a has_direct_input extension.

Here is the full diff:
  https://www.dropbox.com/s/3wcgiqh7m764ovm/gaf-diffs-2017-12-14-2017-12-15.txt?dl=0

Any guesses as to what the problem is?  There aren't any SVN changes around that time.

I'll check to see if there are any GO changes around the 14th that could explain the differences.

**Comment by mah11** [comment]
Thanks, Kim - that gave me enough clues that I think I've got it.

Take-home tl;dr message: make the Chado loader use all of the GAFs in the pombe-embl/external_data/external-go-data/ directory (match PMID*gaf.tsv should do it, analogous to how it loads PHAFs).


Long-winded explanation: The big drop has been caused by a malign interaction between GO's new HTP evidence codes, Canto, and external GAF loading (or not).

GO added some new evidence codes for high-throughput data recently (GO saga in https://github.com/geneontology/go-annotation/issues/1655, but that's a scary place). In https://github.com/pombase/pombase-chado/issues/646 Kim made Chado play nice with them, so in https://github.com/pombase/curation/issues/1767 Val and I set about deploying them.

BUT ... the three papers I did were curated in Canto, and the HTP codes aren't available there. That's probably a good idea, since it would be kind of a pain to enter an HTP-scale load of annotations in Canto anyway. It did mean I had to create three new GAFs to house the annotations that got switched to new codes, though.

I didn't realize that those new GAFs wouldn't get loaded automagically, but indeed they aren't - the gaf-load-output logs (e.g. https://curation.pombase.org/dumps/latest_build/logs/log.2018-01-09-21-29-32.gaf-load-output) have "reading PMID_27984725_gaf.tsv" but no other "reading PMID_*_gaf.tsv" messages. The three unloaded files are

    PMID_20838651_gaf.tsv
    PMID_22146723_gaf.tsv
    PMID_26412298_gaf.tsv

and between them they hold 1696 annotation lines.

**Comment by ValWood** [comment]
Phew well trouble-shot!

**Comment by mah11** [comment]
I've opened https://github.com/pombase/pombase-chado/issues/656 for it.

**Comment by ValWood** [comment]
Slim issue is fixed on dev :)

**Comment by ValWood** [comment]
but the GO number is still low:

pombase-build-2018-01-09\ \(2\).gaf  |sort |wc
   40539

**Comment by kimrutherford** [comment]
The nightly load failed because I made a typo when I tried to fix pombase/pombase-chado#656

I've fixed the typo.

**Comment by kimrutherford** [comment]
The GAF numbers look much better after last night's load: 

pombase-build-2017-12-14.gaf  42131
pombase-build-2018-01-09.gaf  40539
pombase-build-2018-01-11.gaf  42222

I've just updated the main site.

**Comment by ValWood** [comment]
great, thanks!

**Comment by kimrutherford** [comment]
Does the main site look OK?  Can we close this?

**Comment by ValWood** [comment]
i thinks so, slim is fine and gaf is fine.

val
