### ISSUE TITLE
Add a one sentence description or title for each query type

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#657]
I think most of the query types are quite simple but I think it would be more friendly to have a one sentence title or description above each type.  For example the "Coding exons" type could have something as simple as "Find genes by number of coding exons:"

![query-builder-exons-2018-01-22](https://user-images.githubusercontent.com/90474/35200055-251da608-ff6c-11e7-8b49-35572b20ec90.png)

**Comment by kimrutherford** [comment]
I'm happy to have a go at making some titles that we use as a starting point.  But here's the list of types in case anyone feels like trying:

 - GO
 - phenotype
 - protein modification
 - protein domain
 - protein feature
 - disease
 - product type
 - taxonomic conservation
 - characterisation status
 - Canned queries
 - protein mol. weight
 - protein length
 - Number of TM domains
 - Coding exons
 - Genome location
 - Gene IDs

**Comment by ValWood** [comment]
I have been thinking recently it would be useful to have canned queries separately near the top:
(and the gene ID list)

Canned Queries

Find genes by
Gene ID list
GO term or ID
Phenotype term or ID
Protein modification
Protein domain 
Protein feature
Protein length
Protein MW
Disease
Product type
Number of TM domains
Taxonomic conservation
Chromosome or region
Number of coding exons
Characterization status

**Comment by ValWood** [comment]
@mah11 @Antonialock 
any issues with my proposal,  please suggest any revisions.

**Comment by mah11** [comment]
I can't quite shake a sense that over-thinking is happening, but since you asked ...

- It feels odd to me to put canned queries first, although it is odder still to have them plunked in the middle. It does make sense to separate them from the rest somewhat. My gut reaction would have been to put them last, since they'll stand out a bit anyway if they get something of a separate section.

- Apart from that, I don't think we should change the query order frequently, or without careful consideration. So,

- Have we received complaints or questions about the current order, or suggestions for changing it, from users? Or,

- Do we have data on how frequently the various query types are used? If so, that should guide any changes (most frequently used at the top). If not, we don't really have a case for changing anything other than canned query placement yet.

**Comment by Antonialock** [comment]
I don't think it is odd to have canned queries first (likely to be used a lot?)

By the way, I think it would be nice to have a link to the documentation (https://www.pombase.org/documentation/advanced-search).

**Comment by ValWood** [comment]
OK canned queries last. It seems that some of the canned queried might be things people look for often (like the protein set, which they probably don't know how to make easily), butlast is fine.

The gene list is also one of the most popular and people reported that could not find it easily (before we added the menu back)  although some reported that they found it by chance. I though it would therefore be better at the top so that everyone sees it straight off, because it gets a bit lost in the list (if you hadn't spotted it in the menu bar).

It seemed sensible to put the "protein features" together, and put the queries that  are not used so often, at least by the community (exon, chromosome location, characterization status)
at the bottom.

So I just thought this was slightly more logical ordering for the users.

**Comment by ValWood** [comment]
So although I don't have empirical data I know from over the years  which ones people don't use frequently and which ones they do.
The 4 at the bottom are the least used  by far (along with protein feature, but it would be odd to move that out of the protein section).

**Comment by ValWood** [comment]
Re the canned queries, I routinely use these myself now for protein coding genes (it saves doing protein coding -dubious-transposon.

I think the canned queries would be good at the top and it should contain  all the most common queries.

The general things I used to be asked most often (before the FAQ) are:

protein coding
disease associated
conserved in cerevisiae
conserved in human (it might be good to make this as it  the proxy is "conserved in vertebrate" which might not be obvious)
conserved in human but absent from cerevisiae
viable and inviable deletion (population)
unknown

although mainly single queries  it takes some knowledge to figure out how to do them initially....

**Comment by ValWood** [comment]
I'll have a stab at this now...

**Comment by ValWood** [comment]
- Canned queries
Canned queries (rename to commonly used queries)?

 - GO
Retrieve gene products (protein and ncRNA) by molecular function (activity), biological process, complex, or location using PomBase Gene Ontology annotation (all evidence codes)

 - phenotype
Retrieve gene product (protein and ncRNA) phenotypes assigned by PomBase  using the Fission Yeast Phenotype Ontology (FYPO) . 

 - protein modification
Retrieve gene product protein modification using the Protein Ontology (PRO)

 - protein domain
Retrieve  proteins with specific domains using InterPro or Pfam identifiers
Use IPR*  or PF* for all domain containing proteins

 - protein feature
Search protein features (e.g. NLS, destruction box) assigned by PomBase  using the protein sequence feature branch of Sequence Ontology (SO)

 - disease
Retrieve gene products where the curated human ortholog is associated with a specific disease, or any disease (ID)

 - product type
Retrieve genes products by “product type”. Note that for protein dubious and transposons are included. You can retrieve the subset without these  from the “common queries” link above.

 - taxonomic conservation
Retrieve  protein coding gene products lists based on broad taxonomic conservation, or absence from S. cerevisiae.

 - characterisation status
Retrieve genes based on characterisation status (described here >https://www.pombase.org/status/gene-characterisation)

 - protein mol. weight
 - protein length
 - Number of TM domains
 - Coding exons

 - Genome location
Retrieve gene products in region.
 
- Gene IDs

**Comment by ValWood** [comment]
Also in my preferred order, based on most  commonly used at the top

**Comment by ValWood** [comment]
Tweaked. Please suggest edits.

**Comment by ValWood** [comment]
Also any specific search tips for these queries.

**Comment by ValWood** [comment]
- [ ]  change order of queries to reflect common usage (especially "canned queries" at the top
and "gene list ID search" second (because it get's a bit buried)
- [ ]  change  the descriptions.....BUT my descriptions most likely need refining... @mah11 ?

**Comment by mah11** [comment]
Where are these text descriptions intended to appear? Several of them look too long to have showing all the time, but would (with editing) be fine as tooltips to appear in mouseovers or in little (i) popups. So how I edit them depends on how they'll be used.

**Comment by ValWood** [comment]
I envisage that they would show here when you selected a type, as there is usually quite a lot of space...

![type](https://user-images.githubusercontent.com/7359272/39433906-fb203fbc-4c8e-11e8-8cef-04bd274cf5d1.jpg)

**Comment by mah11** [comment]
by 'here' you mean what? the space underneath the text box?

**Comment by mah11** [comment]
or should it go above the box/boxes/pulldowns/etc.?

**Comment by ValWood** [comment]
Yes. But wait to see if Kim envisaged something else...
There is usually plenty of room (A bit less for phenotypes but still plenty)

**Comment by ValWood** [comment]
Maybe aov the box would be better,

So 
new blurb

existing BOX

any existing text.

**Comment by kimrutherford** [comment]
> Maybe above the box would be better,

Yep.  I think a short sentence at the top (above the input box) would be best.

**Comment by mah11** [comment]
Some thoughts on the query list entries ...

> Canned queries (rename to commonly used queries)?

Yes, I like "Commonly used queries"

> Gene ID list search

For this one I suggest keeping "Gene IDs" as the short name, and adding a text description.

> coding exons

This should be changed, e.g. to "number of exons", because it searches spliced ncRNA genes as well as protein-coding genes.

**Comment by mah11** [comment]
Suggestions for text to appear on top when one is selected:

- Gene IDs
Enter or upload a list of systematic gene IDs

- GO
Retrieve genes via annotated Gene Ontology terms that describe the activity, process, or location of their products (protein or ncRNA)

- phenotype
Retrieve genes based on phenotypes of mutations annotated using Fission Yeast Phenotype Ontology (FYPO) terms

- product type
Retrieve genes based on product type. Note that "protein" includes dubious and transposon protein-coding genes; there is a prepared query that excludes both in the list of commonly used queries.

- protein modification
Retrieve protein-coding genes based on modifications annotated using PSI-MOD ontology terms

- protein domain
Retrieve protein-coding genes by specific domains present in the products. To retrieve all domain-containing proteins, search for 'IPR*' or 'PF*'.

- protein feature
Retrieve protein-coding genes based on features annotated using the protein sequence feature branch of the Sequence Ontology (SO)

- protein length
Retrieve protein-coding genes by product length (in amino acids)

- protein mol. weight
Retrieve protein-coding genes by product molecular weight

- disease
Retrieve genes for which the curated human ortholog is associated with a disease. To find all disease gene orthologs, search for "disease_associated".

- number of TM domains
Retrieve protein-coding genes by number of predicted transmembrane domains in the product

- genome location
Retrieve genes in a specified region of a chromosome

- number of exons
Retrieve genes by number of exons

- taxonomic conservation
Retrieve protein-coding genes based on broad categories of taxonomic conservation

- characterisation status
Retrieve protein-coding genes based on characterisation status
(hyperlink "characterisation status" rather than add more text)


... I don't love the GO one but we could run with it if no one comes up with anything better

**Comment by kimrutherford** [comment]
> (hyperlink "characterisation status" rather than add more text)

What should it link to?

**Comment by kimrutherford** [comment]
> "Commonly used queries"

I've changed the name.  We need a description text for above the list.  I put in "Shortcuts for commonly used queries" as a place holder while we decide.

> This should be changed, e.g. to "number of exons",

I've changed that.

> Also in my preferred order, based on most commonly used at the top

I've put the list in that order.  Let me know if you need any changes.

I've updated the text and screenshot in documentation: https://www.pombase.org/documentation/advanced-search

**Comment by mah11** [comment]
>> (hyperlink "characterisation status" rather than add more text)
> 
> What should it link to?

https://www.pombase.org/status/gene-characterisation

**Comment by ValWood** [comment]
yep (I think thats the only place we describe the status?)

**Comment by kimrutherford** [comment]
Thanks, "characterisation status" is now a link.
