### ISSUE TITLE
difference in search and term page

### ISSUE THREAD

**Issue by ValWood** [pombase/website#675]
from
https://github.com/pombase/fypo/issues/3214#issuecomment-362555484

 multinucleate vegetative cell are all abnormal cytokinesis

(is a cytokinesis failure) so should  be retrieved by a search on  "abnormal cytokinesis"

according to this it should be:
https://github.com/pombase/fypo/issues/3214#issuecomment-362555484

> (mah) They do show up on the term page for abnormal cytokinesis. If the search doesn't find the same genes, that seems like a question for Kim about search behavior.

>val
I don't see
elongated multinucleate multiseptate vegetative cell, single septa between nuclei
on the abnormal cytokinesis page, but I do see

elongated multinucleate multiseptate vegetative cell, irregular septum position
inviable elongated multiseptate vegetative cell with fragmented DNA

> mah
Hmm. I looked specifically for FYPO:0000118 'multiseptate vegetative cell' when I last commented. It's odd, though, and definitely one for Kim to look at, because FYPO:0000133 'elongated multinucleate vegetative cell' appears on that page, and FYPO:0001253 is_a FYPO:0000133. I therefore don't understand why FYPO:0001253 wouldn't be on the FYPO:0000032 page if FYPO:0000133 is.

**Comment by ValWood** [comment]
this is the search that alerted me 

![alert](https://user-images.githubusercontent.com/7359272/36040489-7f092eee-0dbd-11e8-96d0-0dd0c7908738.jpg)


we may need to discuss

**Comment by kimrutherford** [comment]
> I don't see
> elongated multinucleate multiseptate vegetative cell, single septa between nuclei
> on the abnormal cytokinesis page

I'm not following - I do see that term (FYPO:0001253) here: https://www.pombase.org/term/FYPO:0000032

What am I missing?

**Comment by ValWood** [comment]
OK. ignore that. 
This is my problem. All "multiseptate vegetative cell" phenotypes are "abnormal cytokinesis"

but if I do a query on "abnormal cytokinesis" only 90 of the 114 "multiseptate" phenotypes  are annotated to it.
Maybe we were looking at the wrong thing. @mah11  could you double check  and let us know how "multiseptate vegetative cell" is related to "abnormal cytokinesis" in FYPO?

**Comment by kimrutherford** [comment]
> ... how "multiseptate vegetative cell" is related to "abnormal cytokinesis" in FYPO?

FYPO:0000118 "multiseptate vegetative cell"
output_of 
FYPO:0000032 "abnormal cytokinesis"

**Comment by ValWood** [comment]
OK, so don't we follow "output of" for searching (Sorry I still get confused about which links we follow for phenotype searching)

**Comment by kimrutherford** [comment]
> OK, so don't we follow "output of" for searching

We do follow output_of for phenotypes.  Which is why the FYPO:0000118 "multiseptate vegetative cell" annotations appear here: https://www.pombase.org/term/FYPO:0000032

I'm struggling with this but I think I have an idea.  The results you see might be because there are descendant(*) terms of "multiseptate vegetative cell" that aren't descendant(*) terms of "abnormal cytokinesis".  For example adn3 is annotated with "multinucleate multiseptate vegetative cell" which is related to "multiseptate vegetative cell" by has_part so those annotations appear on the "multiseptate vegetative cell" term page and in queries for "multiseptate vegetative cell".  But the "multinucleate multiseptate vegetative cell" annotations won't appear in queries for "abnormal cytokinesis" or on the "abnormal cytokinesis" term page.

(*) I'm sure that isn't the right terminology

So:
 - "multiseptate vegetative cell" output_of "abnormal cytokinesis"
 - and "multiseptate vegetative cell" has_part "multinucleate multiseptate vegetative cell" 
 - but according to OWLTools "multinucleate multiseptate vegetative cell" isn't related to "abnormal cytokinesis" .

To add to the confusion, the term parents links aren't always shown on the term page: https://github.com/pombase/website/issues/193#issuecomment-282911396
We only show "is_a", "part_of" and "regulates" parents.  We can change that if it helps.

**Comment by ValWood** [comment]
I still need to process this!

**Comment by ValWood** [comment]
I need to look at this, it is still sitting in my inbox, I'll get to it soon....

**Comment by ValWood** [comment]
I think this *might* fix it
https://github.com/pombase/fypo/issues/3408

**Comment by ValWood** [comment]
I thought we did follow has_part. Maybe we only do it in Canto...I get confused...

**Comment by kimrutherford** [comment]
> I thought we did follow has_part.

We do follow has_part and output_of.  Here's the complete list:

 -   is_a
 -   part_of
 -   regulates
 -   positively_regulates
 -   negatively_regulates
 -   has_part                                                                                                                                                                                  
 -   output_of

> An actual fix would be to make the term page setup clever enough to follow both of these steps

I don't know of an easy way to do that.  We use OWLTools to calculate the transitive closure that the site uses and it doesn't follow has_part+output_of as a combination.

**Comment by mah11** [comment]
from 24 Jan call: I'll email Nico, DavidOS, Chris for their thoughts on this
(has anyone run into this before? if so, what do they do?)

we don't have to do anything until we hear something back

**Comment by ValWood** [comment]
I re- ran the query and this is no longer an issue:



  | 139 | abnormal cytokinesis (FYPO:0000032) [single allele genotypes] AND multiseptate vegetative cell (FYPO:0000118) [single allele genotypes] [details] | ...
  | 437 | abnormal cytokinesis (FYPO:0000032) [single allele genotypes] | ...
  | 139 | multiseptate vegetative cell (FYPO:0000118) [single allele genotypes]
