### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by ValWood** [pombase/website#686]
which page on the pombase site causes this "hit"
(I can't figure it out)

https://analytics.google.com/analytics/web/#report/content-pages/a98997285w156805306p158341248/%3F_u.date00%3D20171001%26_u.date01%3D20180215%26explorer-graphOptions.selected%3Danalytics.nthMonth%26explorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.pagePath%3A%2Fsearch%2Fensembl/

**Comment by kimrutherford** [comment]
I think those hits are coming from external sites and search engines that still have the old URLs for gene page.  I made an alias (/search/ensembl/) when we changed to PomBase V1 so that those old links would still work.  There are no internal links to those URLs.

The link below should show the sources, or choose "Secondary dimension"->"Acquisition"->"Source".  Some say "(direct)" which I think probably means there are some users with bookmarks with the old links.

https://analytics.google.com/analytics/web/#report/content-pages/a98997285w156805306p158341248/%3F_u.date00%3D20171001%26_u.date01%3D20180215%26explorer-graphOptions.selected%3Danalytics.nthMonth%26explorer-table.plotKeys%3D%5B%5D%26explorer-table.secSegmentId%3Danalytics.source%26explorer-table.rowStart%3D0%26explorer-table.rowCount%3D5000%26_r.drilldown%3Danalytics.pagePath%3A%2Fsearch%2Fensembl/

**Comment by ValWood** [comment]
OK, just curious!
