### ISSUE TITLE
JBrowse config file

### ISSUE THREAD

**Issue by ValWood** [pombase/website#691]
useful links
config current location Dropbox/pombase/PomBase_website/ensembl_track_config.tsv
https://www.pombase.org/jbrowse/index.html
https://browse.yeastgenome.org
old spreadsheet I started before Kim auto-generated the config file https://docs.google.com/spreadsheets/d/13STLSIvYcqKVaFxz_g3XKOkd-huwbu8qrdQWn9jVN8w/edit#gid=0

- [x]  copy config file  to subversion
- [x]  Rename source_name old_source_name
- [x]  Add and populate display name
- [x] split out "assay type" into a separate column - DamID / tiling array -
Kim will do as much as possible with perl

**Comment by ValWood** [comment]
- [ ]  Data type? (chromatin binding etc)
 - [ ]  Description  (display name) shortened version
 - [ ]  Experiment type (Chip- seq etc)
 - [ ]

**Comment by ValWood** [comment]
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM882083

**Comment by ValWood** [comment]
Later
- [ ]  individual track IDs and names (as published in repository)

**Comment by ValWood** [comment]
- [ ] Once we  have the tracks hosted Antonia can mail the authors to check that we are displaying correctly 
Sometimes we might not want to show every dataset (controls?)

- [ ]  Note that the Wilhelm dataset has not been displayed recently so in theory this is the only one which wasn't tested.

**Comment by kimrutherford** [comment]
Here's the first try:
  https://www.pombase.org/jbrowse/index.html?loc=I%3A1..286778&tracks=PomBase%20features&highlight=

If you see the old track list, the old track configuration might be cached in your browser.  In that case, try shift-reload or try pombase-dev:
  http://pombase-dev.bioinformatics.nz/jbrowse/index.html?loc=I%3A1..286794&tracks=PomBase%20features&highlight=

This is just a first attempt.  I wanted to make sure I knew how to configure things.  Problems I've noticed now it's deployed:
 - [ ] missing publication date in the track table
 - [ ] the groups on the left in the track table are ordered alphabetically

Let me know anything else you see.

> copy config file to subversion

The file is: pombe-embl/website/pombase_jbrowse_track_metadata.csv

It's not quite ready to be edited because I'm going to overwrite it.

> Note that the Wilhelm dataset has not been displayed recently so in theory this is the only one which wasn't tested.

I'm going to add all those tracks to the table in SVN, but not show them in JBrowse.  Then at least they'll be in the file and they can be added to JBrowse as needed.

**Comment by ValWood** [comment]
Looking good so far.
Let us know when you are ready to tweak the file....

- [ ] strand specificity, some tracks are strand specific. PolyA data for example has forward and reverse strand for each dataset. This needs to be in the eventual  file description?

**Comment by kimrutherford** [comment]
> missing publication date in the track table

With this morning's update, that's fixed.

**Comment by Antonialock** [comment]
check for missing tracks

**Comment by ValWood** [comment]
1. Check all datasets are there
2. Add data to column to populate table (publication titles, missing UDs etc)

**Comment by kimrutherford** [comment]
Sorry, I haven't yet done the work on the JBrowse config that I said I would.  

Some of the data URLs contain the sample ID as well as the project/study ID.  On Monday I'll pull those sample IDs out into a separate column as they might be useful.
eg. https://www.pombase.org/external_datasets/ERP001075/ERS078444.bw

There are also some rows missing from the CSV file because they are commented out of the Ensembl config.  I'll include all those in the CSV file on Monday, but I'll add a column with a flag that shows which datasets were commented out.  Most of the missing data is from the Wilhelm (2008) paper.

**Comment by kimrutherford** [comment]
> but I'll add a column with a flag that shows which datasets were commented out.

I've added all the datasets to pombase-embl/website/pombase_jbrowse_track_metadata.csv

I've added a column called "display_in_jbrowse" to control which datasets should be visible in JBrowse.  Only rows with "yes" in that column will be displayed.

> I'll pull those sample IDs out into a separate column as they might be useful.

That's done now.  I've added an "extra_db_id" column.  The IDs in that columns mostly look like sample IDs.  The column name is the first thing that came into my head.  Please rename it if that makes sense, or add new columns to the file.

At the moment all of the columns from the config file appear in the "About track" dialog.  Some of them (like "Ensembl_source_name" and "Display_in_jbrowse") can definitely be removed so I'll do that.  We can discuss what else to remove (or add).

    Name   Nucleosome positioning - meiosis 0h, pat1.114, diploid
    Track type   JBrowse/View/Track/Wiggle/XYPlot
    Data_type   Nucleosome positioning
    Display_in_jbrowse   yes
    Assay_type   NGS
    First_author   Soriano
    Publication_date   2013
    Pmed_id   24256300
    Geo_id   GSE41773
    Extra_db_id   GSM1024000
    Ensembl_source_name   Nucleosome positioning - NGS - meiosis 0h, pat1.114, diploid - Soriano (2013)
    Data_file_type  bigWig
    Source_url  https://www.pombase.org/external_datasets/GSE41773/GSM1024000_MN_Mei0h.bw

**Comment by kimrutherford** [comment]
I've added some documentation to the wiki about the track configuration: https://github.com/pombase/website/wiki/JBrowse-Configuration

I think the config file is ready to be edited and tidied up.  Now that all the columns are added I won't need to overwrite it.

There were two tracks that ended up with the same label "Nucleosome positioning - mitosis, 972 h-, haploid".  I've made them unique by adding "(NGS)" and "(tiling microarray)" to the ends of the label.

There are a bunch of Rhind (2001) tracks were we have a BigWig file and a BAM file.  Ensembl just showed the BigWig file so that what we're doing for now.  The BAM file tracks have "display_in_jbrowse" set to "no".

**Comment by Antonialock** [comment]
ah crud. I had saved a version on my desktop which I was editing last weekend. I'll need to merge our two docs (but I'm not finished yet...also looks like some overlap).

**Comment by kimrutherford** [comment]
> I'll need to merge our two docs

I'm happy to help if that's a pain.

**Comment by Antonialock** [comment]
well now I can't find it. either I didn't save it on my desktop and svn updating deleted the old version, or I deleted it by mistake when I was trying to clear space on my laptop :-( oh well, start over

**Comment by Antonialock** [comment]
@kimrutherford @ValWood 

I did some major revisions to the config file, does that look fine?

**Comment by kimrutherford** [comment]
> I did some major revisions to the config file, does that look fine?

Thanks!  I'll load it on my desktop and see how it goes.

**Comment by kimrutherford** [comment]
> I did some major revisions to the config file, does that look fine?

I had to modify the code which reads the config file to ignore the lines where the format is BED.  I haven't got BED files working yet so for now I've changed the code to print a warning and go to the next line.

The load failed last night but should be OK for tonight.

**Comment by Antonialock** [comment]
@ValWood can you check to see you are happy with columns )feel free to change the label wording)

**Comment by kimrutherford** [comment]
Your JBrowse changes are live now.

**Comment by ValWood** [comment]
> @ValWood can you check to see you are happy with columns )feel free to change the label wording)

where is the file now?

@Antonialock  can you close off this ticket and open a new one for outstanding tasks?

- [ ] Looking at the browser itself, my only comment is that often the text is "no data", can we improve this?
If we are happy, can we go live?

@Antonialock  could you draft an announcement and circulate?

v

**Comment by kimrutherford** [comment]
> where is the file now?

In SVN:
  pombe-embl/website/pombase_jbrowse_track_metadata.csv

**Comment by ValWood** [comment]
Nice, I think I'll look at the browser rendering of the data instead ;)

**Comment by ValWood** [comment]
- [ ]  first author should always be populated
- [ ]   if there is no data and it is not applicable put n/a so we can distinguish from "unpopulated"

**Comment by ValWood** [comment]
- [ ] data type should always be populated
- [ ]  which ones have  no assay type, we'll see if anything is appropriate

**Comment by ValWood** [comment]
- [ ]  how to make "data type" appear at the top were we going to add numbers?)

**Comment by ValWood** [comment]
- [ ] hide ENA study ID for now?  or are you populating this one?

**Comment by ValWood** [comment]
Oh I remember, the ones with no data are the "genome reference tracks"
- [ ]  how to handle these?

**Comment by Antonialock** [comment]
Val a lot of your comments don't make sense at all, did you look at the updated browser?
- the data type IS always populated
- all tracks ARE associated with a PMID
- first author IS always populated

etc

**Comment by Antonialock** [comment]
I'll open a new ticket for outstanding stuff

**Comment by ValWood** [comment]
https://github.com/pombase/website/issues/720

**Comment by ValWood** [comment]
we can go live without variation and announce when it appears.....
