### ISSUE TITLE
can't search on synonym

### ISSUE THREAD

**Issue by ValWood** [pombase/website#702]
V-shaped spindle
https://github.com/pombase/fypo/issues/3242#issuecomment-371783365

**Comment by kimrutherford** [comment]
It's there but because it's a RELATED synonym it has a low weight in the query.  If you type the full synonym ("V-shaped spindle during meiosis I") it's the top match.

I'll try raising the weights for synonyms.  I put them quite low because I wasn't sure when it was first implemented.

The other confusion is that it shows the term name rather than the matching synonym in the suggestions.  So if you type "V-shaped spindle during meiosis I" it shows "monopolar spindle during meiosis I".  I think we can do better on that and make it act more like Canto.

**Comment by kimrutherford** [comment]
> I'll try raising the weights for synonyms.

It's a bit better now.  "V-shaped spindle" completes to "monopolar mitotic spindle".

I've made an issue about showing the synonym: #705
