### ISSUE TITLE
edit FYPO flat file format doc

### ISSUE THREAD

**Issue by ValWood** [pombase/website#71]
I used these instructions  to make my file last night:

Some small suggestions
http://www.pombase.org/submit-data/modification-data-submission-form

10. Synonym. Can we put a real synonym example (this one would not exist as we would just fix the case to the consensus usage)

11. Allele type is not mandatory, but I think it should be?
Otherwise partial deletions (nt or aa) are not unambiguous, or some nucleotide or amino acid mutations....(probably up to now they have all been deletions in these tables?, do we need to check). Could say in instrucutions tat if your dataset is entirely deletions it is not required?

12. For the evidence code one we mention ECO, but cant we just provide a link to the list of the ones we use?  

19. Can you add that the date format is YYYYMMDD?  or change the eg in the table  to one where the day cannot be a month. (maybe everyone would know this except for me)

**Comment by mah11** [comment]
1, 2 and 4 done. I have not implemented suggestion 3, because that would commit us to maintaining another web page to house the list, and that risks going stale (we already have a couple of ECO IDs in PHAFs that don't have corresponding options in Canto). It might also not be a terrible thing to subtly discourage over-reliance on "other" in PHAFs.

**Comment by ValWood** [comment]
> It might also not be a terrible thing to subtly discourage over-reliance on "other" in PHAFs.

Good point.
I think I originally suggested this because the link isn't very useful. I could not easily see a way to search ECO. IS there one?

**Comment by mah11** [comment]
> I could not easily see a way to search ECO. IS there one?

http://evidenceontology.org/ - "Visualize ECO" in menu
(as noted in https://github.com/pombase/curation/issues/1035#issuecomment-244737669)

I haven't linked it to any of our docs on in-house bulk file formats, because I thought it would be less scary for biologists just to have us hold their hands rather than send them up against all of ECO. We can revisit that if people do become more familiar with ECO.

**Comment by ValWood** [comment]
Ok
