### ISSUE TITLE
some  proteins don't show up in the tmm domain query even though they have them

### ISSUE THREAD

**Issue by ValWood** [pombase/website#711]
SPAC977.01 | sub-telomeric 5Tm protein family Ftm1
ftm2 | SPAC977.02 | sub-telomeric 5Tm protein family Ftm2

**Comment by kimrutherford** [comment]
Does that mean the data from InterPro is wrong?  We haven't updated in a while.

**Comment by ValWood** [comment]
I think this might be to do with specific entries. It seems to only affect a few and its  seems to be the telomeric duplications, which were split out by UniProt (I think).

Could you provide me with the rows from the InterPro result flat  file (if there is such  thing?), then i can get in touch with them to check that   it gets resolved.

For the few which are missing I  can infer for my figure.

**Comment by kimrutherford** [comment]
> Could you provide me with the rows from the InterPro result flat file (if there is such thing?)

The data comes from a 100GB XML file.  :-(

I looked up one of your examples:
  http://www.uniprot.org/uniprot/P0CU16

UniProt are showing TMMs for that example.  I guess the possibilities are:
  - there's a bug and we're not displaying the TMMs from InterPro
  - they were missing from the InterPro XML in August but are there now (seems unlikely)
  - they're on the UniProt page but not in the InterPro file

Since our last update was in August, I'm downloading the latest InterPro XML file.  It takes a few hours to process but I think it will be done for tonight's load.

If the domains are still missing on the PomBase pages after this update, I'll dig into the XML file.

**Comment by kimrutherford** [comment]
I forgot to say: we don't load the XML file directly because that would be too slow to do every night.  Instead we process the XML, pull out the pombe entries and write them to a small and sensible JSON file.  We load the JSON file each night.

The JSON file generated from the August InterPro XML file doesn't contain any results for your two examples.  Once the latest XML file is processed I'll check the new JSON.

**Comment by ValWood** [comment]
It will probably be the same. I don't think there has been another release yet....

**Comment by kimrutherford** [comment]
> Does that mean the data from InterPro is wrong?

I have a memory like a goldfish - the TM predictions come from running TMHMM, not from InterPro.  I think what confused me is that we process the InterPro XML and we run TMHMM at the same time.  We generate a JSON file containing the domain data from both sources.

And that I think that is what indirectly caused the missing TM domains.  There's a bug in the logic of the JSON writer that means if there are no InterPro hits, no TMHMM results are written.  It looks like there were no InterPro results for your two genes in the InterPro release from August so no TMHMM results were written to the JSON file.  In the updated InterPro there are some InterPro results so the TMHMM hits are there now:
  https://www.pombase.org/gene/SPAC977.01
  https://www.pombase.org/gene/SPAC977.02

I'll fix the logic bug tomorrow.

> It will probably be the same. I don't think there has been another release yet....

There have been a few releases since I last updated: ftp://ftp.ebi.ac.uk/pub/databases/interpro/

**Comment by ValWood** [comment]
I had forgotten this too...

**Comment by kimrutherford** [comment]
> And that I think that is what indirectly caused the missing TM domains.

I was completely wrong.  The code is fine and doing the right thing.

The TM domains were missing on those genes because when I created the JSON data file in August those genes had different UniProt IDs in Chado.  The mapping file has changed since then:
  pombe-embl/ftp_site/pombe/names_and_identifiers/PomBase2UniProt.tsv

So SPAC977.02 is now P0CU07 but was Q9P332.  The JSON file contains only has UniProt IDs so the ID of the TM domains data blob in the JSON file didn't match what was in the current Chado.

It's all fine now it has been re-run.  And we have the latest InterPro data as a bonus.

**Comment by ValWood** [comment]
brilliant....
