### ISSUE TITLE
Include all GO terms in advanced search autocomplete  (i.e report 'zero' if no results)

### ISSUE THREAD

**Issue by ValWood** [pombase/website#726]
I noticed recently that you can no longer search on GO IDs only terms...its been like that at least a few weeks I think... I noticed a while ago and forgot to open a ticket.

**Comment by ValWood** [comment]
hmm, it works now...

**Comment by kimrutherford** [comment]
I haven't (knowingly) changed how that code works any time recently.  Perhaps you pasted a GO term ID into the phenotype search or vice versa?

**Comment by ValWood** [comment]
I checked the ontology, but maybe a space?

**Comment by kimrutherford** [comment]
> I checked the ontology, but maybe a space?

It should cope with leading and trailing spaces.  If it happens again, please let me know the ID you're trying.

**Comment by kimrutherford** [comment]
> For future reference I now remember why, its when we have not used the term in annotation....

I forgot about that.  Do you think that's the right behaviour?

**Comment by ValWood** [comment]
It might be less confusing if a "0" result came up. At present it won't let you perform the query. This might be confusing if you expected as result....Not urgent though...

**Comment by ValWood** [comment]
This might be tricky if only used GO terms are loaded?

**Comment by kimrutherford** [comment]
> This might be tricky if only used GO terms are loaded?

There are term pages for all terms:
  https://www.pombase.org/term/GO:2000526

but at the moment we don't load the term names or IDs into Lucene for auto-completion.

In Canto we don't auto-complete for non-pombe term because they aren't relevant (and might be confusing?).

**Comment by ValWood** [comment]
> In Canto we don't auto-complete for non-pombe term because they aren't relevant (and might be confusing?).

yes this is the preferred behavior. But this is taxon restricted terms. We can still search on terms which might be relevent to pombe but as yet unsued.

Maybe the PomBase search shoud be similar.

Thoughts?

**Comment by kimrutherford** [comment]
> yes this is the preferred behaviour. But this is taxon restricted terms. We can still search on
> terms which might be relevant to pombe but as yet unused.

Good point.  I understand now.

Currently we load the whole of GO into Chado because it's easier.  The website generation code doesn't know which terms are pombe-only.  We could try loading the pombe-only subset into Chado instead.  That would make it easy to add the unused terms to Lucene - we could just load all the Chado GO terms.

**Comment by ValWood** [comment]
I don't think it matters that ALL terms are avaiable in chado. I never even knew that they were. I don't think it's an issue that they are.

The reason that we don't want them in Canto is so that it removes some of the "noise/clutter" when people are annotating.

 I don't mind if unused terms are in Canto or not, but  it might be best practice to include all...

**Comment by kimrutherford** [comment]
> I don't mind if unused terms are in Canto or not, but it might be best practice to include all...

Do you mean Chado here?

Should the website autocomplete include all terms from GO?

**Comment by ValWood** [comment]
Yes I did mean Chado.

I think the website probably should allow a search on any GO term, but provide "zero" if no results. I would like to know what others think though @mah11 @Antonialock

**Comment by kimrutherford** [comment]
> I think the website probably should allow a search on any GO term, but provide "zero" if no results. 

OK.  That should be no problem.

**Comment by kimrutherford** [comment]
(Another old issue)

I think the summary here is that we want to be able to search for any term in the interface, even those we no annotations.  Just to be clear, do you mean search by term ID or searching by name?

I think searching by ID makes sense but I worry that if we allow searching all terms by name there will be cases where the un-annotated terms swamp out the annotated terms in the autocomplete.  So maybe you type in a word or two and lots of un-annotated terms appear because they match just as well as the annotated terms.

An alternative is to allow matching any term by ID, but only autocomplete on annotated term names.

Another option is to persuade Lucece (by changing weightings) that non-annotated term names should only be shown as a last resort.

**Comment by ValWood** [comment]
I think only report '0' IDs would be OK. Or does that seem like strange behavior?

**Comment by mah11** [comment]
> An alternative is to allow matching any term by ID, but only autocomplete on annotated term names.

This option would be fine with me.

**Comment by kimrutherford** [comment]
> An alternative is to allow matching any term by ID, but only autocomplete on annotated term names.

I've implemented that plan.  So if you paste a (non-obsolete) term ID, the name and description will appear even if there is no annotation.  You'll see the change on Friday morning.

Because the same server code is used for the autocomplete in the search box, that has changed too.

**Comment by kimrutherford** [comment]
> You'll see the change on Friday morning.

I've done a bit of testing and it all seems OK.  If you're happy with the change can you close this issue?

**Comment by mah11** [comment]
Looks fine to me too. I added a blurb to the search documentation.
