### ISSUE TITLE
track labelling questions

### ISSUE THREAD

**Issue by ValWood** [pombase/website#740]
![ask antonia](https://user-images.githubusercontent.com/7359272/38877241-2ae585e2-4256-11e8-91d1-03a96ad11654.jpg)

Here, I think that it is a bit confusing to have

1. clr4 delta used as experimental control (why is it a control, this is the mutant they are analysing isn't it?, same for dcr1 delta)

2. I think I would put   the allele in the description, but in (parenthesis)  so it is always the same format, otherwise it has varius different wording (maybe it is saying something different that I did not get?)

3. Experimental background should all be in the same place, so if clr4 really is "background" it should move to the background column.

4. I liked your notation in the spreadsheet "technical background"  which makes this clearer.
but make sure that you don't put hte allele under study into the "background"

**Comment by Antonialock** [comment]
1. No it really is an experimental control, it is a bit of a special case. The "normal" control for the Dam-ID assay is Dam-only (i.e. expressed on its own, not fused to any protein). In their experiments they included the additional control of Swi6-Dam in a clr4-delta background.
Swi6 does not bind chromatin in the clr4delta mutant, so it is virtually virtually the same as expressing unfused Dam. 

2. I'm not sure what you mean? 

3. it's just in the control channel Val, the "measured" channel is still Sw6 chromatin binding in WT. 
i.e. you have
measured channel normalized to control channel (control channel = normally dam only, but in this special case it is clr4delta)

I don't think we should spend too much time worrying about this one track. I can write more helptext but hopefully anyone interested in the data can go look it up.

4. is this still about the one track?

**Comment by ValWood** [comment]
I'm confused about the difference between "alleles' and 'controls' and I'm confused about what the controls mean. The labels seem a bit inconsistent to me.  I'm still not sure why it isn't sorting alphabetically on track label (looks random). So maybe I'm being dim. You seem confident that it is OK, so don't worry about it, you can explain it to me when you see me ;)

**Comment by ValWood** [comment]
> is this still about the one track?

Its about all the tracks really. I'll be more explicit.

Why is:

Swi6 (clr4 delta background ) WT  in allele column
and
Arb1 (clr4 delta background )  clr4delta in allele column

**Comment by ValWood** [comment]
can probably be closed, pending my final question?

**Comment by Antonialock** [comment]
Arb1 (clr4 delta background ) clr4delta in allele column
-> experiment was performed in a clr4 delta mutant

Swi6 (clr4 delta background ) WT in allele column
-> this track never existed outside of your head ;). I agree it wouldnt make sense

I had already relabelled the tracks that confused you.

These are now labelled as:

Swi6 chromatin   binding sites during vegetative growth, (control channel: clr4delta) repeat 3   - Woolcock et al. (2011)
Swi6 chromatin binding sites during   vegetative growth, (control channel: dam only) repeat 1 - Woolcock et al.   (2011)

For this assay you typically normalize against "dam only" (i.e. protein-fused-to-Dam signal is normalized to Dam-not-fused-to-anything signal - this removes background noise)

Swi6 is a special case because in a clr4-delta background it does not bind chromatin AT ALL, so it can serve as an additional control, and should yield the same results as when normalizing against Dam only

For these TWO tracks they looked at Swi6-Dam binding in **WT** background. They normalized to two different controls: 1) Dam only and 2) Swi6-Dam in clr4 delta background

It has nothing to do with a mutant background, it only has to do with how you normalize your data.

I asked Marc if he really wanted to include both tracks and he said he thought it was important. I hope the newish label makes it clearer. I agree it is a difficult one to communicate. If you now understand what's going on and have any suggestions for improvement feel free to suggest away :-)

**Comment by ValWood** [comment]
OK
