### ISSUE TITLE
search result sequence download - add flanking regions

### ISSUE THREAD

**Issue by mah11** [pombase/website#744]
In the sequence download options for search results*, add the options to include sequence upstream and/or downstream of the selected bits. Controls can work essentially the same way as in the gene page sequence display options.

This got a passing mention it #21, but is kind of lost in the many comments there.

Medium priority because we've lived without it all along, but it will be _wonderful_ to be able to stop sending people into the BioMart jungle.

*i.e. do a search -> click for results -> click Download -> Sequence tab in popup

note to self: when done, update faq can-i-download-sequences-for-many-genes-at-once-including-flanking-regions.md

**Comment by kimrutherford** [comment]
> In the sequence download options for search results*, add the options to include sequence
> upstream and/or downstream of the selected bits.

That makes a lot of sense.  I'll have a go at this once PHI-Canto is under control.  Hopefully soon.

**Comment by kimrutherford** [comment]
> add the options to include sequence upstream and/or downstream of the selected bits.

I've implemented the server side of this.  I'm now thinking about how the gene list / search result download dialog should look.

I'd like it to make the dialog look more or less like the sequence download section on the gene pages.

The sequence download dialog currently looks like this:

![download-gene-list-dialog-1](https://user-images.githubusercontent.com/90474/45260503-9de78280-b43d-11e8-92c3-ba43eeb7935d.png)

An obvious problem is that it says "CDS sequence and:" but some gene lists will contain RNA genes.  Any suggestions for the wording there?  It's a bit trickier than the gene page sequence section because on a gene page we always know if the gene is coding or not.  A gene list could contain coding or non-coding genes.

The "Include 5'UTR" doesn't always make sense either.  Perhaps it should say "Include 5'UTR for protein coding genes"?

What wording should we have beside the upstream and downstream bases selector?  On the gene page we can be quite explicit about what the bases are upstream or downstream of (translation start vs gene start etc - see below).

Here's how the download dialog looks for a protein coding gene:
![seq-download-prot-gene-1](https://user-images.githubusercontent.com/90474/45260423-84ddd200-b43b-11e8-8b2f-8bbb8f5d3011.png)

The text changes a bit if the UTRs are selected:
![seq-download-prot-gene-utr-1](https://user-images.githubusercontent.com/90474/45260425-8c9d7680-b43b-11e8-9b32-4c0c998f800f.png)

And the text is different again for an RNA gene:
![seq-download-rna-gene-1](https://user-images.githubusercontent.com/90474/45260426-9030fd80-b43b-11e8-9e3e-7eb1a14d0c60.png)

For now I'm going to add it to the gene results download dialog as "Upstream bases" and "Downstream bases" but I would prefer to be more clear.  We definitely need to change the "CDS sequence and:" text and probably the "Include 5'UTR" text.

Let me know if you have any thoughts or we can chat about it on a call sometime.

**Comment by mah11** [comment]
Here's a slightly radical suggestion (apologies for crap formatting):

- Amino acid (protein-coding genes only)
- Nucleotide
- Include in downloaded sequences:
- -  [box] bases upstream
- - 5' UTR (protein-coding genes only)
- - Exons
- - Introns
- - 3' UTR (protein-coding genes only)
- -  [box] bases downstream

**Comment by kimrutherford** [comment]
That wording seems fine to me.  Val and Antonia, do you have any tweaks or should I go ahead?

**Comment by ValWood** [comment]
sounds good

v

**Comment by Antonialock** [comment]
yeah looks fine.

**Comment by kimrutherford** [comment]
OK, thanks.  I've updated the text.
