### ISSUE TITLE
interaction section

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#749]
hee it says source: biogrid, but I curated the information. Looks misleading?

this example from 
![screen shot 2018-05-02 at 08 55 41](https://user-images.githubusercontent.com/12727506/39511815-b10e4afa-4de6-11e8-90b9-b299a4a01323.png)
https://www.pombase.org/reference/PMID:19473263

**Comment by kimrutherford** [comment]
> biogrid, but I curated the information. Looks misleading?

We could change it to: "Interactions curated by BioGRID and PomBase"

**Comment by Antonialock** [comment]
yes, although it would be nice to link to biogrid where they have curated...they provide more information about the interaction (particularly useful for genetic interactions imo). Not urgent I suppose, we haven't shown it so far.

**Comment by mah11** [comment]
> it would be nice to link to biogrid where they have curated

Nice, yes, but on gene pages that would require a link at the level of each individual annotation because the interaction section lumps annotations from papers we curated with ones from papers BioGRID curated.

It would work for publication pages, where each paper has interactions from one group (apart from corrections, which we can ignore for this purpose). Do you envision having the BioGRID link only on publication pages? (If so, that link could go specifically to BioGRID's entry for the paper, rather than to the home page.)

**Comment by Antonialock** [comment]
I don't really envision anything at this stage, just in the back of my mind.

#40 talks about a mouseover, which would actually resolve the "less than ideal" current situation

**Comment by ValWood** [comment]
1. OK we can add the  suggestion by Kim
"Interactions curated by BioGRID and PomBase"
(I think we need to update BIOgrid  with our data though?)

2. What is the additional infor BIOGRID provide...
Why isn't https://github.com/pombase/website/issues/40
sufficient for this?

**Comment by Antonialock** [comment]
Yes that would be good in the short term.

We have some additional things we would like (#40 ) but it isn't urgent.

**Comment by ValWood** [comment]
What are the "things"

val

**Comment by Antonialock** [comment]
it's in #40, I thought I'd try and clear this ticket from stuff I realized is covered by another ticket.

**Comment by kimrutherford** [comment]
> We could change it to: "Interactions curated by BioGRID and PomBase"

I've made that change.
