### ISSUE TITLE
more informative page titles for browser history

### ISSUE THREAD

**Issue by mah11** [pombase/website#750]
Back in #130 the html titles for gene, publication, and ontology term pages got nice informative titles, which show up in helpful places like tab headers and history entries.

I would find it very useful indeed to do the same for the static pages, search, and basically anything else that doesn't already have something more informative than just "PomBase". Right now I have some browser tabs with just "PomBase" over and over again in the history, and that doesn't really tell me where I've been ;)

@kimrutherford - I am happy to do the relevant static pages additions/edits if you can tell me what to edit where. I think you'll have to do the search page and any other pages that don't come from the /frontend/src/docs/ directory

**Comment by kimrutherford** [comment]
Thanks.  I'll have a think about the best way to do this.

**Comment by kimrutherford** [comment]
> Right now I have some browser tabs with just "PomBase" over and over again in the history, and that
> doesn't really tell me where I've been

I've notice a related problem - for me in Chrome the history always says "PomBase" for every page.  Firefox has the expected gene, term and publication page titles in the history.

I'm still working on improving the titles.

**Comment by kimrutherford** [comment]
The documentation page titles are now displayed in the browser window title.  I still haven't worked out why the page titles don't show up in the history in Chrome.

**Comment by ValWood** [comment]
Did you figure this out with the recent changes?

**Comment by kimrutherford** [comment]
It still works fine for me on Firefox but not in Chrome. I do another Google search for solutions. It might be a quick tweak.

**Comment by kimrutherford** [comment]
I think I've the weirdness in Chrome.  The page title now consistently show up in the history.  The problem was that each time a new page was displayed, the title was being set to a default ("PomBase") and then later set to the page specific title.  It seems that Chrome doesn't like that and it's also necessary.  Now that the title is just being set once the history works.

It's possible that this was also causing the Google search results for genes (#1039) to be quite poor.  We'll see.

I've leaving this open because the title isn't set for all documentation pages yet.  That's still in progress.

**Comment by kimrutherford** [comment]
> I think I've the weirdness in Chrome.

Should be "I think I've fixed the weirdness in Chrome."

**Comment by kimrutherford** [comment]
> I've leaving this open because the title isn't set for all documentation pages yet. That's still in progress.

Now I've checked, it's looking quite good.  The title changes as you navigate around the site, including the documentation.

So I'll close this.

Please open separate issues for any missing or not great titles.
