### ISSUE TITLE
Handle long genotype names better

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#765]
This might need a bit of line wrapping:

"KR25A+SV40NLS(K143A,R144A,K145A,R146A,R149A,K151A,K152A,K156A,K161A,R163A,K164A,K169A,K172A,K177A,K184A,K187A,K191A,K217A,K222A,K241A,K242A,K243A,K251A,R256A,K261A,with SV40 NLS added at N-terminus)"

https://www.pombase.org/genotype/5bf20875f2c283f7-genotype-8

**Comment by ValWood** [comment]
A suugestion....we don't *really* need to be able to actually read these in Canto, other than to differentiate from related alleles.

I suggest that  on "annotation" pages at least we shorten  

by
"KR25A+SV40NLS(K143A,R144A,K145A,R146A....."
at some suitably agreed   cut-off ?

**Comment by kimrutherford** [comment]
> read these in Canto

I was mostly thinking about the website genotype pages where that example runs off the side of the screen.

(Although they're too long in Canto too)

**Comment by ValWood** [comment]
- [ ]  AI try to find out which  gene/allele this is for future

**Comment by mah11** [comment]
the example is an allele of swi6 from PMID:22683269 (session 5bf20875f2c283f7)

**Comment by ValWood** [comment]
This is swi6

the issue is in the heading

http://pombase-dev.bioinformatics.nz/genotype/swi6-KR25A%2BSV40NLS-K143A,R144A,K145A,R146A,R149A,K151A,K152A,K156A,K161A,R163A,K164A,K169A,K172A,K177A,K184A,K187A,K191A,K217A,K222A,K241A,K242A,K243A,K251A,R256A,K261A,with_SV40_NLS_added_at_N-terminus-other-expression-not_assayed


AI:  introduce a teeny-weeny bit of whitespace to enable line wrapping

**Comment by ValWood** [comment]
https://www.pombase.org/genotype/swi6-KR25A%2BSV40NLS-K143A,R144A,K145A,R146A,R149A,K151A,K152A,K156A,K161A,R163A,K164A,K169A,K172A,K177A,K184A,K187A,K191A,K217A,K222A,K241A,K242A,K243A,K251A,R256A,K261A,with_SV40_NLS_added_at_N-terminus-other-expression-not_assayed

only a problem in the header:

![line-wrapping](https://user-images.githubusercontent.com/7359272/43547899-85d6b7d8-95d4-11e8-84cb-e9d27bb4be8b.jpg)


gene page and  alelle page otherwise fine...

**Comment by ValWood** [comment]
Not hugely urgent but do final bit if quick

**Comment by ValWood** [comment]
Is this a solution? If so looks quick?

**Comment by kimrutherford** [comment]
That's fixed now.
