### ISSUE TITLE
Add  JBrowse documentation

### ISSUE THREAD

**Issue by ValWood** [pombase/website#783]
[Getting started with PomBase JBrowse.pdf](https://github.com/pombase/website/files/2042389/Getting.started.with.PomBase.JBrowse.pdf)

Would make more sense for this to be "core documentation"

**Comment by Antonialock** [comment]
Yeah I just wanted to send something out as part of the announcement, we should have something similar in the documentation

**Comment by mah11** [comment]
I've added a link to the "Getting started" doc to the main documentation page (https://www.pombase.org/documentation). Close this if that's enough.

**Comment by Antonialock** [comment]
I can write it up so that it can be shown on the website. Would a word/google doc do?

**Comment by mah11** [comment]
Not sure I fully understand the question - the PDF content displays in most browsers anyway (and if it doesn't, that's down to someone's browser settings). It would actually be worse to link to a Word doc or even a Google doc.

If you want to have the content on a web page, it'll have to be converted to HTML, or maybe Markdown would suffice; it depends on how complex the structure and formatting are. But for that, it's approximately as easy to copy/paste from the existing PDF as from a word-processor doc. And I'm not sure we'd gain enough to make it worth having two versions that could drift out of sync.

**Comment by ValWood** [comment]
I agree, the pdf needs to be migrate into the html, and deprecate the pdf, it was temporary.

**Comment by mah11** [comment]
> I meant something that could be easily converted to web page format.

A word doc seems like a tangent. For a web page, we need to mark up the text and put the images in the correct directory.

> I don't understand why we would have two versions? We would have the documentation that's online.

This implies that we would remove links to the PDF - otherwise, it will hang around and be the second version after we add a web page.

I'm happy to have a web page instead of the current PDF, and can convert the text from it without anyone creating new Word docs (I have no use for Word in this effort). I'll need to know where to find the images so I can copy them into the github repository.

**Comment by Antonialock** [comment]
Yes just remove the links once appropriate, it was just a temporary measure, it's not how we normally provide documentation. 

I really didn't want to send the announcement without some supporting help documentation of "how to get going" for novices  (I didn't know how to add a website help page + you were at beerfest when we sent it, we also didn't want to delay announcement since the data was up there)

**Comment by mah11** [comment]
I've added a new documentation page. Over to @kimrutherford to update the website.

I'll check it over and fix any problems that I couldn't spot in the text editor, and then close this.

**Comment by kimrutherford** [comment]
It's now updated in pombase-dev if you'd like to have a check before it goes live.

http://pombase-dev.bioinformatics.nz/

**Comment by mah11** [comment]
Thanks - it looks pretty good. This afternoon I'll fix some typos and it'll look even better. After today's commit it should be ready to go live.

**Comment by mah11** [comment]
I've committed my fixes, and I think it's ready (anything left to fix is probably small enough not to cause problems if it does reach the live site).

**Comment by kimrutherford** [comment]
> I've committed my fixes, and I think it's ready

I'm off to bed but I've just kicked off a pombase-dev update.  Should be done in 10 minutes-ish if you want to have a look.  It will go live on the main site tonight (UK time) or on (UK) Wednesday morning.

**Comment by mah11** [comment]
Cool, thanks, and sleep well :)

**Comment by kimrutherford** [comment]
I've updated the main site.

**Comment by mah11** [comment]
Thanks, but oddly, it's showing the version from Monday. It doesn't have the small fixes I did yesterday. I don't think I forgot to push the changes, and I do see the newer version in the GitHub web interface "code" tab. Any ideas?

**Comment by kimrutherford** [comment]
Sorry, I forgot to push the update to GitHub.  All updated for real this time I hope.

**Comment by mah11** [comment]
I'm disproportionately glad it wasn't me ;)

All looks good now; thanks again. I think that's this one done - yay!
