### ISSUE TITLE
Error viewing mitochondrial chromosome reverse strand features

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#784]
I think this is happening because there are no reverse strand mitochondrial chromosome features in Chado.

![mito-fail-1](https://user-images.githubusercontent.com/90474/40584039-574ef5c0-61ee-11e8-80d0-4c660c349b79.png)

**Comment by ValWood** [comment]
Yup, what should we do? can't you display an empty strand (this must be an issue for  other mitochindiral genomes.... what do SGD do?)

**Comment by ValWood** [comment]
https://browse.yeastgenome.org/?loc=chrmt%3A8550..77172&tracks=DNA%2CAll%20Annotated%20Sequence%20Features%2CDoube_strand_break_hotspots%2CXrn1-sensitive_unstable%20transcripts_XUTs%2CScGlycerolMedia%2C3%27UTRs%2CPolII_occupancy_WT&highlight=


that didn't help, they display all on the same strand (there is a reverse strand feature here the origin of replication)

Actually, that suggests a solution, revert to  "display  both strands on a single track view" for mitohondria?

**Comment by kimrutherford** [comment]
> Actually, that suggests a solution, revert to "display both strands on a single track view" for mitohondria?

We can't do it just for mitochondria.  It's all or nothing.

I'll double check the documentation then make a JBrowse issue about the error.

(Unless there are any reverse strand features you could add.  Like the origin of replication?  It kind of makes sense for that to have a forward and a reverse strand feature I think?)

**Comment by ValWood** [comment]
Yes we could do that. The origin of replication is strand independent so it can go on either strand. We just need to find it ;)

**Comment by ValWood** [comment]
I can't find the nucleotide sequence submission at EBI (I tried multiple ways)
but I don't think it must be known or I would have annotated it.

That said, I did spot that the  major and minoe promoters are available here:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC140500/

could ask if anyone knows

**Comment by mah11** [comment]
in light of 

> but I don't think it must be known or I would have annotated it

this is a tangent, but the submission is easy to find at NCBI:

https://www.ncbi.nlm.nih.gov/nuccore/X54421

**Comment by ValWood** [comment]
great we can add

 misc_difference 2091
                     /note="conflict"
                     /citation=[3]
                     /replace="g"


     misc_difference 4102
                     /note="conflict"
                     /citation=[4]
                     /replace="g"

REFERENCE   3  (bases 1 to 2900)
  AUTHORS   Lang,B.F., Cedergren,R. and Gray,M.W.
  TITLE     The mitochondrial genome of the fission yeast, Schizosaccharomyces
            pombe. Sequence of the large-subunit ribosomal RNA gene, comparison
            of potential secondary structure in fungal mitochondrial
            large-subunit rRNAs and evolutionary considerations
  JOURNAL   Eur. J. Biochem. 169 (3), 527-537 (1987)
   PUBMED   2446871
REFERENCE   4  (bases 3131 to 4580)
  AUTHORS   Trinkl,H., Lang,B.F. and Wolf,K.
  TITLE     Nucleotide sequence of the gene encoding the small ribosomal RNA in
            the mitochondrial genome of the fission yeast Schizosaccharomyces
            pombe

to make the bug go away

**Comment by ValWood** [comment]
OK I added these 2  as reverse strand features 

misc difference
complement(2091)
/note="conflict"
/replace="g"
/db_xref="PMID:2780299"

and
complement(4102)
/note="conflict"
/replace="g"
/db_xref="PMID:2780299"

(note that since these were originally reported on fwd strand I reverse complemented the conflict)

Let's see if the bug goes away.....

**Comment by kimrutherford** [comment]
> Let's see if the bug goes away.....

I need to add "misc_difference" the contig loader configration.  Which SO term should we use in Chado to represent those new features?  Options include "point_mutation" and "SNP.

**Comment by kimrutherford** [comment]
Fixed.  Thanks Val!

**Comment by kimrutherford** [comment]
Now we have a new mitochondrial config file we have this problem again.  The forward strand features look fine.

Val, your two reverse strand "misc_difference" features aren't there any more.  Are they still relevant?  Could you add them back if so?

**Comment by ValWood** [comment]
I removed them, these were just discrepancies between different versions of the sequence. This sequence is the corrected version. At least it's a different version so I assumed no longer relevant (although I did not check this)
@lilindu can confirm.

That's a good check to have in place though- features disappearing !  I didn't know we had that.

**Comment by lilindu** [comment]
The two "misc_difference" features in https://www.ncbi.nlm.nih.gov/nuccore/X54421 actually correspond to two of the 20 errors listed in Table 1 of Tao et al. 2019. I guess the authors who submitted X54421 to GenBank had suspected possible errors at these two positions but decided to only add a note of "conflict" because they were not absolutely certain about which nucleotide is correct.

**Comment by ValWood** [comment]
Oh I see now. I did not realize that your comment was in this old ticket. I  only read the comment not the history- so that is why we had the conflicts flagged!

I guess this is really a JBrowse issue?

**Comment by ValWood** [comment]
This is what I see in my default gene page view because of  the mitochondrial genome feature depth

<img width="1052" alt="Screen Shot 2020-05-08 at 05 16 47" src="https://user-images.githubusercontent.com/7359272/81369782-4191a600-90eb-11ea-9451-9449fcc99082.png">


Is it possible to default so that the  vertical scroll bar if it appears  is set to the top instead of the bottom?

**Comment by kimrutherford** [comment]
> Is it possible to default so that the vertical scroll bar if it appears is set to the top instead of the bottom?

I don't know how to fix that.  Have you seen it happen on pages without the JBrowse error?

**Comment by ValWood** [comment]
I think it only occurs with the mito genome because the depth is bigger

see  cdc2
https://www.pombase.org/gene/SPBC11B10.09
https://www.pombase.org/gene/SPBC83.15

the scroll bar is there, and at the bottom, but it doesn't matter here.

but for mito
https://www.pombase.org/gene/SPMIT.09
there are ~ 30 features/genes in 10kb
I don't think we are likely to see thin in the nuclear genome (except when we add  @bahler s 15,000 ncRNA's it could be a problem....

**Comment by ValWood** [comment]
At the centromere it happens
https://www.pombase.org/gene/SPCTRNAVAL.09
but it doesn't seem so bad because you don't see the error, you see at least some features.

I'm tempted to just create a dummy feature on the mito reverse strand..

**Comment by cmdcolin** [comment]
This is probably due to the request for https://www.pombase.org/jbrowse/data/tracks/PomBase%20reverse%20strand%20features/mitochondrial/trackData.json returning a status 200 instead of a 404 error

**Comment by kimrutherford** [comment]
Thanks for the diagnosis Colin.  I'll fix that.

Have a great weekend.

**Comment by kimrutherford** [comment]
That fixed things.  Thanks Colin.

**Comment by ValWood** [comment]
That's much better, we don't have the big error,
but  we still don't see the genes  for example here:
https://www.pombase.org/gene/SPRRNA.01
because the right hand scroll bar defaults to the bottom. Are we sure that there isn't a way to make it default to the top?

**Comment by ValWood** [comment]
closing so I don't need to read the entire ticket again, I'll open a new ticket for the small outstanding issue to try to make the scroll bar default to the top on our gene pages.

https://www.pombase.org/gene/SPRRNA.01
because the right hand scroll bar defaults to the bottom. Are we sure that there isn't a way to make it default to the top?
