### ISSUE TITLE
Wrong message for paper with no annotation

### ISSUE THREAD

**Issue by kimrutherford** [pombase/website#795]
https://www.pombase.org/reference/PMID:29784772

The current message is "This publication has no annotations in PomBase because it hasn't been curated yet." which is wrong because the session for that paper has APPROVED status.

I noticed this because (today at least) it's the top of the "Recent community curation" list - not ideal.

**Comment by kimrutherford** [comment]
I've fixed things so that it shows the correct message for curated papers with no annotation:

    This publication has no annotations in PomBase because the curators have found
    no annotatable gene-specific data in it.

> I noticed this because (today at least) it's the top of the "Recent community curation" list - not ideal.

Should curated, approved papers with no annotation appear in the "Recent community curation" list?

**Comment by ValWood** [comment]
This publication has no annotations in PomBase because the curators have found no annotatable gene-specific data in it.


maybe

This publication currently has no annotation in PomBase because there is   no  gene-specific data for available annotation types.

I have no problem with it been in the list for now....I triaged it incorrectly and the author sent it back classed as no annotatable data.

**Comment by kimrutherford** [comment]
> maybe
> This publication currently has no annotation in PomBase because there is no gene-specific data
> for available annotation types.

Should I go ahead and make that change?

**Comment by ValWood** [comment]
I think it sounds less like "nothing useful to read in this paper"
@mah11  can tweak if better suggestion.

**Comment by mah11** [comment]
I'm happy to amend the message wording, but it seems like two slightly different things are being conflated. The current wording

> This publication has no annotations in PomBase because the curators have found no annotatable gene-specific data in it.

is trying to do dual duty - it's covering both
- papers where someone has ticked the "This paper does not contain any gene-specific information" box instead of entering a gene list, and
- papers where someone has entered a gene list but then chosen the "data not of available types" reason not to add experimental result annotations (this is the case for PMID:29784772).

Val's suggestion seems to shift emphasis to the second case. If we want to lessen the impression that "no annotatable gene-specific data" means "nothing interesting", but still have one message for both kinds of no-annotations, it may take more words, e.g.:

"This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types."


Or, if we want to distinguish these two cases (non-gene-specific data vs. gene-specific data of types not available in Canto), we could split the messages into

"This publication has no annotations in PomBase because the data in it cannot be associated with individual genes."

for the first type, and for the second type

"This publication has no annotations in PomBase because the data it contains do not match any of the currently curatable types."

**Comment by mah11** [comment]
We can stop fretting about this if we use the combined message:

"This publication has no annotations in PomBase because the data it contains either cannot be associated with individual genes, or cannot be represented by currently available annotation types."

**Comment by ValWood** [comment]
curent message
This publication has no annotations in PomBase because the curators have found no annotatable gene-specific data in it.

**Comment by mah11** [comment]
... use for papers with completed Canto sessions but no annotations.

Nothing else changes - we're happy with how reviews, methods, uncurated pubs, and pubs with annotation are handled.
