### ISSUE TITLE
Gene page counts

### ISSUE THREAD

**Issue by ValWood** [pombase/website#84]
I am now using PomBase2 as my  main website because it is up to date  and I can see all the changes I made recently!
It is already therefore much more useful than the current site for evaluating the annotation status.

However the "counts" only reflect the direct annotations (I think?), so can this be fairly high on the list in this new fast moving PomBase world...

**Comment by kimrutherford** [comment]
> the "counts" only reflect the direct annotations (I think?)

Yep, just direct annotations so far.

**Comment by kimrutherford** [comment]
> However the "counts" only reflect the direct annotations

I completely misread all this.  For some reason I thought that the counts on pombase.org were counts of annotations using the term rather than counts of genes annotated with the term.

So I've implement the indirect annotations but the counts are annotation counts.  And if you click through to the term page it shows details of all the annotations (term name, evidence code, reference, etc.).  For example here is GO:0000281, mitotic cytokinesis:
   http://pombase2.bioinformatics.nz/term/GO:0000281

I'll fix the counts to be gene counts but is it useful to have all the annotations shown on the term page?

Also which relations should be followed to find descendant annotations?  Currently it's just using is_a and part_of.

**Comment by kimrutherford** [comment]
The counts are now gene counts but the term details pages have the same information for now.

I temporarily swapped in the v61 data for pombase2 and gene counts were in the right ball park.  Some were a bit too low though.  Perhaps because it's only following is_a and part_of to find the descendants.

**Comment by ValWood** [comment]
Yes its gene count.
Is a bit odd becasue the count and the term link tale you to (exactly) the same page.

Displaying the gene "count"  is a carry over from GeneDB.
It's useful, but many users do not know what it means. Once they know it is useful.
We have never come  up with a better way to do this (any ideas?)
In GeneDB the column header used to be "others"

I'm not sure how useful it is to see all annotations directly on the term page. Maybe the should be available though (but perhaps one click away?) a link "view all annotations" on the term page?

Genes is more immediately useful  and should be the most prominent view ( it removes the redundancy presented in the annotation list). However Amigo does offer to view by genes or by annotations, and perhaps this is useful too.
Actually I rather like this view, you can see which descendent term the annotation is coming from. So yes ;)


> Currently it's just using is_a and part_of.
it' s 
is_a and part_of and regulates for Biological Process (also use Function-process links)
is_a and part_of  for Molecular Function
is_a and part of for Component

I think thats it.....

**Comment by kimrutherford** [comment]
> In GeneDB the column header used to be "others"

For now I've changed it to say "Other genes"

> Genes is more immediately useful

The "Other genes" count is now a link to a term details page with a link of genes. 

> Actually I rather like this view, you can see which descendent term the annotation is coming from. So yes ;)

For now, the name and term ID in the annotation tables on the gene pages continues to be a link to the term details page that includes all the annotation.

So there are two term details view now.  One has the genes and the other has the annotations.  Each page has a link to the other.  eg.
   http://pombase2.bioinformatics.nz/term/GO%3A0007131
   http://pombase2.bioinformatics.nz/term_genes/GO%3A0007131

It would probably be nicer to have two tabs on the same term details page for these two view, but this was easier to do quickly.

> Currently it's just using is_a and part_of.

What relations should be used for find descendant for FYPO?  The only seem to be three relations between FYPO terms in Chado: is_a, part_of and inheres_in.  For finding descendants for displaying annotations should we follow inheres_in relationships too?

> is_a and part_of and regulates for Biological Process

OK, I'll add regulates for looking up process terms descendants.

> also use Function-process links

That will take longer because we don't have those links in Chado.  Are they in the standard GO ontology or are they in a different file some where?

**Comment by kimrutherford** [comment]
I've just tried loading up the v61 data to compare the counts.  They're very close.  One problem I noticed was that NOT annotations aren't handled correctly in the new code.  They should be ignored in the counts and "NOT" should be displayed.

**Comment by ValWood** [comment]
> What relations should be used for find descendant for FYPO? 
@mah11 (I can never remember which to follow for propagation)

> also use Function-process links
I'm not sure.... @mah11  ?

> One problem I noticed was that NOT annotations
well spotted. In 1 we had about 100 tickets about that ;) this is *so* easy ;)

**Comment by ValWood** [comment]
- One has the genes and the other has the annotations. 

Lovely! I think annotated genes should be the default view.

**Comment by ValWood** [comment]
- For now, the name and term ID in the annotation tables on the gene pages continues to be a link to the term details page that includes all the annotation.

I wonder if this would work, to save space:

Term name (other genes)
cysteine metabolic process (10)

i.e collapse into a single column?
??

**Comment by kimrutherford** [comment]
> collapse into a single column?

Maybe that would make it less obvious what the numbers mean?

**Comment by ValWood** [comment]
perhaps. I though people would read it the same way but maybe not.
My problem with the single column has always been the space which the informative header requires.....But the info is useful.

**Comment by kimrutherford** [comment]
I've changed things to use is_a, part_of and regulates for finding descendants of process terms and I've fixed the counts to ignore NOT annotations.  It also now shows "NOT" beside NOT annotations.  eg.
  http://pombase2.bioinformatics.nz/gene/SPAC15E1.07c

>  In 1 we had about 100 tickets about that ;) this is so easy ;)

Yep!  I feel like I'm cheating.  :-)

**Comment by ValWood** [comment]
Actually I think the others counts are fine as they are...

**Comment by mah11** [comment]
re links for FYPO:

> What relations should be used for find descendant for FYPO?

Follow is_a and part_of as for GO.

There should be lots of has_part links between FYPO terms, and they should be followed the same way as it works in Canto. Example:

id: FYPO:0000223
name: elongated multiseptate vegetative cell
relationship: has_part FYPO:0000061 ! multinucleate vegetative cell
relationship: has_part FYPO:0001122 ! elongated vegetative cell

The counts for FYPO:0000061 and FYPO:0001122 should include things annotated to FYPO:0000223 (and search results should do the same, when you get there).

Ignore the inheres_in links - most of them point to GO terms, and the only 3 FYPO terms used with inheres_in are very high level and not very informative. Everything should have an is_a link to a more specific FYPO term asserted or inferred anyway.

**Comment by mah11** [comment]
re MF-BP:

> > also use Function-process links
> 
> That will take longer because we don't have those links in Chado. Are they in the standard GO ontology or are they in a different file some where?

The MF-BP links are in the go.* and go-plus.* versions of the GO files. Annotations that can be inferred by following MF-BP links should be in the "inferred GAF" files (ours is gene_association.pombase.inf.gaf), so in theory you could get them by loading that .inf.gaf file from GO Jenkins. BUT in practice, something's been wrong for months - see this ticket, which I opened last December: https://github.com/geneontology/go-annotation/issues/1336

Since we can't rely on the GO Jenkins inference file yet, once you get the ontology links, annotation counting should work - at present I think they're all MF part_of BP (and in the longer term, even if they add any other link types it'll be the MF part_of BP ones that we'll want to use).

So, on to the question of whether we _should_ include MF-BP links ...

I think it would be entirely accurate to follow MF-part_of-BP links, because it would effectively be saying "this gene product is involved in this process, because it does this MF which is always part of the process" - if that's ever not true, there's a problem with the ontology.

What I can't guess as easily is whether it's what users would expect, or whether it would foul up anyone's usage of the counts - or especially the search results - to have BP terms retrieved by a query for MF. For counts on gene pages I suppose we could just make an executive decision, document the hell out of it, and hope for the best. When it comes to search behavior, it might be wise to offer an explicit option to include or exclude inter-ontology retrieval. (And I hope that's technically feasible!)

**Comment by mah11** [comment]
re counts & term pages

> I think annotated genes should be the default view.

Seconded.

> [column header is] "Other genes"

This is super-duper pedantic, but because the gene whose page you're on is included in the count and shown on the linked page, it's not "other" genes. It's all genes annotated to the term. So "Annotated genes" would be the most accurate header, but it's annoyingly long. Maybe just "Genes"?

> > collapse [term name and gene counts] into a single column?
> 
> Maybe that would make it less obvious what the numbers mean?

I agree that the meaning may not be as clear as with a column. There's also a visual issue: 
counts won't be in a consistent position in the table, unless we put the number before the term name, which seems like the wrong emphasis. It's good for the numbers to be consistently positioned, because that makes it easier to find where to click, as well as to look over the list and see which terms have lots annotated (often the less specific terms) versus a few (often more specific terms).

**Comment by ValWood** [comment]
OK:
Gene Count
Annotated genes
Genes

Not keen on any, maybe "Genes" is best but its not ideal...

Separate column is definitely better for scanning up and down numbers....

**Comment by ValWood** [comment]
Re:  What I can't guess as easily is whether it's what users would expect, or whether it would foul up anyone's usage of the counts - or especially the search results - to have BP terms retrieved by a query for MF. For counts on gene pages I suppose we could just make an executive decision, document the hell out of it, and hope for the best. When it comes to search behavior, it might be wise to offer an explicit option to include or exclude inter-ontology retrieval. 

- Do you mean to have MF terms returned on a query for BP? A query for MF should not return BP?

- I don't think that is necessary to offer inclusion or exclusion of inter-ontology links for querying. They should be included for MF part_of BP to make the counts correct.

The current situation is that although we don't include F-P links explicitly in PomBase, 
 we haven't needed to because the annotations are automatically materialized by GOC. If this did not happen the counts  would  not reflect the biology  for biological process correctly. 

Looking back, last news was that materializing inferred MF-BP  annotations is still likely
https://github.com/geneontology/go-annotation/issues/1427 
so the counts should  be largely correct for most terms.

However, we might need to use F-P links because  in some cases.  I have blocked/filtered display of  the some modification process annotations so that they do not appear on the gene pages. For example, "protein phosphorylation" from inferred links is suppressed so that we don't see a redundant "protein phosphorylation" annotation  for every "protein kinase activity" annotation, where the "phosphorylation" annotation is not required because it is not telling the user anything about the biological role.

Where "protein  phosphorylation" is displayed  it is because the term is explicitly annotated. However the counts (and the queries) should include annotations which would be generated via F-P links.  I can't figure out if the F-P links are being followed in the current PomBase (counts of queries).....I think probably not. I'll check next time I come across a protein kinase annotation that doesn't not have an explicit phosphorylation annotation.

**Comment by mah11** [comment]
> Do you mean to have MF terms returned on a query for BP? A query for MF should not return BP?

Ah, right, missed out a step above. What I was thinking of was from a gene-centric POV and asking what terms it's annotated to; got that mixed up with querying from a term POV. For gene page counts, ignore that bit (also clarified in comment above.)

> the counts (and the queries) should include annotations which would be generated via F-P links. I can't figure out if the F-P links are being followed in the current PomBase (counts of queries).....I think probably not. 

One of Kim's comments on this ticket suggests that PomBase2 loading/display/etc. isn't doing anything at our end to use MF-BP links yet. I don't know whether it's loading the inferred annotations from GO, but even if they are getting in, that set is woefully incomplete at the moment due to the bug from ticket https://github.com/geneontology/go-annotation/issues/1336.

The question of whether the gene pages should show BP terms reached via MF-BP links feels like it's off on a tangent from the topic of this ticket. If GO materializes them (and fixes the bug), and we use the .inf.gaf annotations, it's moot.

**Comment by kimrutherford** [comment]
> PomBase2 loading/display/etc. isn't doing anything at our end to use MF-BP links yet

It's currently getting data only from Chado and there are no MF-BP relationships in Chado.  We load Chado from go-plus.obo

**Comment by kimrutherford** [comment]
> The MF-BP links are in the go.* and go-plus.* versions of the GO files.

Could you send me an example so I can track down why they are being stored in Chado?

**Comment by kimrutherford** [comment]
> I think annotated genes should be the default view. 

OK, will do.

**Comment by kimrutherford** [comment]
>>   What relations should be used for find descendant for FYPO?
> Follow is_a and part_of as for GO.

Thanks.  That should be working then.

**Comment by kimrutherford** [comment]
> There should be lots of has_part links between FYPO terms, and they should be followed
> the same way as it works in Canto.

OK, I'll work on that.  New issue:  #89

**Comment by kimrutherford** [comment]
> When it comes to search behavior, it might be wise to offer an explicit option to include
> or exclude inter-ontology retrieval. (And I hope that's technically feasible!)

I hope to copy (as much as and if possible) the search engine behind Amigo2 but I haven't looked into that at all yet.  So if Amigo2 can do it we can.  Does annotation shown in Amigo2 include descendants found by following MF-BP links?

**Comment by kimrutherford** [comment]
> So "Annotated genes" would be the most accurate header, but it's annoyingly long. 

I would like to have a pop-up description for each column heading which will help.

**Comment by mah11** [comment]
> > The MF-BP links are in the go.* and go-plus.* versions of the GO files.
> 
> Could you send me an example so I can track down why they are being stored in Chado?

here are three:
GO:0008233 peptidase activity part_of GO:0006508 proteolysis
GO:0071164 RNA trimethylguanosine synthase activity part_of GO:0036261 7-methylguanosine cap hypermethylation
*GO:0005484 SNAP receptor activity part_of GO:0061025 membrane fusion

*for this example, the inferred annotation should be in the inf.gaf but isn't (that bug)

**Comment by ValWood** [comment]
if the F_P links are fiddly, put them on the back burner because it only affects the small number of modification process term totals where I have filtered. You might prefer that we do this another way.
We could load all of the data (which should make all the queries correct even if F-P links are excluded), and then just flag some terms  for the annotation not to appear on the gene pages if this is easier.
I would just need to process the list  as GO IDs are added for  other reasons. One is if there are terms we don't like to anntotate to at all like "cell proliferation" .
We can discuss on next call.

**Comment by kimrutherford** [comment]
I've been having a look at the problem.  We're loading go-basic.obo into Chado and that doesn't seem to have the cross CV links.  So that's probably an easy fix.  I was wondering about using the pombe-only version go-plus.obo instead.   That would have all the MF-BP links and none of the non-pombe terms.

**Comment by ValWood** [comment]
> The question of whether the gene pages should show BP terms reached via MF-BP links feels like it's off on a tangent from the topic of this ticket. If GO materializes them (and fixes the bug), and we use the .inf.gaf annotations, it's moot.

I don't think it is quite because of some quirky filtering I do (see above).
However, for now we won't worry about this.
I will check future counts and if there is an issue I'll open a ticket explaining properly.

**Comment by kimrutherford** [comment]
> We're loading go-basic.obo into Chado and that doesn't seem to have the cross CV links.
> I was already wondering about using the pombe-only version of go-plus.obo instead.

I was tidying us my Inbox today and found email email from Midori pointing out this issue:
  https://github.com/geneontology/go-annotation/issues/1427
which might be relevant.

**Comment by mah11** [comment]
yes, I linked to that ticket here a few days ago (https://github.com/pombase/website/issues/84#issuecomment-262056854)

**Comment by mah11** [comment]
> Does annotation shown in Amigo2 include descendants found by following MF-BP links?

I did a bit of digging to try to answer this q. Of course it's not a simple, convenient "yes" or "no"; it depends on whether you start from a gene- or GO term-centric perspective.

On the page of details for a gene (product), it only shows directly annotated terms in the main display table. That set of direct annotations will include ones derived by following MF-BP links*, though, because the Jenkins system generates direct annotations and we incorporate them (that's the inf.gaf file I've been banging on about).

There's also a link in the left-hand sidebar to see all terms annotated by transitivity, which follows all is_a, part_of, and regulates links, including MF-part_of-BP. The annotation download thingy offers a somewhat unintuitive set of options that look like they can include or exclude annotations inferred from MF-BP even if they aren't available as 'direct' annotations via the .inf.gaf route, but I didn't try testing it.

It's slightly different if I start with a GO term - the results include a "genes and gene products" link, and that page has a table that does include genes annotated transitively via MF-BP. [I was able to test this because of that GO bug (https://github.com/geneontology/go-annotation/issues/1336), so I guess it's had a bit of a silver lining.]

The bottom line is that AmiGO does appear to follow MF-BP links in some cases, so there must be code in there somewhere to do it.

**Comment by ValWood** [comment]
OK there is a lot going on in this ticket!
It seems to be more discussion than actions so I am going to close it.
I will open a new ticket for anything i think still requires discussion.

**Comment by ValWood** [comment]
OK, I pulled out the F-P links discussion part.
I think 
i) the FYPO inference topic is covered by another ticket,
ii) "Others" lists  is done (or needs new ticket for changes)
iii) Other actions may be required but no direct actions were identified in this ticket so hopefully they will resurface as necessary
