### ISSUE TITLE
Quick little gene list tool, download table

### ISSUE THREAD

**Issue by Antonialock** [pombase/website#884]
add the ability to export the results of the analysis as a table

e.g
gene viability component
abc1 inviable nucleus
yfg1 viable mitochondrion

Jurgs group wanted this for import into R

**Comment by ValWood** [comment]
we'll do this at the end with other download stuff that needs doing

**Comment by kimrutherford** [comment]
> we'll do this at the end with other download stuff that needs doing

I thought I'd give this a go even though it's not urgent.  I wanted to try adding extra download options.

The ortholog present/absent options aren't there yet because it doesn't work in the downloads yet.  :-)

This is only visible in pombase-dev:

![vis-download-options-1](https://user-images.githubusercontent.com/90474/44254103-e4d6c380-a255-11e8-9779-09a270a7db19.png)

**Comment by ValWood** [comment]
Good start. Looks good so far.
Note that the GO stuff is not done in the main download yet so this also doesn't work here...

**Comment by kimrutherford** [comment]
> Note that the GO stuff is not done in the main download yet so this also doesn't work here...

What do you mean by "main download"?

I've only added the options in pombase-dev for now.

**Comment by ValWood** [comment]
I mean we can't do GO here yet:

![standard](https://user-images.githubusercontent.com/7359272/44387174-b9d1c580-a51c-11e8-8ced-9d64a35065cf.jpg)

So it should also be excluded.

**Comment by kimrutherford** [comment]
> So it should also be excluded.

Sorry, I still don't follow.  Excluded from what?

**Comment by ValWood** [comment]
we have GO options on the quick little tool. We should not have them yet:

![quick little](https://user-images.githubusercontent.com/7359272/44387893-afb0c680-a51e-11e8-9d3d-34896c920d6a.jpg)

**Comment by kimrutherford** [comment]
> we have GO options on the quick little tool. We should not have them yet:

That's only in pombase-dev.  Should I remove them?

**Comment by ValWood** [comment]
> That's only in pombase-dev. Should I remove them?

I think remove them on dev, because likely we can make this live before the GO and orthologs are handled more generally.
Or we could  visit that with this ticket.

We need to think about the GO stuff because the GO behaviour will need to be slightly different here than on the main download. We can chat about this on Thursday.

**Comment by kimrutherford** [comment]
> I think remove them on dev

OK, I've done that.

**Comment by ValWood** [comment]
done for this ticket so far?

**Comment by ValWood** [comment]
the GO data download is undecided. We have 3 other tickets about this: I will combine these into a single ticket.

Implement GO ids in advanced tool download spreadsheet #1487
https://github.com/pombase/website/issues/1487

GAF downloads (from advanced search etc)
https://github.com/pombase/website/issues/949

Download most specific ontology terms used to annotate gene products #1026
https://github.com/pombase/website/issues/1026
