### ISSUE TITLE
missing annotation?

### ISSUE THREAD

**Issue by ValWood** [pombase/website#900]
https://www.pombase.org/reference/PMID:11702950

protein binding
--
  | rad24 binds transcription factor ste11 phosphorylated 1 (Schizosaccharomyces pombe) binds ste11

I don't see this on the rad24 page?

**Comment by kimrutherford** [comment]
Isn't this it from the rad24 page?:

![rad24-ste11-1](https://user-images.githubusercontent.com/90474/43881240-ad54fd20-9bff-11e8-8dec-e611cc17d700.png)

**Comment by Antonialock** [comment]
Weird...rad24 seems to have several go protein binding annotations that
show on the publication page and detailed view in gene pages, but not in
the collapsed view


Collapsed





Detailed view



-- 
Antonia Lock, PhD
PomBase Biocurator, http://www.pombase.org
Department of Genetics, Evolution and Environment,
The Darwin Building,
University College London
London WC1E 6BT, UK

**Comment by ValWood** [comment]
yes this is related to the ticket I wanted to discuss today!
PR ID display https://github.com/pombase/canto/issues/1591

I think it's because the gene is not specified, only the modified entity, maybe?

**Comment by ValWood** [comment]
although
binds ste11 | IPI | Kitamura K et al. (2001)


is there on its own.....

**Comment by kimrutherford** [comment]
So is the bug that the annotation is missing from the summary?

**Comment by Antonialock** [comment]
It looks like it?

**Comment by kimrutherford** [comment]
Turns out there were quite a few annotations missing from summaries.

On the rad24 page this was missing too:

    binds tyrosine-protein phosphatase Clp1 phosphorylated 1 (Schizosaccharomyces pombe)
       binds clp1

Another example, on the ste11 page, this was missing:

     binds transcription factor ste11 phosphorylated 1 (Schizosaccharomyces pombe)
         binds rad24
         part of negative regulation of transcription by RNA polymerase II

And:  ` binds rad24 active form PR:000027543 `

It took a while to track down the problem, but it's fixed now.

It was only happening in cases where the same relation (like binds) can have two different range types.  eg. binds(PR:000027543) vs binds(SPAC8E11.02c).

There aren't a lot of pages where that happens which is why we hadn't noticed.
