### ISSUE TITLE
Change precedence of MF in QLTool

### ISSUE THREAD

**Issue by ValWood** [pombase/website#990]
DNA binding (GO:0003677)
transcription regulator activity (GO:0140110)

**Comment by kimrutherford** [comment]
This is the current list.  Should we just swap the positions of GO:0003677 and GO:0140110?

GO:0016491                                                                                                                                                                                    
GO:0016787
GO:0016740
GO:0016874
GO:0009975
GO:0016829
GO:0003824
GO:0030234
GO:0140110
GO:0005215
GO:0008092
GO:0051082
GO:0003677
GO:0003723
GO:0046872
GO:0008289
GO:0098631
GO:0005198

**Comment by ValWood** [comment]
just move GO:0003677 to above  GO:0140110 keeping everything else the same..

**Comment by kimrutherford** [comment]
That change is done now.  It should be visible in the morning.

**Comment by ValWood** [comment]
"DNA binding" does not seem to take precedence over "transcription regulator"

**Comment by kimrutherford** [comment]
Sorry, I forgot to check the change in.

I got distracted because there is redundancy in how the order/priority of terms is configured and I wanted to fix it before we launch.  The fix is half finished so I should have that done before the overnight load get to that point tonight.

I'll check in the morning.

**Comment by kimrutherford** [comment]
I think this is fixed now.
